Repository apache/streampark, pull requests merged in 2023-12, with the labels that each got.

#3371 [Improve] Maven wrapper improvement
  .mvn/wrapper/MavenWrapperHelper.java
  .mvn/wrapper/maven-wrapper.properties
  build.sh
  mvnw
  streampark-console/streampark-console-service/src/main/assembly/bin/mvnw
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/entity/Project.java
Labels: BUILD, BACKEND

#3374 [Improve] fix myBatis query for like using concat function
  streampark-console/streampark-console-service/src/main/resources/mapper/core/ApplicationMapper.xml
  streampark-console/streampark-console-service/src/main/resources/mapper/core/ProjectMapper.xml
  streampark-console/streampark-console-service/src/main/resources/mapper/core/ResourceMapper.xml
  streampark-console/streampark-console-service/src/main/resources/mapper/core/VariableMapper.xml
  streampark-console/streampark-console-service/src/main/resources/mapper/core/YarnQueueMapper.xml
  streampark-console/streampark-console-service/src/main/resources/mapper/system/MemberMapper.xml
  streampark-console/streampark-console-service/src/main/resources/mapper/system/RoleMapper.xml
  streampark-console/streampark-console-service/src/main/resources/mapper/system/TeamMapper.xml
  streampark-console/streampark-console-service/src/main/resources/mapper/system/UserMapper.xml
Labels: BACKEND

#3383 [Improve] FE links improvement
  streampark-console/streampark-console-service/src/main/resources/db/data-h2.sql
  streampark-console/streampark-console-webapp/src/views/setting/extlink/View.vue
  streampark-console/streampark-console-webapp/src/views/setting/extlink/components/Modal.vue
  streampark-console/streampark-console-webapp/src/views/setting/extlink/components/index.ts
  streampark-console/streampark-console-webapp/src/views/setting/extlink/components/useExternalLink.tsx
Labels: WEB UI, BACKEND

#3385 [Fix] Fix rabc lost ingress/deployments resources permission when fli…
  deploy/helm/streampark/templates/rbac.yaml
Labels: DOCKER

#3386 [Improve] http check improvement
  streampark-common/src/main/scala/org/apache/streampark/common/util/Utils.scala
Labels: BACKEND

#3380 [fixBug] yarnUtil restRequest error,illegal character in RM url bug
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/watcher/FlinkAppHttpWatcher.java
Labels: BACKEND

#3384 [Improve] FE links improvement
  streampark-console/streampark-console-service/src/main/assembly/script/data/mysql-data.sql
Labels: BUILD, BACKEND

#3392 [FIX] fix sql error when copy job
  streampark-console/streampark-console-service/src/main/assembly/script/upgrade/mysql/2.1.2.sql
Labels: BUILD, BACKEND

#3395 [ISSUE-3393][Fix]fix mybatis-plus enum annotation
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/base/config/MybatisConfig.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/entity/Message.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/MessageServiceImpl.java
Labels: BACKEND

#3389 [ISSUE-3046][Improve] Improve streampark-common module base on 3.3 Methods Rule
  streampark-common/src/main/java/org/apache/streampark/common/enums/ApplicationType.java
  streampark-common/src/main/java/org/apache/streampark/common/enums/ClusterState.java
  streampark-common/src/main/java/org/apache/streampark/common/enums/FlinkDevelopmentMode.java
  streampark-common/src/main/java/org/apache/streampark/common/enums/FlinkExecutionMode.java
  streampark-common/src/main/java/org/apache/streampark/common/enums/FlinkK8sRestExposedType.java
  streampark-common/src/main/java/org/apache/streampark/common/enums/FlinkRestoreMode.java
  streampark-common/src/main/java/org/apache/streampark/common/enums/FlinkSqlValidationFailedType.java
  streampark-common/src/main/java/org/apache/streampark/common/enums/ResolveOrder.java
  streampark-common/src/main/java/org/apache/streampark/common/enums/Semantic.java
  streampark-common/src/main/java/org/apache/streampark/common/enums/StorageType.java
  streampark-common/src/main/java/org/apache/streampark/common/util/ExceptionUtils.java
Labels: BACKEND

#3398 [Improve] check maven-wrapper improvement
  .mvn/wrapper/MavenWrapperHelper.java
  .mvn/wrapper/maven-wrapper.properties
  mvnw
  streampark-console/streampark-console-service/src/main/assembly/bin/mvnw
  streampark-console/streampark-console-service/src/main/assembly/bin/streampark.sh
Labels: BUILD, BACKEND

#3404 [Improve] Twitter links minor improvement
  README.md
Labels: DOCS

#3406 [Improve] pgsql ddl improve
  streampark-console/streampark-console-service/src/main/assembly/script/data/pgsql-data.sql
  streampark-console/streampark-console-service/src/main/assembly/script/schema/pgsql-schema.sql
Labels: BUILD, BACKEND

#3409 [ISSUE-3405][Feature] Avoid Null Pointer Exception in switch keyword
  streampark-common/src/main/java/org/apache/streampark/common/enums/ApplicationType.java
  streampark-common/src/main/java/org/apache/streampark/common/enums/FlinkDevelopmentMode.java
  streampark-common/src/main/java/org/apache/streampark/common/enums/FlinkExecutionMode.java
Labels: BACKEND

#3413 [ISSUE-3057][Improve] Improve streampark-common module base on [3.7 Code Comments Rule]
  streampark-common/src/main/java/org/apache/streampark/common/enums/ApplicationType.java
  streampark-common/src/main/java/org/apache/streampark/common/enums/ClusterState.java
  streampark-common/src/main/java/org/apache/streampark/common/enums/FlinkDevelopmentMode.java
  streampark-common/src/main/java/org/apache/streampark/common/enums/FlinkExecutionMode.java
  streampark-common/src/main/java/org/apache/streampark/common/enums/FlinkK8sRestExposedType.java
  streampark-common/src/main/java/org/apache/streampark/common/enums/FlinkRestoreMode.java
  streampark-common/src/main/java/org/apache/streampark/common/enums/FlinkSqlValidationFailedType.java
  streampark-common/src/main/java/org/apache/streampark/common/enums/ResolveOrder.java
  streampark-common/src/main/java/org/apache/streampark/common/enums/Semantic.java
  streampark-common/src/main/java/org/apache/streampark/common/enums/StorageType.java
  streampark-common/src/main/java/org/apache/streampark/common/util/ExceptionUtils.java
Labels: BACKEND

#3416 [Fix] Fix submit to k8s retry and timeout too less.
  streampark-flink/streampark-flink-kubernetes/src/main/scala/org/apache/streampark/flink/kubernetes/KubernetesRetriever.scala
Labels: FLINK, KUBERNETES

#3422 [ISSUE-3057][Improve] Improve streampark-common module base on [3.10 Pre-Conditions Checking]
  streampark-common/src/main/scala/org/apache/streampark/common/util/ClassLoaderUtils.scala
  streampark-common/src/main/scala/org/apache/streampark/common/util/Utils.scala
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/controller/ApplicationController.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/task/ProjectBuildTask.java
  streampark-flink/streampark-flink-packer/src/main/scala/org/apache/streampark/flink/packer/maven/MavenTool.scala
Labels: BACKEND, FLINK

#3421 [ISSUE-3057][Improve] Improve streampark-common module base on [3.10 Pre-Conditions Checking]
  streampark-common/src/main/scala/org/apache/streampark/common/fs/LfsOperator.scala
  streampark-common/src/main/scala/org/apache/streampark/common/util/FileUtils.scala
  streampark-common/src/main/scala/org/apache/streampark/common/util/PropertiesUtils.scala
  streampark-common/src/main/scala/org/apache/streampark/common/util/Utils.scala
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/bean/Dependency.java
  streampark-flink/streampark-flink-packer/src/main/scala/org/apache/streampark/flink/packer/docker/DockerRetriever.scala
Labels: BACKEND, FLINK

#3420 [ISSUE-3057][Improve] Improve streampark-common module base on [3.10 Pre-Conditions Checking]
  streampark-common/src/main/scala/org/apache/streampark/common/util/Logger.scala
  streampark-common/src/main/scala/org/apache/streampark/common/util/Utils.scala
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/controller/ExternalLinkController.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/runner/EnvInitializer.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/application/impl/ApplicationActionServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/AppBuildPipeServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ExternalLinkServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/FlinkSqlServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ProjectServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/SavePointServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/SqlCompleteServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/YarnQueueServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/service/impl/UserServiceImpl.java
  streampark-tests/streampark-testcontainer/src/main/java/org/apache/streampark/testcontainer/flink/FlinkStandaloneSessionCluster.java
Labels: BACKEND

#3417 [Fix] Fix submit to k8s retry and timeout too less
  streampark-flink/streampark-flink-kubernetes/src/main/scala/org/apache/streampark/flink/kubernetes/KubernetesRetriever.scala
Labels: FLINK, KUBERNETES

#3403 [Improve] resource improvement
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/enums/ResourceTypeEnum.java
  streampark-console/streampark-console-service/src/main/resources/db/data-h2.sql
  streampark-console/streampark-console-webapp/src/components/Form/src/components/FormItem.vue
  streampark-console/streampark-console-webapp/src/components/Modal/src/components/ModalWrapper.vue
  streampark-console/streampark-console-webapp/src/hooks/setting/useMenuSetting.ts
  streampark-console/streampark-console-webapp/src/locales/lang/zh-CN/flink/resource.ts
  streampark-console/streampark-console-webapp/src/locales/lang/zh-CN/menu.ts
  streampark-console/streampark-console-webapp/src/utils/props.ts
  streampark-console/streampark-console-webapp/src/views/base/error-log/data.tsx
  streampark-console/streampark-console-webapp/src/views/resource/upload/View.vue
  streampark-console/streampark-console-webapp/src/views/resource/upload/components/Upload.vue
  streampark-console/streampark-console-webapp/src/views/resource/upload/components/UploadDrawer.vue
  streampark-console/streampark-console-webapp/src/views/resource/upload/upload.data.ts
  streampark-console/streampark-console-webapp/src/views/resource/upload/useUploadRender.tsx
  streampark-console/streampark-console-webapp/src/views/resource/variable/components/VariableDrawer.vue
Labels: WEB UI, BACKEND

#3425 [Improve] deploy flink job on k8s timeout improvement
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/entity/Project.java
  streampark-flink/streampark-flink-client/streampark-flink-client-core/src/main/scala/org/apache/streampark/flink/client/tool/FlinkSessionClientHelper.scala
  streampark-flink/streampark-flink-kubernetes/src/main/scala/org/apache/streampark/flink/kubernetes/KubernetesRetriever.scala
  streampark-flink/streampark-flink-kubernetes/src/main/scala/org/apache/streampark/flink/kubernetes/watcher/FlinkCheckpointWatcher.scala
  streampark-flink/streampark-flink-kubernetes/src/main/scala/org/apache/streampark/flink/kubernetes/watcher/FlinkJobStatusWatcher.scala
  streampark-flink/streampark-flink-kubernetes/src/main/scala/org/apache/streampark/flink/kubernetes/watcher/FlinkMetricsWatcher.scala
Labels: BACKEND, FLINK, KUBERNETES

#3427 [Improve] Use StringUtils.isNotBlank instead of StringUtils.isNotEmpty
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/entity/Project.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/SavePointServiceImpl.java
Labels: BACKEND

#3429 fix check Comment
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/FlinkEnvServiceImpl.java
Labels: BACKEND

#3426 [Feature] flink cluster operation logic changes
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/controller/FlinkClusterController.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/FlinkClusterService.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/application/impl/ApplicationActionServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/application/impl/ApplicationManageServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/FlinkClusterServiceImpl.java
Labels: BACKEND

#3432 [FIX] t_flink_app init error
  streampark-console/streampark-console-service/src/main/assembly/script/data/mysql-data.sql
  streampark-console/streampark-console-service/src/main/assembly/script/data/pgsql-data.sql
Labels: BUILD, BACKEND

#3401 [Feature] User can use different hadoop-user to submit application
  streampark-console/streampark-console-service/src/main/assembly/script/upgrade/mysql/2.2.0.sql
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/entity/Application.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/application/impl/ApplicationActionServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/application/impl/ApplicationManageServiceImpl.java
  streampark-console/streampark-console-service/src/main/resources/db/schema-h2.sql
  streampark-console/streampark-console-webapp/src/api/flink/app.type.ts
  streampark-console/streampark-console-webapp/src/locales/lang/en/flink/app.ts
  streampark-console/streampark-console-webapp/src/locales/lang/zh-CN/flink/app.ts
  streampark-console/streampark-console-webapp/src/views/flink/app/EditFlink.vue
  streampark-console/streampark-console-webapp/src/views/flink/app/hooks/useCreateAndEditSchema.ts
  streampark-console/streampark-console-webapp/src/views/flink/app/utils/index.ts
  streampark-flink/streampark-flink-client/streampark-flink-client-api/src/main/scala/org/apache/streampark/flink/client/bean/SubmitRequest.scala
  streampark-flink/streampark-flink-client/streampark-flink-client-core/src/main/scala/org/apache/streampark/flink/client/impl/YarnApplicationClient.scala
Labels: BUILD, WEB UI, BACKEND, FLINK

#3439 [improve] improve resource management logic
  streampark-common/src/main/java/org/apache/streampark/common/util/ExceptionUtils.java
  streampark-common/src/main/scala/org/apache/streampark/common/util/Utils.scala
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/application/impl/ApplicationInfoServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ResourceServiceImpl.java
Labels: BACKEND

#3435 [Improve#3068] Improve streampark-console module base on [3.5 Concurrent Processing]
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/base/config/AsyncExecutorPoolConfig.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/application/impl/ApplicationActionServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/AppBuildPipeServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/FlinkClusterServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ProjectServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/SavePointServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/watcher/FlinkAppHttpWatcher.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/watcher/FlinkClusterWatcher.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/watcher/FlinkK8sChangeEventListener.java
Labels: BACKEND
