Repository apache/streampark, pull requests merged in 2023-09, with the labels that each got.

#3011 [Hotfix][translation] Translate the ignored comments.
  streampark-flink/streampark-flink-shims/streampark-flink-shims-base/src/main/java/org/apache/streampark/flink/core/StreamEnvConfigFunction.java
  streampark-flink/streampark-flink-shims/streampark-flink-shims-base/src/main/java/org/apache/streampark/flink/core/TableEnvConfigFunction.java
Labels: FLINK

#2956 [Feature] Yarn supports pyflink
  streampark-common/src/main/scala/org/apache/streampark/common/conf/ConfigConst.scala
  streampark-common/src/main/scala/org/apache/streampark/common/conf/Workspace.scala
  streampark-common/src/main/scala/org/apache/streampark/common/util/EnvUtils.java
  streampark-console/streampark-console-service/src/main/assembly/assembly.xml
  streampark-console/streampark-console-service/src/main/assembly/python/.gitkeep
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ApplicationServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ResourceServiceImpl.java
  streampark-console/streampark-console-webapp/src/locales/lang/en/flink/app.ts
  streampark-console/streampark-console-webapp/src/locales/lang/zh-CN/flink/app.ts
  streampark-console/streampark-console-webapp/src/views/flink/app/components/UploadJobJar.vue
  streampark-flink/streampark-flink-client/streampark-flink-client-api/src/main/scala/org/apache/streampark/flink/client/bean/SubmitRequest.scala
  streampark-flink/streampark-flink-client/streampark-flink-client-core/pom.xml
  streampark-flink/streampark-flink-client/streampark-flink-client-core/src/main/resources/pyflink.md
  streampark-flink/streampark-flink-client/streampark-flink-client-core/src/main/scala/org/apache/streampark/flink/client/impl/YarnApplicationClient.scala
  streampark-flink/streampark-flink-client/streampark-flink-client-core/src/main/scala/org/apache/streampark/flink/client/trait/FlinkClientTrait.scala
  streampark-flink/streampark-flink-shims/streampark-flink-shims-base/src/main/scala/org/apache/streampark/flink/util/FlinkUtils.scala
Labels: BUILD, WEB UI, BACKEND, FLINK

#2981 [Improve] FileUtils minor improvement
  streampark-common/src/main/scala/org/apache/streampark/common/conf/ConfigOption.scala
  streampark-common/src/main/scala/org/apache/streampark/common/conf/InternalConfigHolder.scala
  streampark-common/src/main/scala/org/apache/streampark/common/conf/Workspace.scala
  streampark-common/src/main/scala/org/apache/streampark/common/util/FileUtils.scala
  streampark-common/src/main/scala/org/apache/streampark/common/util/HadoopUtils.scala
  streampark-common/src/main/scala/org/apache/streampark/common/util/ImplicitsUtils.scala
  streampark-common/src/main/scala/org/apache/streampark/common/util/Logger.scala
  streampark-common/src/main/scala/org/apache/streampark/common/util/Utils.scala
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/base/util/FileUtils.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/AppBuildPipeServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ApplicationServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ProjectServiceImpl.java
  streampark-console/streampark-console-service/src/test/java/org/apache/streampark/console/base/util/FileUtilsTest.java
  streampark-flink/streampark-flink-client/streampark-flink-client-core/src/main/scala/org/apache/streampark/flink/client/trait/YarnClientTrait.scala
  streampark-flink/streampark-flink-kubernetes/src/main/scala/org/apache/streampark/flink/kubernetes/KubernetesRetriever.scala
  streampark-flink/streampark-flink-kubernetes/src/main/scala/org/apache/streampark/flink/kubernetes/helper/KubernetesDeploymentHelper.scala
  streampark-flink/streampark-flink-kubernetes/src/main/scala/org/apache/streampark/flink/kubernetes/ingress/IngressController.scala
  streampark-flink/streampark-flink-kubernetes/src/main/scala/org/apache/streampark/flink/kubernetes/ingress/IngressStrategyV1.scala
  streampark-flink/streampark-flink-kubernetes/src/main/scala/org/apache/streampark/flink/kubernetes/ingress/IngressStrategyV1beta1.scala
  streampark-flink/streampark-flink-packer/src/main/scala/org/apache/streampark/flink/packer/pipeline/impl/FlinkYarnApplicationBuildPipeline.scala
  streampark-flink/streampark-flink-proxy/src/main/scala/org/apache/streampark/flink/proxy/FlinkShimsProxy.scala
  streampark-flink/streampark-flink-shims/streampark-flink-shims-base/src/main/scala/org/apache/streampark/flink/core/FlinkStreamingInitializer.scala
Labels: BACKEND, FLINK, KUBERNETES

#3006 [ISSUE-2940][Improve] enhance login password protection
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/security/impl/AuthenticatorImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/service/UserService.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/service/impl/UserServiceImpl.java
Labels: BACKEND

#3010 [Improve] Packer module code optimization
  streampark-common/src/main/scala/org/apache/streampark/common/util/Utils.scala
  streampark-flink/streampark-flink-kubernetes/src/main/scala/org/apache/streampark/flink/kubernetes/PodTemplateTool.scala
  streampark-flink/streampark-flink-kubernetes/src/main/scala/org/apache/streampark/flink/kubernetes/model/K8sPodTemplates.scala
  streampark-flink/streampark-flink-packer/src/main/scala/org/apache/streampark/flink/packer/pipeline/DockerResolveProgress.scala
  streampark-flink/streampark-flink-packer/src/main/scala/org/apache/streampark/flink/packer/pipeline/impl/FlinkK8sApplicationBuildPipeline.scala
  streampark-flink/streampark-flink-packer/src/main/scala/org/apache/streampark/flink/packer/pipeline/impl/FlinkYarnApplicationBuildPipeline.scala
Labels: BACKEND, FLINK, KUBERNETES

#2942 Modify pgsql-schema.sql
  streampark-console/streampark-console-service/src/main/assembly/script/schema/pgsql-schema.sql
  streampark-console/streampark-console-service/src/main/assembly/script/upgrade/pgsql/2.2.0.sql
Labels: BUILD, BACKEND

#3009 [Refactor] Refactor ApplicationService moving it to own package and creating two interfaces.
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/aspect/StreamParkAspect.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/controller/ApplicationController.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/controller/ApplicationHistoryController.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/controller/SavePointController.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/ApplicationService.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/alert/impl/AlertConfigServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/application/ApplicationActionService.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/application/ApplicationInfoService.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/application/ApplicationManageService.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/application/impl/ApplicationActionServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/application/impl/ApplicationInfoServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/application/impl/ApplicationManageServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/AppBuildPipeServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ApplicationBackUpServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ApplicationServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ExternalLinkServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/FlinkClusterServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/FlinkEnvServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ProjectServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ResourceServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/SavePointServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/VariableServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/YarnQueueServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/task/CheckpointProcessor.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/task/FlinkClusterWatcher.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/task/FlinkHttpWatcher.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/task/FlinkK8sChangeEventListener.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/task/FlinkK8sWatcherWrapper.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/service/impl/TeamServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/service/impl/UserServiceImpl.java
  streampark-console/streampark-console-service/src/test/java/org/apache/streampark/console/core/service/ApplicationManageServiceITest.java
  streampark-console/streampark-console-service/src/test/java/org/apache/streampark/console/core/service/ApplicationManageServiceTest.java
  streampark-console/streampark-console-service/src/test/java/org/apache/streampark/console/core/service/SavePointServiceTest.java
  streampark-console/streampark-console-service/src/test/java/org/apache/streampark/console/core/service/UserServiceTest.java
  streampark-console/streampark-console-service/src/test/java/org/apache/streampark/console/core/service/YarnQueueServiceTest.java
Labels: BACKEND

#3015 [Improve] application service minor improvement
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/controller/ApplicationController.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/application/ApplicationActionService.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/application/ApplicationInfoService.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/application/ApplicationManageService.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/application/impl/ApplicationActionServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/application/impl/ApplicationInfoServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/application/impl/ApplicationManageServiceImpl.java
  streampark-console/streampark-console-service/src/test/java/org/apache/streampark/console/core/service/ApplicationManageServiceITest.java
Labels: BACKEND

#3014 [Improve] pyflink improvement
  streampark-common/src/main/java/org/apache/streampark/common/enums/DevelopmentMode.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/ApplicationBackUpService.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/application/impl/ApplicationActionServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ApplicationBackUpServiceImpl.java
  streampark-flink/streampark-flink-client/streampark-flink-client-api/src/main/scala/org/apache/streampark/flink/client/bean/SubmitRequest.scala
  streampark-flink/streampark-flink-client/streampark-flink-client-core/src/main/scala/org/apache/streampark/flink/client/impl/KubernetesNativeSessionClient.scala
  streampark-flink/streampark-flink-client/streampark-flink-client-core/src/main/scala/org/apache/streampark/flink/client/impl/LocalClient.scala
  streampark-flink/streampark-flink-client/streampark-flink-client-core/src/main/scala/org/apache/streampark/flink/client/impl/RemoteClient.scala
  streampark-flink/streampark-flink-client/streampark-flink-client-core/src/main/scala/org/apache/streampark/flink/client/impl/YarnApplicationClient.scala
  streampark-flink/streampark-flink-client/streampark-flink-client-core/src/main/scala/org/apache/streampark/flink/client/impl/YarnPerJobClient.scala
  streampark-flink/streampark-flink-client/streampark-flink-client-core/src/main/scala/org/apache/streampark/flink/client/impl/YarnSessionClient.scala
  streampark-flink/streampark-flink-client/streampark-flink-client-core/src/main/scala/org/apache/streampark/flink/client/trait/FlinkClientTrait.scala
  streampark-flink/streampark-flink-shims/streampark-flink-shims-base/src/main/scala/org/apache/streampark/flink/util/FlinkUtils.scala
Labels: BACKEND, FLINK

#3016 [FIX] fix pyflink bug
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/entity/Application.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/AppBuildPipeServiceImpl.java
  streampark-console/streampark-console-webapp/src/enums/flinkEnum.ts
  streampark-console/streampark-console-webapp/src/views/flink/app/Add.vue
  streampark-console/streampark-console-webapp/src/views/flink/app/hooks/useCreateSchema.ts
  streampark-flink/streampark-flink-client/streampark-flink-client-core/src/main/scala/org/apache/streampark/flink/client/impl/YarnApplicationClient.scala
  streampark-flink/streampark-flink-client/streampark-flink-client-core/src/main/scala/org/apache/streampark/flink/client/trait/FlinkClientTrait.scala
Labels: WEB UI, BACKEND, FLINK

#3017 [Fix] Slim the pac4j package
  dist-material/release-docs/LICENSE
  streampark-console/streampark-console-service/pom.xml
Labels: BUILD, BACKEND

#3019 [Improve] Using code style & quality rules to improve org.apache.stre…
  streampark-common/src/main/java/org/apache/streampark/common/enums/ClusterState.java
  streampark-common/src/main/java/org/apache/streampark/common/enums/RestoreMode.java
Labels: BACKEND

#3021 [Improve] merge from dev
  deploy/helm/README.md
  deploy/helm/streampark/templates/ingress.yaml
  deploy/helm/streampark/templates/streampark.yml
  deploy/helm/streampark/values.yaml
  dist-material/release-docs/LICENSE
  pom.xml
  streampark-common/src/main/scala/org/apache/streampark/common/conf/K8sFlinkConfig.scala
  streampark-console/streampark-console-service/src/main/assembly/bin/streampark.sh
  streampark-console/streampark-console-service/src/main/resources/application.yml
  streampark-console/streampark-console-webapp/src/components/Form/src/hooks/useFormEvents.ts
  streampark-console/streampark-console-webapp/src/layouts/default/header/components/notify/index.vue
  streampark-flink/streampark-flink-client/streampark-flink-client-core/src/main/scala/org/apache/streampark/flink/client/trait/FlinkClientTrait.scala
  streampark-flink/streampark-flink-kubernetes/src/main/scala/org/apache/streampark/flink/kubernetes/helper/KubernetesDeploymentHelper.scala
  streampark-flink/streampark-flink-kubernetes/src/main/scala/org/apache/streampark/flink/kubernetes/ingress/IngressStrategy.scala
  streampark-flink/streampark-flink-kubernetes/src/main/scala/org/apache/streampark/flink/kubernetes/ingress/IngressStrategyV1.scala
  streampark-flink/streampark-flink-kubernetes/src/main/scala/org/apache/streampark/flink/kubernetes/ingress/IngressStrategyV1beta1.scala
  streampark-storage/pom.xml
  streampark-storage/src/main/java/org/apache/streampark/storage/StorageService.java
  streampark-storage/src/main/java/org/apache/streampark/storage/StorageServiceConfig.java
  streampark-storage/src/main/java/org/apache/streampark/storage/oss/OssConfig.java
  streampark-storage/src/main/java/org/apache/streampark/storage/oss/OssStorageService.java
  streampark-storage/src/test/java/org/apache/streampark/storage/oss/OssStorageServiceTest.java
Labels: BUILD, WEB UI, DOCKER, DOCS, BACKEND, FLINK, KUBERNETES

#2966 Added flink k8s operator validate
  streampark-flink/streampark-flink-kubernetes-v2/streampark-flink-kubernetes-core/src/main/scala/org/apache/streampark/flink/kubernetes/v2/observer/DeployCRObserver.scala
  streampark-flink/streampark-flink-kubernetes-v2/streampark-flink-kubernetes-core/src/main/scala/org/apache/streampark/flink/kubernetes/v2/operator/CROperator.scala
Labels: FLINK

#3028 [issues-3027][fix]remove redundant tasks submit logic
  streampark-flink/streampark-flink-client/streampark-flink-client-core/src/main/scala/org/apache/streampark/flink/client/trait/FlinkClientTrait.scala
Labels: FLINK

#2994 Refactor the lifecycle control of flink application mode -dosubmit
  streampark-flink/streampark-flink-client/streampark-flink-client-core/pom.xml
  streampark-flink/streampark-flink-client/streampark-flink-client-core/src/main/scala/org/apache/streampark/flink/client/impl/KubernetesNativeApplicationClientV2.scala
Labels: BUILD, FLINK

#3032 [Enhance] Optimize the validation logic of flinkDeploymentCR at PR#2966
  streampark-flink/streampark-flink-kubernetes-v2/streampark-flink-kubernetes-core/src/main/scala/org/apache/streampark/flink/kubernetes/v2/operator/CROperator.scala
  streampark-flink/streampark-flink-kubernetes-v2/streampark-flink-kubernetes-core/src/main/scala/org/apache/streampark/flink/kubernetes/v2/operator/OprError.scala
Labels: FLINK

#3034 [Hotfix] Disabled unstable test cases.
  .github/workflows/maven.yml
  streampark-console/streampark-console-service/src/test/java/org/apache/streampark/console/base/util/DependencyUtilsTest.java
  streampark-console/streampark-console-service/src/test/java/org/apache/streampark/console/core/service/ApplicationManageServiceITest.java
Labels: INFRA, BACKEND

#3023 [Refactor] Refactor alert module.
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/controller/AlertController.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/entity/Application.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/entity/FlinkCluster.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/enums/AlertType.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/alert/AlertNotifyService.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/alert/AlertService.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/alert/impl/AlertConfigServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/alert/impl/AlertServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/alert/impl/DingTalkAlertNotifyServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/alert/impl/EmailAlertNotifyServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/alert/impl/HttpCallbackAlertNotifyServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/alert/impl/LarkAlertNotifyServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/alert/impl/WeComAlertNotifyServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/task/CheckpointProcessor.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/task/FlinkClusterWatcher.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/task/FlinkHttpWatcher.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/task/FlinkK8sChangeEventListener.java
  streampark-console/streampark-console-service/src/test/java/org/apache/streampark/console/core/service/alert/AlertServiceTest.java
Labels: BACKEND

#3025 [Improve] Remove redundant serializable implements for enum
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/enums/AccessTokenState.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/enums/AppExistsState.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/enums/BuildState.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/enums/CandidateType.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/enums/ChangeTypeEnum.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/enums/CheckPointStatus.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/enums/CheckPointType.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/enums/ConfigFileType.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/enums/EffectiveType.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/enums/FlinkAppState.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/enums/GitAuthorizedError.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/enums/NoticeType.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/enums/Operation.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/enums/OptionState.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/enums/PlaceholderType.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/enums/ReleaseState.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/enums/ResourceFrom.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/enums/StopFrom.java
Labels: BACKEND

#3012 [ISSUE-2992][Improve] Using code style & quality rules to improve org.apache.streampark.console.base.config package of streampark-console module.
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/base/config/OpenapiConfig.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/base/config/WebMvcConfig.java
Labels: BACKEND

#3038 [Style] code style update
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/base/config/OpenapiConfig.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/base/config/WebMvcConfig.java
Labels: BACKEND

#3039 [Hotfix] Fix non-existed methods references and exceptions-thrown.
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/runner/EnvInitializer.java
  streampark-flink/streampark-flink-client/streampark-flink-client-core/src/main/scala/org/apache/streampark/flink/client/impl/KubernetesApplicationClientV2.scala
Labels: BACKEND, FLINK

#2989 [Feature] [Flink-K8s-V2] Refactor the state tracking of Flink on Kubernetes
  streampark-console/streampark-console-service/src/main/scala/org/apache/streampark/console/core/task/FlinkK8sChangeListener.scala
  streampark-console/streampark-console-service/src/main/scala/org/apache/streampark/console/core/utils/FlinkAppStateConverter.scala
  streampark-flink/streampark-flink-kubernetes-v2/streampark-flink-kubernetes-core/src/main/scala/org/apache/streampark/flink/kubernetes/v2/model/JobState.scala
  streampark-flink/streampark-flink-kubernetes-v2/streampark-flink-kubernetes-core/src/main/scala/org/apache/streampark/flink/kubernetes/v2/operator/OprError.scala
Labels: BACKEND, FLINK

#3040 [Improve] EnvUtils minor improvement
  streampark-common/src/main/scala/org/apache/streampark/common/util/EnvUtils.java
  streampark-common/src/main/scala/org/apache/streampark/common/util/HadoopConfigUtils.scala
  streampark-common/src/main/scala/org/apache/streampark/common/util/SystemPropertyUtils.scala
  streampark-flink/streampark-flink-client/streampark-flink-client-core/src/main/scala/org/apache/streampark/flink/client/trait/FlinkClientTrait.scala
Labels: BACKEND, FLINK

#3042 [Feature] Flink yarn application support pyflink maven dependency
  streampark-common/src/main/scala/org/apache/streampark/common/util/DeflaterUtils.scala
  streampark-common/src/main/scala/org/apache/streampark/common/util/FileUtils.scala
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/entity/Application.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/application/impl/ApplicationManageServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/AppBuildPipeServiceImpl.java
  streampark-console/streampark-console-webapp/src/views/flink/app/Add.vue
  streampark-console/streampark-console-webapp/src/views/flink/app/hooks/useCreateAndEditSchema.ts
  streampark-flink/streampark-flink-client/streampark-flink-client-core/src/main/scala/org/apache/streampark/flink/client/impl/YarnApplicationClient.scala
  streampark-flink/streampark-flink-packer/src/main/scala/org/apache/streampark/flink/packer/pipeline/impl/FlinkYarnApplicationBuildPipeline.scala
Labels: WEB UI, BACKEND, FLINK

#3041 [Feature] [Flink-K8s-V2] Refactor the lifecycle control of Flink session-mode jobs on Kubernetes
  streampark-flink/streampark-flink-client/streampark-flink-client-core/src/main/scala/org/apache/streampark/flink/client/FlinkClientHandler.scala
  streampark-flink/streampark-flink-client/streampark-flink-client-core/src/main/scala/org/apache/streampark/flink/client/impl/KubernetesSessionClientV2.scala
Labels: FLINK

#3004 [Improvement] add support for SinkRequest that has multiple statements
  streampark-flink/streampark-flink-connector/streampark-flink-connector-base/src/main/scala/org/apache/streampark/flink/connector/failover/SinkRequest.scala
  streampark-flink/streampark-flink-connector/streampark-flink-connector-base/src/test/scala/org/apache/streampark/flink/connector/failover/SinkRequestTest.scala
  streampark-flink/streampark-flink-connector/streampark-flink-connector-clickhouse/src/main/scala/org/apache/streampark/flink/connector/clickhouse/internal/ClickHouseWriterTask.scala
Labels: FLINK

#3031 [Bug] fix FlinkKubernetesClient.getService() bug
  streampark-flink/streampark-flink-shims/streampark-flink-shims_flink-1.16/src/main/scala/org/apache/streampark/flink/core/FlinkKubernetesClient.scala
  streampark-flink/streampark-flink-shims/streampark-flink-shims_flink-1.17/src/main/scala/org/apache/streampark/flink/core/FlinkKubernetesClient.scala
Labels: FLINK

#3052 [Bug] workspace path init bug fixed
  pom.xml
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/runner/EnvInitializer.java
  streampark-console/streampark-console-webapp/src/views/flink/project/components/LogModal.vue
  streampark-flink/streampark-flink-client/streampark-flink-client-api/src/main/scala/org/apache/streampark/flink/client/FlinkClient.scala
  streampark-flink/streampark-flink-client/streampark-flink-client-core/src/main/scala/org/apache/streampark/flink/client/FlinkClientEndpoint.scala
  streampark-flink/streampark-flink-kubernetes-v2/streampark-flink-kubernetes-core/src/main/scala/org/apache/streampark/flink/kubernetes/v2/FlinkK8sConfig.scala
  streampark-tests/pom.xml
  streampark-tests/streampark-testcontainer/pom.xml
  streampark-tests/streampark-testcontainer/src/main/java/org/apache/streampark/testcontainer/flink/FlinkComponent.java
  streampark-tests/streampark-testcontainer/src/main/java/org/apache/streampark/testcontainer/flink/FlinkContainer.java
  streampark-tests/streampark-testcontainer/src/main/java/org/apache/streampark/testcontainer/flink/FlinkStandaloneSessionCluster.java
  streampark-tests/streampark-testcontainer/src/main/java/org/apache/streampark/testcontainer/hadoop/HadoopContainer.java
  streampark-tests/streampark-testcontainer/src/test/java/org/apache/streampark/testcontainer/flink/FlinkStandaloneSessionClusterITest.java
  streampark-tests/streampark-testcontainer/src/test/java/org/apache/streampark/testcontainer/hadoop/HadoopContainerTest.java
Labels: BUILD, WEB UI, BACKEND, FLINK

#3053 [Feat][flink-k8s-v2] Update helm configs for embedded file server
  deploy/docker/Dockerfile
  deploy/docker/docker-compose.yaml
  deploy/helm/streampark/conf/streampark-console-config/application.yml
  deploy/helm/streampark/templates/service.yaml
  deploy/helm/streampark/templates/streampark.yml
  deploy/helm/streampark/values.yaml
Labels: DOCKER

#3054 [Feat][Flink-k8s-v2] Migrate the creation of Flink ingress to Flink K8s operator
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/application/impl/ApplicationActionServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/utils/FlinkK8sDataTypeConverterStub.java
  streampark-console/streampark-console-service/src/main/scala/org/apache/streampark/console/core/utils/FlinkK8sDataTypeConverter.scala
  streampark-flink/streampark-flink-client/streampark-flink-client-api/src/main/scala/org/apache/streampark/flink/client/bean/KubernetesSubmitParam.scala
  streampark-flink/streampark-flink-client/streampark-flink-client-core/src/main/scala/org/apache/streampark/flink/client/impl/KubernetesApplicationClientV2.scala
  streampark-flink/streampark-flink-client/streampark-flink-client-core/src/main/scala/org/apache/streampark/flink/client/impl/KubernetesNativeApplicationClient.scala
  streampark-flink/streampark-flink-client/streampark-flink-client-core/src/main/scala/org/apache/streampark/flink/client/impl/KubernetesNativeSessionClient.scala
Labels: BACKEND, FLINK

#3080 [fix] buji-pac4j dependency issue when use SSO feature
  streampark-console/streampark-console-service/pom.xml
Labels: BUILD, BACKEND

#3122 [Improve] RestResponse fail method improvement
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/base/domain/RestResponse.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/base/handler/GlobalExceptionHandler.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ProjectServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/controller/UserController.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/service/impl/AccessTokenServiceImpl.java
Labels: BACKEND

#3082 [Improvement] FE enums improvements
  streampark-console/streampark-console-webapp/src/assets/icons/app.svg
  streampark-console/streampark-console-webapp/src/assets/icons/fql.svg
  streampark-console/streampark-console-webapp/src/assets/icons/py.svg
  streampark-console/streampark-console-webapp/src/enums/flinkEnum.ts
  streampark-console/streampark-console-webapp/src/layouts/default/header/components/notify/index.vue
  streampark-console/streampark-console-webapp/src/views/flink/app/Add.vue
  streampark-console/streampark-console-webapp/src/views/flink/app/EditFlink.vue
  streampark-console/streampark-console-webapp/src/views/flink/app/EditStreamPark.vue
  streampark-console/streampark-console-webapp/src/views/flink/app/View.vue
  streampark-console/streampark-console-webapp/src/views/flink/app/components/AppView/StopApplicationModal.vue
  streampark-console/streampark-console-webapp/src/views/flink/app/hooks/useAppTableAction.ts
  streampark-console/streampark-console-webapp/src/views/flink/app/hooks/useCreateAndEditSchema.ts
  streampark-console/streampark-console-webapp/src/views/flink/app/hooks/useCreateSchema.ts
  streampark-console/streampark-console-webapp/src/views/flink/app/hooks/useEditFlinkSchema.ts
  streampark-console/streampark-console-webapp/src/views/flink/app/hooks/useFlinkRender.tsx
  streampark-console/streampark-console-webapp/src/views/flink/app/hooks/useSavepoint.tsx
  streampark-console/streampark-console-webapp/src/views/setting/FlinkCluster/index.vue
Labels: WEB UI

#3123 fix: app create err & fix type error
  streampark-console/streampark-console-webapp/package.json
  streampark-console/streampark-console-webapp/src/api/flink/setting/types/flinkEnv.type.ts
  streampark-console/streampark-console-webapp/src/api/system/user.ts
  streampark-console/streampark-console-webapp/src/components/Form/src/components/FormItem.vue
  streampark-console/streampark-console-webapp/src/components/Form/src/helper.ts
  streampark-console/streampark-console-webapp/src/components/Icon/src/IconPicker.vue
  streampark-console/streampark-console-webapp/src/components/Modal/src/components/ModalWrapper.vue
  streampark-console/streampark-console-webapp/src/components/Page/src/PageWrapper.vue
  streampark-console/streampark-console-webapp/src/components/Scrollbar/src/Scrollbar.vue
  streampark-console/streampark-console-webapp/src/components/SimpleMenu/src/SimpleMenu.vue
  streampark-console/streampark-console-webapp/src/components/Table/src/BasicTable.vue
  streampark-console/streampark-console-webapp/src/components/Table/src/components/TableAction.vue
  streampark-console/streampark-console-webapp/src/components/Table/src/components/editable/EditableCell.vue
  streampark-console/streampark-console-webapp/src/components/Table/src/hooks/useDataSource.ts
  streampark-console/streampark-console-webapp/src/layouts/default/header/components/notify/NoticeList.vue
  streampark-console/streampark-console-webapp/src/locales/useLocale.ts
  streampark-console/streampark-console-webapp/src/store/modules/lock.ts
  streampark-console/streampark-console-webapp/src/utils/bem.ts
  streampark-console/streampark-console-webapp/src/utils/http/axios/Axios.ts
  streampark-console/streampark-console-webapp/src/utils/props.ts
  streampark-console/streampark-console-webapp/src/views/base/login/LoginSlogan.tsx
  streampark-console/streampark-console-webapp/src/views/flink/app/Add.vue
  streampark-console/streampark-console-webapp/src/views/flink/app/View.vue
  streampark-console/streampark-console-webapp/src/views/flink/app/hooks/useCreateAndEditSchema.ts
  streampark-console/streampark-console-webapp/src/views/flink/app/hooks/useSavepoint.tsx
  streampark-console/streampark-console-webapp/src/views/flink/resource/components/ResourceDrawer.vue
  streampark-console/streampark-console-webapp/src/views/setting/FlinkCluster/index.vue
  streampark-console/streampark-console-webapp/types/store.d.ts
Labels: WEB UI

#3125 [Improve] project clone openssh higher version improvement
  dist-material/release-docs/LICENSE
  streampark-common/src/main/scala/org/apache/streampark/common/util/SystemPropertyUtils.scala
  streampark-console/streampark-console-service/pom.xml
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/base/util/GitUtils.java
  streampark-console/streampark-console-service/src/main/resources/db/data-h2.sql
Labels: BUILD, BACKEND

#3121 [Improve] Improve streampark-console module base on [3.2 Constant Variables Definition]
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/base/util/CommonUtils.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/base/util/FreemarkerUtils.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/base/util/WebUtils.java
Labels: BACKEND

#3126 [Improve][All] Improvement of StringUtils.isEmpty method
  streampark-common/src/main/java/org/apache/streampark/common/enums/StorageType.java
  streampark-common/src/main/scala/org/apache/streampark/common/util/PropertiesUtils.scala
  streampark-common/src/test/scala/org/apache/streampark/common/util/PropertiesUtilsTestCase.scala
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/base/util/GitUtils.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/bean/MavenConfig.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/bean/MavenPom.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/controller/FlinkPodTemplateController.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/entity/FlinkCluster.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/entity/FlinkEnv.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/entity/Project.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/application/impl/ApplicationInfoServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/FlinkClusterServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/SavePointServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/VariableServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/YarnQueueServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/task/FlinkClusterWatcher.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/task/FlinkHttpWatcher.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/utils/YarnQueueLabelExpression.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/controller/PassportController.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/service/impl/AccessTokenServiceImpl.java
  streampark-flink/streampark-flink-client/streampark-flink-client-core/src/main/scala/org/apache/streampark/flink/client/trait/FlinkClientTrait.scala
  streampark-flink/streampark-flink-connector/streampark-flink-connector-doris/src/main/java/org/apache/streampark/flink/connector/doris/internal/DorisSinkFunction.java
Labels: BACKEND, FLINK

#3127 [Improve] project page improvement
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/application/impl/ApplicationActionServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/task/ProjectBuildTask.java
  streampark-console/streampark-console-webapp/src/assets/icons/http.svg
  streampark-console/streampark-console-webapp/src/assets/icons/net.svg
  streampark-console/streampark-console-webapp/src/assets/icons/ssh.svg
  streampark-console/streampark-console-webapp/src/locales/lang/en/flink/project.ts
  streampark-console/streampark-console-webapp/src/locales/lang/zh-CN/flink/project.ts
  streampark-console/streampark-console-webapp/src/views/flink/app/components/AppView/StopApplicationModal.vue
  streampark-console/streampark-console-webapp/src/views/flink/project/components/RepositoryGroup.tsx
Labels: WEB UI, BACKEND

#3036 [Feature] StreamPark Autonomous Health Probing
  streampark-console/streampark-console-service/src/main/assembly/script/schema/mysql-schema.sql
  streampark-console/streampark-console-service/src/main/assembly/script/schema/pgsql-schema.sql
  streampark-console/streampark-console-service/src/main/assembly/script/upgrade/mysql/2.2.0.sql
  streampark-console/streampark-console-service/src/main/assembly/script/upgrade/pgsql/2.2.0.sql
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/bean/AlertProbeMsg.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/bean/AlertTemplate.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/entity/Application.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/enums/FlinkAppState.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/mapper/ApplicationMapper.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/application/ApplicationManageService.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/application/impl/ApplicationManageServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/task/AutoHealthProbingTask.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/task/FlinkHttpWatcher.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/task/FlinkK8sChangeEventListener.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/task/FlinkK8sWatcherWrapper.java
  streampark-console/streampark-console-service/src/main/resources/alert-template/alert-dingTalk.ftl
  streampark-console/streampark-console-service/src/main/resources/alert-template/alert-email.ftl
  streampark-console/streampark-console-service/src/main/resources/alert-template/alert-lark.ftl
  streampark-console/streampark-console-service/src/main/resources/alert-template/alert-weCom.ftl
  streampark-console/streampark-console-service/src/main/resources/db/schema-h2.sql
  streampark-console/streampark-console-service/src/main/resources/mapper/core/ApplicationMapper.xml
  streampark-console/streampark-console-webapp/src/enums/flinkEnum.ts
  streampark-console/streampark-console-webapp/src/views/flink/app/components/State.less
  streampark-console/streampark-console-webapp/src/views/flink/app/components/State.tsx
Labels: BUILD, WEB UI, BACKEND

#3128 [Improve] application state improvement
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/annotation/AppUpdated.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/aspect/StreamParkAspect.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/bean/AlertProbeMsg.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/entity/Application.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/application/impl/ApplicationActionServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/application/impl/ApplicationInfoServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/application/impl/ApplicationManageServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/AppBuildPipeServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ProjectServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/SavePointServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/task/FlinkAppHttpWatcher.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/task/FlinkAppLostWatcher.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/task/FlinkCheckpointProcessor.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/task/FlinkK8sChangeEventListener.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/task/FlinkK8sWatcherWrapper.java
  streampark-console/streampark-console-service/src/main/resources/mapper/core/ApplicationMapper.xml
  streampark-console/streampark-console-service/src/test/java/org/apache/streampark/console/core/service/ApplicationManageServiceITest.java
Labels: BACKEND

#3124 [Feature] Flink remote support pyflink maven dependency
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/AppBuildPipeServiceImpl.java
  streampark-flink/streampark-flink-client/streampark-flink-client-core/src/main/scala/org/apache/streampark/flink/client/trait/FlinkClientTrait.scala
  streampark-flink/streampark-flink-packer/src/main/scala/org/apache/streampark/flink/packer/pipeline/impl/FlinkRemoteBuildPipeline.scala
Labels: BACKEND, FLINK

#3134 [Improve] Modify savepoint parameter name
  streampark-flink/streampark-flink-shims/streampark-flink-shims-base/src/main/scala/org/apache/streampark/flink/core/FlinkClientTrait.scala
Labels: FLINK

#3137 [Cleanup] Remove the redundant Serializable implementation for all En…
  streampark-common/src/main/java/org/apache/streampark/common/enums/ApplicationType.java
  streampark-common/src/main/java/org/apache/streampark/common/enums/ClusterState.java
  streampark-common/src/main/java/org/apache/streampark/common/enums/DevelopmentMode.java
  streampark-common/src/main/java/org/apache/streampark/common/enums/ExecutionMode.java
  streampark-common/src/main/java/org/apache/streampark/common/enums/FlinkK8sRestExposedType.java
  streampark-common/src/main/java/org/apache/streampark/common/enums/FlinkSqlValidationFailedType.java
  streampark-common/src/main/java/org/apache/streampark/common/enums/ResolveOrder.java
  streampark-common/src/main/java/org/apache/streampark/common/enums/RestoreMode.java
  streampark-common/src/main/java/org/apache/streampark/common/enums/Semantic.java
  streampark-common/src/main/java/org/apache/streampark/common/enums/StorageType.java
Labels: BACKEND

#3135 [Improve] Unified enumeration comparison methods
  streampark-common/src/main/java/org/apache/streampark/common/enums/ExecutionMode.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/entity/Application.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/entity/FlinkCluster.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/enums/FlinkAppState.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/enums/GitCredential.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/runner/EnvInitializer.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/application/impl/ApplicationActionServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/application/impl/ApplicationInfoServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/application/impl/ApplicationManageServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/AppBuildPipeServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ApplicationConfigServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ProjectServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ResourceServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/SavePointServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/task/FlinkAppHttpWatcher.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/task/FlinkCheckpointProcessor.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/task/FlinkK8sChangeEventListener.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/task/FlinkK8sWatcherWrapper.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/service/impl/MenuServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/service/impl/TeamServiceImpl.java
  streampark-flink/streampark-flink-client/streampark-flink-client-core/src/main/scala/org/apache/streampark/flink/client/impl/YarnSessionClient.scala
  streampark-flink/streampark-flink-client/streampark-flink-client-core/src/main/scala/org/apache/streampark/flink/client/trait/FlinkClientTrait.scala
Labels: BACKEND, FLINK

#3139 [Cleanup] Remove the package org.apache.streampark.common.tuple of streampark-common module. #3132
  streampark-common/src/main/java/org/apache/streampark/common/tuple/Tuple.java
  streampark-common/src/main/java/org/apache/streampark/common/tuple/Tuple1.java
  streampark-common/src/main/java/org/apache/streampark/common/tuple/Tuple2.java
  streampark-common/src/main/java/org/apache/streampark/common/tuple/Tuple3.java
  streampark-common/src/main/java/org/apache/streampark/common/tuple/Tuple4.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/application/impl/ApplicationActionServiceImpl.java
Labels: BACKEND

#3141 [Improve] Shims base module code optimization
  streampark-flink/streampark-flink-shims/streampark-flink-shims-base/src/main/scala/org/apache/streampark/flink/core/FlinkSqlExecutor.scala
  streampark-flink/streampark-flink-shims/streampark-flink-shims-base/src/main/scala/org/apache/streampark/flink/core/FlinkSqlValidator.scala
  streampark-flink/streampark-flink-shims/streampark-flink-shims-base/src/main/scala/org/apache/streampark/flink/core/SqlCommandParser.scala
  streampark-flink/streampark-flink-sqlclient/src/main/scala/org/apache/streampark/flink/cli/SqlClient.scala
Labels: FLINK

#3144 [Bug] The incorrect for loop writing method resulted in the same valu…
  streampark-flink/streampark-flink-client/streampark-flink-client-core/src/main/scala/org/apache/streampark/flink/client/trait/KubernetesNativeClientTrait.scala
Labels: FLINK

#3148 add how to Contribute
  README.md
Labels: DOCS

#3151 [Improve] Improve assembly.xml baseDirectory name
  streampark-console/streampark-console-service/src/main/assembly/assembly.xml
Labels: BUILD, BACKEND

#3150 [Improve] FlinkAppHttpWatcher improvement
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/enums/StopFrom.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/task/FlinkAppHttpWatcher.java
Labels: BACKEND

#3152 [Improve] Add additional use cases for FlinkOperator on Kubernetes
  streampark-flink/streampark-flink-kubernetes-v2/streampark-flink-kubernetes-core/src/test/scala/org/apache/streampark/flink/kubernetes/v2/example/UsingOperator.scala
Labels: FLINK

#3156 [Improve] improve README.md
  README.md
Labels: DOCS

#3160 [Feature] Add application backup clean task
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/ApplicationBackUpService.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ApplicationBackUpServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/task/ApplicationBackUpCleanTask.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/task/FlinkAppLostWatcher.java
  streampark-console/streampark-console-service/src/main/resources/application.yml
  streampark-flink/streampark-flink-sql-gateway/streampark-flink-sql-gateway-base/src/main/java/org/apache/streampark/gateway/session/SessionHandle.java
Labels: BACKEND, FLINK

#3130 [Improve] Improve streampark-common module base on 3.1 Naming Style
  streampark-common/src/main/java/org/apache/streampark/common/enums/ApplicationType.java
  streampark-common/src/main/java/org/apache/streampark/common/enums/ClusterState.java
  streampark-common/src/main/java/org/apache/streampark/common/enums/DevelopmentMode.java
  streampark-common/src/main/java/org/apache/streampark/common/enums/ExecutionMode.java
  streampark-common/src/main/java/org/apache/streampark/common/enums/FlinkK8sRestExposedType.java
  streampark-common/src/main/java/org/apache/streampark/common/enums/FlinkSqlValidationFailedType.java
  streampark-common/src/main/java/org/apache/streampark/common/enums/ResolveOrder.java
  streampark-common/src/main/java/org/apache/streampark/common/enums/RestoreMode.java
  streampark-common/src/main/java/org/apache/streampark/common/enums/Semantic.java
  streampark-common/src/main/java/org/apache/streampark/common/enums/StorageType.java
  streampark-common/src/main/scala/org/apache/streampark/common/conf/ConfigConst.scala
  streampark-common/src/main/scala/org/apache/streampark/common/conf/FlinkVersion.scala
  streampark-common/src/main/scala/org/apache/streampark/common/conf/K8sFlinkConfig.scala
  streampark-common/src/main/scala/org/apache/streampark/common/util/HdfsUtils.scala
  streampark-common/src/main/scala/org/apache/streampark/common/util/SqlConvertUtils.scala
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/controller/FlinkSqlController.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/entity/Application.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/FlinkClusterServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/task/FlinkClusterWatcher.java
  streampark-console/streampark-console-service/src/main/scala/org/apache/streampark/console/core/task/FlinkK8sObserverBroker.scala
  streampark-console/streampark-console-service/src/test/java/org/apache/streampark/console/core/service/SavePointServiceTest.java
  streampark-flink/streampark-flink-client/streampark-flink-client-api/src/main/scala/org/apache/streampark/flink/client/bean/SubmitRequest.scala
Labels: BACKEND, FLINK

#3154 [Fix] Interceptors add /resource/upload
  streampark-common/pom.xml
  streampark-common/src/main/scala/org/apache/streampark/common/util/FileUtils.scala
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/base/config/WebMvcConfig.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/base/interceptor/UploadFileTypeInterceptor.java
Labels: BUILD, BACKEND

#3168 [Improve] alerm minor improvement
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/alert/impl/EmailAlertNotifyServiceImpl.java
Labels: BACKEND

#3174 [Improve] Improve streampark-common module base on [3.9 Java Streams]
  streampark-common/src/main/java/org/apache/streampark/common/enums/RestoreMode.java
Labels: BACKEND

#3173 [Improve] optimize enum RestoreMode getName function
  streampark-common/src/main/java/org/apache/streampark/common/enums/RestoreMode.java
Labels: BACKEND

#3171 [Improve] Streampark-common module tika dependency moved to the streampark-console module
  dist-material/release-docs/LICENSE
  streampark-common/pom.xml
  streampark-common/src/main/scala/org/apache/streampark/common/util/FileUtils.scala
  streampark-console/streampark-console-service/pom.xml
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/base/interceptor/UploadFileTypeInterceptor.java
Labels: BUILD, BACKEND

#3176 [Fix] Modify the isPythonFileType parameter
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/base/interceptor/UploadFileTypeInterceptor.java
Labels: BACKEND

#3177 [Improve] Improve streampark-flink-client-core module base on [Naming Style]
  streampark-flink/streampark-flink-client/streampark-flink-client-core/src/main/scala/org/apache/streampark/flink/client/impl/KubernetesNativeApplicationClient.scala
  streampark-flink/streampark-flink-client/streampark-flink-client-core/src/main/scala/org/apache/streampark/flink/client/impl/KubernetesNativeSessionClient.scala
  streampark-flink/streampark-flink-client/streampark-flink-client-core/src/main/scala/org/apache/streampark/flink/client/trait/KubernetesClientV2Trait.scala
Labels: FLINK

#3183 [Improve] GitUtils code optimization
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/base/util/GitUtils.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/entity/Project.java
Labels: BACKEND

#3187 [Improve] Authentication code optimization
  streampark-console/streampark-console-service/src/main/assembly/script/schema/pgsql-schema.sql
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/authentication/JWTFilter.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/authentication/JWTUtil.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/authentication/ShiroConfig.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/entity/SysLog.java
Labels: BUILD, BACKEND

#3170 [Improve] package name improvement
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/annotation/AppUpdated.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/aspect/ConsoleAspect.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/component/FlinkCheckpointProcessor.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/application/impl/ApplicationActionServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/application/impl/ApplicationInfoServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/application/impl/ApplicationManageServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/AppBuildPipeServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/FlinkClusterServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ProjectServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/SavePointServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/task/ProjectBuildTask.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/watcher/FlinkAppHttpWatcher.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/watcher/FlinkAppLostWatcher.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/watcher/FlinkClusterWatcher.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/watcher/FlinkK8sChangeEventListener.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/watcher/FlinkK8sObserverStub.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/watcher/FlinkK8sWatcherWrapper.java
  streampark-console/streampark-console-service/src/main/scala/org/apache/streampark/console/core/task/FlinkK8sObserverBroker.scala
  streampark-console/streampark-console-service/src/test/java/org/apache/streampark/console/core/service/ApplicationManageServiceITest.java
Labels: BACKEND

#3190 [Polish] Remove redundant @Transactional annotations
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/application/impl/ApplicationActionServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/application/impl/ApplicationManageServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ApplicationBackUpServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ApplicationConfigServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/FlinkClusterServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/FlinkSqlServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ProjectServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ResourceServiceImpl.java
Labels: BACKEND

#3195 [Improve] Add Local Development and Debugging to Readmd document
  README.md
Labels: DOCS

#3191 [Feature] [Flink-K8s-V2] Add id to ShutDownRequest
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/FlinkClusterServiceImpl.java
  streampark-flink/streampark-flink-client/streampark-flink-client-api/src/main/scala/org/apache/streampark/flink/client/bean/ShutDownRequest.scala
Labels: BACKEND, FLINK

#3201 [Refactor] Refactor ObjectUtils and CommonUtils
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/base/util/CommonUtils.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/base/util/ObjectUtils.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/entity/Project.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/application/impl/ApplicationManageServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/SavePointServiceImpl.java
Labels: BACKEND

#3198 [Refactor] Refactor exception handling with ApiAlertException
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/application/impl/ApplicationActionServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/application/impl/ApplicationInfoServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/AppBuildPipeServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ApplicationConfigServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/CommonServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/FlinkGateWayServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ProjectServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/SavePointServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/VariableServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/controller/SsoController.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/security/impl/AuthenticatorImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/security/impl/LdapService.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/service/impl/MenuServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/service/impl/TeamServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/service/impl/UserServiceImpl.java
Labels: BACKEND

#3202 [Improve] Console core module code optimization
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/bean/AlertTemplate.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/entity/Application.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/entity/ApplicationConfig.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/entity/FlinkEnv.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/entity/Project.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/entity/Resource.java
Labels: BACKEND

#3197 [Improve] System module code optimization
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/controller/PassportController.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/security/impl/AuthenticatorImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/service/impl/RoleServiceImpl.java
Labels: BACKEND

#3199 [Improve] [Flink-Kubernetes-V2] Change doTriggerSavepoint log
  streampark-flink/streampark-flink-client/streampark-flink-client-core/src/main/scala/org/apache/streampark/flink/client/trait/KubernetesClientV2Trait.scala
Labels: FLINK

#3206 [Improve] Storage Initialize create python directory
  streampark-common/src/main/scala/org/apache/streampark/common/conf/Workspace.scala
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/runner/EnvInitializer.java
Labels: BACKEND
