Repository apache/streampark, pull requests merged in 2023-02, with the labels that each got.

#2277 [Improve] license improvement
  LICENSE
  dist-material/release-docs/LICENSE
  dist-material/release-docs/licenses/ui-licenses/license-ant-design-vue.txt
  dist-material/release-docs/licenses/ui-licenses/license-axios.txt
  dist-material/release-docs/licenses/ui-licenses/license-crypto-js.txt
  dist-material/release-docs/licenses/ui-licenses/license-dayjs.txt
  dist-material/release-docs/licenses/ui-licenses/license-dotenv.txt
  dist-material/release-docs/licenses/ui-licenses/license-eslint-config-prettier.txt
  dist-material/release-docs/licenses/ui-licenses/license-eslint-plugin-prettier.txt
  dist-material/release-docs/licenses/ui-licenses/license-eslint-plugin-vue.txt
  dist-material/release-docs/licenses/ui-licenses/license-eslint.txt
  dist-material/release-docs/licenses/ui-licenses/license-esno.txt
  dist-material/release-docs/licenses/ui-licenses/license-fs-extra.txt
  dist-material/release-docs/licenses/ui-licenses/license-iconify.txt
  dist-material/release-docs/licenses/ui-licenses/license-lint-staged.txt
  dist-material/release-docs/licenses/ui-licenses/license-lodash-es.txt
  dist-material/release-docs/licenses/ui-licenses/license-monaco-editor.txt
  dist-material/release-docs/licenses/ui-licenses/license-nprogress.txt
  dist-material/release-docs/licenses/ui-licenses/license-path-to-regexp.txt
  dist-material/release-docs/licenses/ui-licenses/license-penpal.txt
  dist-material/release-docs/licenses/ui-licenses/license-picocolors.txt
  dist-material/release-docs/licenses/ui-licenses/license-postcss-html.txt
  dist-material/release-docs/licenses/ui-licenses/license-postcss-less.txt
  dist-material/release-docs/licenses/ui-licenses/license-postcss.txt
  dist-material/release-docs/licenses/ui-licenses/license-qs.txt
  dist-material/release-docs/licenses/ui-licenses/license-resize-observer-polyfill.txt
  dist-material/release-docs/licenses/ui-licenses/license-rollup.txt
  dist-material/release-docs/licenses/ui-licenses/license-sortablejs.txt
  dist-material/release-docs/licenses/ui-licenses/license-sql-formatter.txt
  dist-material/release-docs/licenses/ui-licenses/license-stylelint-order.txt
  dist-material/release-docs/licenses/ui-licenses/license-stylelint.txt
  dist-material/release-docs/licenses/ui-licenses/license-sweetalert2.txt
  dist-material/release-docs/licenses/ui-licenses/license-terser.txt
  dist-material/release-docs/licenses/ui-licenses/license-vite-plugin-svg-icons.txt
  dist-material/release-docs/licenses/ui-licenses/license-vite.txt
  dist-material/release-docs/licenses/ui-licenses/license-vue-eslint-parser.txt
  dist-material/release-docs/licenses/ui-licenses/license-vue-i18n.txt
  dist-material/release-docs/licenses/ui-licenses/license-vue-pinia.txt
  dist-material/release-docs/licenses/ui-licenses/license-vue-router.txt
  dist-material/release-docs/licenses/ui-licenses/license-vue-tsc.txt
  dist-material/release-docs/licenses/ui-licenses/license-vue-types.txt
  dist-material/release-docs/licenses/ui-licenses/license-vue-use.txt
  dist-material/release-docs/licenses/ui-licenses/license-vue.txt
  streampark-common/src/main/scala/org/apache/streampark/common/util/DateUtils.scala
  streampark-common/src/main/scala/org/apache/streampark/common/util/DependencyUtils.scala
  streampark-common/src/main/scala/org/apache/streampark/common/util/PropertiesUtils.scala
  streampark-console/streampark-console-service/src/main/assembly/bin/setclasspath.sh
  streampark-console/streampark-console-service/src/main/assembly/bin/streampark.sh
  streampark-console/streampark-console-service/src/test/java/org/apache/streampark/console/core/entity/DependencyTest.java
Labels: BUILD, BACKEND

#2280 [Bug] delete the default app bug fixed
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/base/domain/Constant.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ApplicationServiceImpl.java
Labels: BACKEND

#2282 [Bug] upload jar check filetype bug fixed.
  streampark-common/src/main/scala/org/apache/streampark/common/util/FileUtils.scala
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/base/interceptor/UploadFileTypeInterceptor.java
Labels: BACKEND

#2283 [Bug] start script bug fixed
  streampark-console/streampark-console-service/src/main/assembly/bin/streampark.sh
Labels: BUILD, BACKEND

#2287 [Bug] flink job on yarn get status bug fixed
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ApplicationServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/task/FlinkRESTAPIWatcher.java
Labels: BACKEND

#2289 [Bug] fix token authorization failed from swagger-ui
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/base/config/SwaggerConfig.java
Labels: BACKEND

#2297 [Improve] delete job improvement
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/base/domain/Constant.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ApplicationServiceImpl.java
Labels: BACKEND

#2300 Update version to 2.1.0
  build.sh
  pom.xml
  streampark-common/pom.xml
  streampark-common/src/main/scala/org/apache/streampark/common/conf/ConfigConst.scala
  streampark-console/pom.xml
  streampark-console/streampark-console-service/pom.xml
  streampark-console/streampark-console-service/src/main/assembly/bin/streampark.sh
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/base/config/SwaggerConfig.java
  streampark-flink/pom.xml
  streampark-flink/streampark-flink-connector/pom.xml
  streampark-flink/streampark-flink-connector/streampark-flink-connector-base/pom.xml
  streampark-flink/streampark-flink-connector/streampark-flink-connector-clickhouse/pom.xml
  streampark-flink/streampark-flink-connector/streampark-flink-connector-doris/pom.xml
  streampark-flink/streampark-flink-connector/streampark-flink-connector-elasticsearch/pom.xml
  streampark-flink/streampark-flink-connector/streampark-flink-connector-elasticsearch/streampark-flink-connector-elasticsearch5/pom.xml
  streampark-flink/streampark-flink-connector/streampark-flink-connector-elasticsearch/streampark-flink-connector-elasticsearch6/pom.xml
  streampark-flink/streampark-flink-connector/streampark-flink-connector-elasticsearch/streampark-flink-connector-elasticsearch7/pom.xml
  streampark-flink/streampark-flink-connector/streampark-flink-connector-hbase/pom.xml
  streampark-flink/streampark-flink-connector/streampark-flink-connector-http/pom.xml
  streampark-flink/streampark-flink-connector/streampark-flink-connector-influx/pom.xml
  streampark-flink/streampark-flink-connector/streampark-flink-connector-jdbc/pom.xml
  streampark-flink/streampark-flink-connector/streampark-flink-connector-kafka/pom.xml
  streampark-flink/streampark-flink-connector/streampark-flink-connector-mongo/pom.xml
  streampark-flink/streampark-flink-connector/streampark-flink-connector-redis/pom.xml
  streampark-flink/streampark-flink-core/pom.xml
  streampark-flink/streampark-flink-kubernetes/pom.xml
  streampark-flink/streampark-flink-packer/pom.xml
  streampark-flink/streampark-flink-proxy/pom.xml
  streampark-flink/streampark-flink-shims/pom.xml
  streampark-flink/streampark-flink-shims/streampark-flink-shims-base/pom.xml
  streampark-flink/streampark-flink-shims/streampark-flink-shims-test/pom.xml
  streampark-flink/streampark-flink-shims/streampark-flink-shims_flink-1.12/pom.xml
  streampark-flink/streampark-flink-shims/streampark-flink-shims_flink-1.13/pom.xml
  streampark-flink/streampark-flink-shims/streampark-flink-shims_flink-1.14/pom.xml
  streampark-flink/streampark-flink-shims/streampark-flink-shims_flink-1.15/pom.xml
  streampark-flink/streampark-flink-shims/streampark-flink-shims_flink-1.16/pom.xml
  streampark-flink/streampark-flink-sqlclient/pom.xml
  streampark-flink/streampark-flink-submit/pom.xml
  streampark-flink/streampark-flink-submit/streampark-flink-submit-api/pom.xml
  streampark-flink/streampark-flink-submit/streampark-flink-submit-core/pom.xml
  streampark-flink/streampark-flink-udf/pom.xml
  streampark-spark/pom.xml
  streampark-spark/streampark-spark-cli/pom.xml
  streampark-spark/streampark-spark-connector/pom.xml
  streampark-spark/streampark-spark-connector/streampark-spark-connector-base/pom.xml
  streampark-spark/streampark-spark-connector/streampark-spark-connector-kafka/pom.xml
  streampark-spark/streampark-spark-core/pom.xml
  streampark-storage/pom.xml
Labels: BUILD, BACKEND, FLINK, KUBERNETES, SPARK

#2307 When creating an application, you can see the projects of other teams
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/controller/ProjectController.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/mapper/ProjectMapper.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/ProjectService.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ProjectServiceImpl.java
  streampark-console/streampark-console-service/src/main/resources/mapper/core/ProjectMapper.xml
Labels: BACKEND

#2310 Update README.md
  README.md
Labels: DOCS

#2312 When starting the application, the option ignore restored does not take effect
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ApplicationServiceImpl.java
Labels: BACKEND

#2321 [Bug] upload jar file type check bug fixed
  streampark-common/src/main/scala/org/apache/streampark/common/util/FileUtils.scala
Labels: BACKEND

#2320 [Bug] application status reset bug fixed.
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/annotation/AppUpdated.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/aspect/StreamParkAspect.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/controller/ApplicationController.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/controller/ProjectController.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/AppBuildPipeServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ProjectServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/task/FlinkRESTAPIWatcher.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/task/ProjectBuildTask.java
  streampark-console/streampark-console-service/src/main/resources/mapper/core/ApplicationMapper.xml
Labels: BACKEND

#2327 Remove AssertUtils to fix license issues
  LICENSE
  dist-material/release-docs/LICENSE
  streampark-common/src/main/scala/org/apache/streampark/common/util/AssertUtils.scala
  streampark-common/src/main/scala/org/apache/streampark/common/util/ExceptionUtils.scala
  streampark-common/src/main/scala/org/apache/streampark/common/util/Utils.scala
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/base/exception/AlertException.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/base/exception/ApiDetailException.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/base/interceptor/UploadFileTypeInterceptor.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/base/util/CommonUtils.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/controller/ProjectController.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/runner/EnvInitializer.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/alert/impl/AlertServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/AppBuildPipeServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ApplicationBackUpServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ApplicationServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/FlinkSqlServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ProjectServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/SavePointServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/SqlCompleteServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/task/FlinkRESTAPIWatcher.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/controller/UserController.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/service/impl/MemberServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/service/impl/RoleServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/service/impl/TeamServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/service/impl/UserServiceImpl.java
  streampark-flink/streampark-flink-client/streampark-flink-client-core/src/main/scala/org/apache/streampark/flink/client/trait/YarnSubmitTrait.scala
  streampark-flink/streampark-flink-connector/streampark-flink-connector-hbase/src/main/scala/org/apache/streampark/flink/connector/hbase/source/HBaseJavaSource.java
  streampark-flink/streampark-flink-connector/streampark-flink-connector-jdbc/src/main/scala/org/apache/streampark/flink/connector/jdbc/sink/JdbcJavaSink.java
  streampark-flink/streampark-flink-connector/streampark-flink-connector-jdbc/src/main/scala/org/apache/streampark/flink/connector/jdbc/source/JdbcJavaSource.java
  streampark-flink/streampark-flink-connector/streampark-flink-connector-mongo/src/main/scala/org/apache/streampark/flink/connector/mongo/source/MongoJavaSource.java
  streampark-flink/streampark-flink-shims/streampark-flink-shims-base/src/main/scala/org/apache/streampark/flink/core/FlinkSqlValidator.scala
Labels: BACKEND, FLINK

#2328 update version
  build.sh
  pom.xml
  streampark-common/pom.xml
  streampark-common/src/main/scala/org/apache/streampark/common/conf/ConfigConst.scala
  streampark-console/pom.xml
  streampark-console/streampark-console-service/pom.xml
  streampark-console/streampark-console-service/src/main/assembly/bin/streampark.sh
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/base/config/SwaggerConfig.java
  streampark-flink/pom.xml
  streampark-flink/streampark-flink-client/pom.xml
  streampark-flink/streampark-flink-client/streampark-flink-client-api/pom.xml
  streampark-flink/streampark-flink-client/streampark-flink-client-core/pom.xml
  streampark-flink/streampark-flink-connector/pom.xml
  streampark-flink/streampark-flink-connector/streampark-flink-connector-base/pom.xml
  streampark-flink/streampark-flink-connector/streampark-flink-connector-clickhouse/pom.xml
  streampark-flink/streampark-flink-connector/streampark-flink-connector-doris/pom.xml
  streampark-flink/streampark-flink-connector/streampark-flink-connector-elasticsearch/pom.xml
  streampark-flink/streampark-flink-connector/streampark-flink-connector-elasticsearch/streampark-flink-connector-elasticsearch5/pom.xml
  streampark-flink/streampark-flink-connector/streampark-flink-connector-elasticsearch/streampark-flink-connector-elasticsearch6/pom.xml
  streampark-flink/streampark-flink-connector/streampark-flink-connector-elasticsearch/streampark-flink-connector-elasticsearch7/pom.xml
  streampark-flink/streampark-flink-connector/streampark-flink-connector-hbase/pom.xml
  streampark-flink/streampark-flink-connector/streampark-flink-connector-http/pom.xml
  streampark-flink/streampark-flink-connector/streampark-flink-connector-influx/pom.xml
  streampark-flink/streampark-flink-connector/streampark-flink-connector-jdbc/pom.xml
  streampark-flink/streampark-flink-connector/streampark-flink-connector-kafka/pom.xml
  streampark-flink/streampark-flink-connector/streampark-flink-connector-mongo/pom.xml
  streampark-flink/streampark-flink-connector/streampark-flink-connector-redis/pom.xml
  streampark-flink/streampark-flink-core/pom.xml
  streampark-flink/streampark-flink-kubernetes/pom.xml
  streampark-flink/streampark-flink-packer/pom.xml
  streampark-flink/streampark-flink-proxy/pom.xml
  streampark-flink/streampark-flink-shims/pom.xml
  streampark-flink/streampark-flink-shims/streampark-flink-shims-base/pom.xml
  streampark-flink/streampark-flink-shims/streampark-flink-shims-test/pom.xml
  streampark-flink/streampark-flink-shims/streampark-flink-shims_flink-1.12/pom.xml
  streampark-flink/streampark-flink-shims/streampark-flink-shims_flink-1.13/pom.xml
  streampark-flink/streampark-flink-shims/streampark-flink-shims_flink-1.14/pom.xml
  streampark-flink/streampark-flink-shims/streampark-flink-shims_flink-1.15/pom.xml
  streampark-flink/streampark-flink-shims/streampark-flink-shims_flink-1.16/pom.xml
  streampark-flink/streampark-flink-sqlclient/pom.xml
  streampark-flink/streampark-flink-udf/pom.xml
  streampark-spark/pom.xml
  streampark-spark/streampark-spark-cli/pom.xml
  streampark-spark/streampark-spark-connector/pom.xml
  streampark-spark/streampark-spark-connector/streampark-spark-connector-base/pom.xml
  streampark-spark/streampark-spark-connector/streampark-spark-connector-kafka/pom.xml
  streampark-spark/streampark-spark-core/pom.xml
  streampark-storage/pom.xml
Labels: BUILD, BACKEND, FLINK, KUBERNETES, SPARK

#2329 update version to 2.1.0-SNAPSHOT
  build.sh
  deploy/helm/streampark/Chart.yaml
  deploy/helm/streampark/values.yaml
  pom.xml
  streampark-common/pom.xml
  streampark-common/src/main/scala/org/apache/streampark/common/conf/ConfigConst.scala
  streampark-console/pom.xml
  streampark-console/streampark-console-service/pom.xml
  streampark-console/streampark-console-service/src/main/assembly/bin/streampark.sh
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/base/config/SwaggerConfig.java
  streampark-flink/pom.xml
  streampark-flink/streampark-flink-client/pom.xml
  streampark-flink/streampark-flink-client/streampark-flink-client-api/pom.xml
  streampark-flink/streampark-flink-client/streampark-flink-client-core/pom.xml
  streampark-flink/streampark-flink-connector/pom.xml
  streampark-flink/streampark-flink-connector/streampark-flink-connector-base/pom.xml
  streampark-flink/streampark-flink-connector/streampark-flink-connector-clickhouse/pom.xml
  streampark-flink/streampark-flink-connector/streampark-flink-connector-doris/pom.xml
  streampark-flink/streampark-flink-connector/streampark-flink-connector-elasticsearch/pom.xml
  streampark-flink/streampark-flink-connector/streampark-flink-connector-elasticsearch/streampark-flink-connector-elasticsearch5/pom.xml
  streampark-flink/streampark-flink-connector/streampark-flink-connector-elasticsearch/streampark-flink-connector-elasticsearch6/pom.xml
  streampark-flink/streampark-flink-connector/streampark-flink-connector-elasticsearch/streampark-flink-connector-elasticsearch7/pom.xml
  streampark-flink/streampark-flink-connector/streampark-flink-connector-hbase/pom.xml
  streampark-flink/streampark-flink-connector/streampark-flink-connector-http/pom.xml
  streampark-flink/streampark-flink-connector/streampark-flink-connector-influx/pom.xml
  streampark-flink/streampark-flink-connector/streampark-flink-connector-jdbc/pom.xml
  streampark-flink/streampark-flink-connector/streampark-flink-connector-kafka/pom.xml
  streampark-flink/streampark-flink-connector/streampark-flink-connector-mongo/pom.xml
  streampark-flink/streampark-flink-connector/streampark-flink-connector-redis/pom.xml
  streampark-flink/streampark-flink-core/pom.xml
  streampark-flink/streampark-flink-kubernetes/pom.xml
  streampark-flink/streampark-flink-packer/pom.xml
  streampark-flink/streampark-flink-proxy/pom.xml
  streampark-flink/streampark-flink-shims/pom.xml
  streampark-flink/streampark-flink-shims/streampark-flink-shims-base/pom.xml
  streampark-flink/streampark-flink-shims/streampark-flink-shims-test/pom.xml
  streampark-flink/streampark-flink-shims/streampark-flink-shims_flink-1.12/pom.xml
  streampark-flink/streampark-flink-shims/streampark-flink-shims_flink-1.13/pom.xml
  streampark-flink/streampark-flink-shims/streampark-flink-shims_flink-1.14/pom.xml
  streampark-flink/streampark-flink-shims/streampark-flink-shims_flink-1.15/pom.xml
  streampark-flink/streampark-flink-shims/streampark-flink-shims_flink-1.16/pom.xml
  streampark-flink/streampark-flink-sqlclient/pom.xml
  streampark-flink/streampark-flink-udf/pom.xml
  streampark-spark/pom.xml
  streampark-spark/streampark-spark-cli/pom.xml
  streampark-spark/streampark-spark-connector/pom.xml
  streampark-spark/streampark-spark-connector/streampark-spark-connector-base/pom.xml
  streampark-spark/streampark-spark-connector/streampark-spark-connector-kafka/pom.xml
  streampark-spark/streampark-spark-core/pom.xml
  streampark-storage/pom.xml
Labels: BUILD, DOCKER, BACKEND, FLINK, KUBERNETES, SPARK

#2333 [Bug] "state.checkpoints.num-retained" is invalid
  streampark-flink/streampark-flink-client/streampark-flink-client-core/src/main/scala/org/apache/streampark/flink/client/trait/FlinkSubmitTrait.scala
Labels: FLINK

#2334 [improve] get state.checkpoints.num-retained improvement
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/SavePointServiceImpl.java
  streampark-flink/streampark-flink-client/streampark-flink-client-core/src/main/scala/org/apache/streampark/flink/client/trait/FlinkSubmitTrait.scala
Labels: BACKEND, FLINK

#2317 [Issue-2299] Support the yarn queue label quick-setting for yarn application mode.
  streampark-common/src/main/scala/org/apache/streampark/common/conf/ConfigConst.scala
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/entity/Application.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/entity/FlinkCluster.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ApplicationServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/FlinkClusterServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/utils/YarnQueueLabelExpression.java
  streampark-console/streampark-console-service/src/test/java/org/apache/streampark/console/core/utils/YarnQueueLabelExpressionTest.java
  streampark-console/streampark-console-webapp/src/locales/lang/en/flink/app.ts
  streampark-console/streampark-console-webapp/src/locales/lang/en/flink/setting.ts
  streampark-console/streampark-console-webapp/src/locales/lang/zh-CN/flink/app.ts
  streampark-console/streampark-console-webapp/src/locales/lang/zh-CN/flink/setting.ts
  streampark-console/streampark-console-webapp/src/views/flink/app/hooks/useCreateAndEditSchema.ts
  streampark-console/streampark-console-webapp/src/views/flink/app/hooks/useFlinkRender.tsx
  streampark-console/streampark-console-webapp/src/views/flink/app/hooks/useFlinkSchema.ts
  streampark-console/streampark-console-webapp/src/views/flink/setting/hooks/useClusterSetting.ts
Labels: WEB UI, BACKEND

#2335 [Improve] call utils.required improvement
  streampark-common/src/main/scala/org/apache/streampark/common/util/Utils.scala
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/base/interceptor/UploadFileTypeInterceptor.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/base/util/CommonUtils.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/controller/ProjectController.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/runner/EnvInitializer.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/alert/impl/AlertServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/AppBuildPipeServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ApplicationBackUpServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ApplicationServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/FlinkSqlServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ProjectServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/SqlCompleteServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/task/FlinkRESTAPIWatcher.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/service/impl/MemberServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/service/impl/UserServiceImpl.java
  streampark-flink/streampark-flink-connector/streampark-flink-connector-hbase/src/main/scala/org/apache/streampark/flink/connector/hbase/source/HBaseJavaSource.java
  streampark-flink/streampark-flink-connector/streampark-flink-connector-jdbc/src/main/scala/org/apache/streampark/flink/connector/jdbc/sink/JdbcJavaSink.java
  streampark-flink/streampark-flink-connector/streampark-flink-connector-jdbc/src/main/scala/org/apache/streampark/flink/connector/jdbc/source/JdbcJavaSource.java
  streampark-flink/streampark-flink-connector/streampark-flink-connector-mongo/src/main/scala/org/apache/streampark/flink/connector/mongo/source/MongoJavaSource.java
Labels: BACKEND, FLINK

#2336 bug report template Improvement
  .github/ISSUE_TEMPLATE/bug-report.yml
Labels: INFRA

#2337 issue report template improvement
  .github/ISSUE_TEMPLATE/bug-report.yml
Labels: INFRA

#2338 issue report template improvement
  .github/ISSUE_TEMPLATE/bug-report.yml
Labels: INFRA

#2342 [Hotfix] Fix the old 2.1.0 version to 2.1.0-SNAPSHOT
  build.sh
  streampark-common/src/main/scala/org/apache/streampark/common/conf/ConfigConst.scala
  streampark-console/streampark-console-service/src/main/assembly/bin/streampark.sh
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/base/config/SwaggerConfig.java
Labels: BUILD, BACKEND

#2346 [Improve] add i18n support for job sql version compare.
  streampark-console/streampark-console-webapp/src/locales/lang/en/flink/app.ts
  streampark-console/streampark-console-webapp/src/locales/lang/zh-CN/flink/app.ts
  streampark-console/streampark-console-webapp/src/views/flink/app/hooks/useFlinkRender.tsx
Labels: WEB UI

#2347 [Bug] Fix can't update yarnQueue when update application.
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/entity/Application.java
  streampark-console/streampark-console-webapp/src/views/flink/app/hooks/useCreateAndEditSchema.ts
Labels: WEB UI, BACKEND

#2351 [Improve] add i18n support for variable Management show info page.
  streampark-console/streampark-console-webapp/src/locales/lang/en/flink/variable.ts
  streampark-console/streampark-console-webapp/src/locales/lang/zh-CN/flink/variable.ts
  streampark-console/streampark-console-webapp/src/views/flink/variable/components/VariableInfo.vue
Labels: WEB UI

#2352 [Improve] README content
  README.md
Labels: DOCS

#2353 [Fix] Test classes should be under sp package
  streampark-console/streampark-console-service/src/test/java/com/github/benmanes/caffeine/cache/RefreshCacheTest.java
  streampark-console/streampark-console-service/src/test/java/org/apache/streampark/common/util/RegexTest.java
  streampark-console/streampark-console-service/src/test/java/org/apache/streampark/console/core/bean/SenderEmailTest.java
Labels: BACKEND

#2354 [Improve] Skip Docker build for forks
  .github/workflows/docker-push.yml
Labels: INFRA

#2357 [Issue-2330]fix get user-defined maven settings.xml
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/entity/Project.java
Labels: BACKEND

#2358 [Bug] Invalid signature file digest for Manifest main attributes bug fixed
  streampark-flink/streampark-flink-packer/src/main/scala/org/apache/streampark/flink/packer/maven/MavenTool.scala
Labels: FLINK

#2363 [Improve] Add agent settings for lark alarm.
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/alert/impl/LarkAlertNotifyServiceImpl.java
  streampark-console/streampark-console-service/src/main/resources/application.yml
Labels: BACKEND

#2368 [Hotfix] Update the icon of trigger-savepoint from database-outlined to camera-outlined
  streampark-console/streampark-console-webapp/src/views/flink/app/hooks/useAppTableAction.ts
Labels: WEB UI

#2367 [Improve] Related app release: LanuchState change to ReleaseState
  streampark-console/streampark-console-service/src/main/assembly/script/data/mysql-data.sql
  streampark-console/streampark-console-service/src/main/assembly/script/data/pgsql-data.sql
  streampark-console/streampark-console-service/src/main/assembly/script/schema/mysql-schema.sql
  streampark-console/streampark-console-service/src/main/assembly/script/schema/pgsql-schema.sql
  streampark-console/streampark-console-service/src/main/assembly/script/upgrade/mysql/2.1.0.sql
  streampark-console/streampark-console-service/src/main/assembly/script/upgrade/pgsql/2.1.0.sql
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/controller/ApplicationBuildPipelineController.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/controller/ApplicationController.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/entity/Application.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/entity/Project.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/enums/OptionState.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/enums/ReleaseState.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/ApplicationService.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/AppBuildPipeServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ApplicationBackUpServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ApplicationServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ProjectServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/SettingServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/task/FlinkRESTAPIWatcher.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/task/ProjectBuildTask.java
  streampark-console/streampark-console-service/src/main/resources/db/data-h2.sql
  streampark-console/streampark-console-service/src/main/resources/db/schema-h2.sql
  streampark-console/streampark-console-service/src/main/resources/mapper/core/ApplicationMapper.xml
  streampark-console/streampark-console-service/src/test/java/org/apache/streampark/console/core/service/ApplicationServiceTest.java
  streampark-console/streampark-console-webapp/src/api/flink/app/app.type.ts
  streampark-console/streampark-console-webapp/src/components/Table/src/types/table.ts
  streampark-console/streampark-console-webapp/src/enums/flinkEnum.ts
  streampark-console/streampark-console-webapp/src/locales/lang/en/flink/app.ts
  streampark-console/streampark-console-webapp/src/locales/lang/zh-CN/flink/app.ts
  streampark-console/streampark-console-webapp/src/views/flink/app/View.vue
  streampark-console/streampark-console-webapp/src/views/flink/app/components/State.tsx
  streampark-console/streampark-console-webapp/src/views/flink/app/data/index.ts
  streampark-console/streampark-console-webapp/src/views/flink/app/hooks/useApp.tsx
  streampark-console/streampark-console-webapp/src/views/flink/app/hooks/useAppTableAction.ts
  streampark-console/streampark-console-webapp/src/views/flink/app/utils/index.ts
Labels: BUILD, WEB UI, BACKEND

#2340 [Improve][Issue 2325] Change the corresponding lines about exception throw for fine users Interaction
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/base/exception/ApiAlertException.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/base/interceptor/UploadFileTypeInterceptor.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/controller/ProjectController.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ApplicationBackUpServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ApplicationServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/CommonServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/FlinkEnvServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ProjectServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/utils/YarnQueueLabelExpression.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/authentication/JWTFilter.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/authentication/JWTUtil.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/controller/UserController.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/service/impl/MemberServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/service/impl/RoleServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/service/impl/TeamServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/service/impl/UserServiceImpl.java
Labels: BACKEND

#2376 [Bug] After switch groups, the metrics dashboard info is not switched…
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/controller/ApplicationController.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/ApplicationService.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ApplicationServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/task/FlinkK8sWatcherWrapper.java
  streampark-console/streampark-console-webapp/src/api/flink/app/app.ts
  streampark-flink/streampark-flink-kubernetes/src/main/scala/org/apache/streampark/flink/kubernetes/DefaultFlinkK8sWatcher.scala
  streampark-flink/streampark-flink-kubernetes/src/main/scala/org/apache/streampark/flink/kubernetes/FlinkK8sWatchController.scala
  streampark-flink/streampark-flink-kubernetes/src/main/scala/org/apache/streampark/flink/kubernetes/FlinkK8sWatcher.scala
  streampark-flink/streampark-flink-kubernetes/src/main/scala/org/apache/streampark/flink/kubernetes/FlinkK8sWatcherLazyStartAop.scala
  streampark-flink/streampark-flink-kubernetes/src/main/scala/org/apache/streampark/flink/kubernetes/helper/KubernetesWatcherHelper.scala
  streampark-flink/streampark-flink-kubernetes/src/main/scala/org/apache/streampark/flink/kubernetes/model/FlinkMetricCV.scala
  streampark-flink/streampark-flink-kubernetes/src/main/scala/org/apache/streampark/flink/kubernetes/model/TrackId.scala
  streampark-flink/streampark-flink-kubernetes/src/main/scala/org/apache/streampark/flink/kubernetes/watcher/FlinkJobStatusWatcher.scala
  streampark-flink/streampark-flink-kubernetes/src/main/scala/org/apache/streampark/flink/kubernetes/watcher/FlinkMetricsWatcher.scala
Labels: WEB UI, BACKEND, FLINK, KUBERNETES

#2375 [Feature][Issue-2191][Issue-2215] Support external link #2331
  streampark-console/streampark-console-service/src/main/assembly/script/data/mysql-data.sql
  streampark-console/streampark-console-service/src/main/assembly/script/data/pgsql-data.sql
  streampark-console/streampark-console-service/src/main/assembly/script/schema/mysql-schema.sql
  streampark-console/streampark-console-service/src/main/assembly/script/schema/pgsql-schema.sql
  streampark-console/streampark-console-service/src/main/assembly/script/upgrade/mysql/2.1.0.sql
  streampark-console/streampark-console-service/src/main/assembly/script/upgrade/pgsql/2.1.0.sql
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/controller/ExternalLinkController.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/entity/ExternalLink.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/enums/PlaceholderType.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/mapper/ExternalLinkMapper.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/ExternalLinkService.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ExternalLinkServiceImpl.java
  streampark-console/streampark-console-service/src/main/resources/db/data-h2.sql
  streampark-console/streampark-console-service/src/main/resources/db/schema-h2.sql
  streampark-console/streampark-console-service/src/main/resources/mapper/core/ExternalLinkMapper.xml
  streampark-console/streampark-console-webapp/src/api/flink/setting/externalLink.ts
  streampark-console/streampark-console-webapp/src/api/flink/setting/types/externalLink.type.ts
  streampark-console/streampark-console-webapp/src/locales/lang/en/flink/setting.ts
  streampark-console/streampark-console-webapp/src/locales/lang/zh-CN/flink/setting.ts
  streampark-console/streampark-console-webapp/src/views/flink/app/Detail.vue
  streampark-console/streampark-console-webapp/src/views/flink/setting/View.vue
  streampark-console/streampark-console-webapp/src/views/flink/setting/components/ExternalLinkBadge.vue
  streampark-console/streampark-console-webapp/src/views/flink/setting/components/ExternalLinkModal.vue
  streampark-console/streampark-console-webapp/src/views/flink/setting/components/ExternalLinkSetting.vue
  streampark-console/streampark-console-webapp/src/views/flink/setting/hooks/useExternalLink.tsx
Labels: BUILD, WEB UI, BACKEND
