Repository apache/streampark, pull requests merged in 2024-03, with the labels that each got.

#3593 [Feat] docker check support
  streampark-console/streampark-console-service/pom.xml
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/SettingServiceImpl.java
  streampark-console/streampark-console-service/src/test/java/org/apache/streampark/console/core/service/SettingServiceTest.java
  streampark-console/streampark-console-webapp/src/views/setting/System/SettingForm.vue
Labels: BUILD, WEB UI, BACKEND

#3595 The prompt for starting the job has an extra ‘p’.
  streampark-console/streampark-console-webapp/src/locales/lang/zh-CN/flink/app.ts
Labels: WEB UI

#3597 [ISSUE-3066][console-service] Improve streampark-console module base on [3.3 Methods Rule]
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/base/exception/ApiAlertException.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/component/FlinkCheckpointProcessor.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/entity/ApplicationBackUp.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/entity/ApplicationConfig.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/entity/Project.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/runner/EnvInitializer.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/alert/impl/AlertServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/alert/impl/DingTalkAlertNotifyServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/alert/impl/HttpCallbackAlertNotifyServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/alert/impl/LarkAlertNotifyServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/application/impl/ApplicationActionServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/application/impl/ApplicationInfoServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/application/impl/ApplicationManageServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/AppBuildPipeServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ApplicationConfigServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/FlinkClusterServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ProjectServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ResourceServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/SavePointServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/SqlWorkBenchServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/watcher/FlinkAppHttpWatcher.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/authentication/SsoShiroPlugin.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/security/impl/AuthenticatorImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/security/impl/LdapService.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/service/impl/MemberServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/service/impl/TeamServiceImpl.java
Labels: BACKEND

#3603 [Imporve] changeStateEvnet equals improvements
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/SavePointServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/task/FlinkAppHttpWatcher.java
  streampark-console/streampark-console-webapp/src/views/flink/app/hooks/useSavepoint.tsx
Labels: WEB UI, BACKEND

#3594 [ISUEE-3578][Improve] Merge dev-2.1.3 Docker & Email BackedEnd Improve Into dev
  streampark-console/streampark-console-service/src/main/assembly/script/data/mysql-data.sql
  streampark-console/streampark-console-service/src/main/assembly/script/data/pgsql-data.sql
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/bean/DockerConfig.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/bean/SenderEmail.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/controller/SettingController.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/SettingService.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/AppBuildPipeServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/SettingServiceImpl.java
  streampark-console/streampark-console-service/src/main/resources/db/data-h2.sql
  streampark-console/streampark-console-service/src/test/java/org/apache/streampark/console/core/service/SettingServiceTest.java
Labels: BUILD, BACKEND

#3616 [Fix] fix Unstable test case
  streampark-console/streampark-console-service/src/test/java/org/apache/streampark/console/core/service/YarnQueueServiceTest.java
Labels: BACKEND

#3622 [Improve] add yarn api error log for debug some problems
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ApplicationServiceImpl.java
Labels: BACKEND

#3625 [Improve] AssertUtils add and check not null improvements
  streampark-common/src/main/java/org/apache/streampark/common/util/ExceptionUtils.java
  streampark-common/src/main/scala/org/apache/streampark/common/fs/LfsOperator.scala
  streampark-common/src/main/scala/org/apache/streampark/common/util/AssertUtils.scala
  streampark-common/src/main/scala/org/apache/streampark/common/util/ExceptionUtils.scala
  streampark-common/src/main/scala/org/apache/streampark/common/util/FileUtils.scala
  streampark-common/src/main/scala/org/apache/streampark/common/util/Logger.scala
  streampark-common/src/main/scala/org/apache/streampark/common/util/PropertiesUtils.scala
  streampark-common/src/main/scala/org/apache/streampark/common/util/Utils.scala
  streampark-common/src/test/scala/org/apache/streampark/common/util/UtilsTest.scala
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/bean/Dependency.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/component/FlinkCheckpointProcessor.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/controller/ExternalLinkController.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/entity/Project.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/runner/EnvInitializer.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/application/impl/ApplicationActionServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/AppBuildPipeServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ExternalLinkServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/FlinkSqlServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ProjectServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/SavePointServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/SqlCompleteServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/YarnQueueServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/service/impl/MemberServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/service/impl/UserServiceImpl.java
  streampark-console/streampark-console-service/src/test/java/org/apache/streampark/console/SpringIntegrationTestBase.java
  streampark-flink/streampark-flink-packer/src/main/scala/org/apache/streampark/flink/packer/docker/DockerRetriever.scala
  streampark-tests/streampark-testcontainer/src/main/java/org/apache/streampark/testcontainer/flink/FlinkStandaloneSessionCluster.java
Labels: BACKEND, FLINK

#3629 [ISSUES-3627] Fix Adding flink1.19 environment configuration exception
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/entity/FlinkEnv.java
Labels: BACKEND

#3632 [hotfix] Add maven ci on release-* and dev-* branch
  .github/workflows/maven.yml
Labels: INFRA

#3631 [hotfix] Fix code style and enable maven ci on dev-* branch
  .github/workflows/maven.yml
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ApplicationServiceImpl.java
Labels: INFRA, BACKEND

#3636 [ISSUES-3627] doSetFlinkConf and doSetVersion are changed in sequence
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/FlinkEnvServiceImpl.java
Labels: BACKEND

#3634 Resolving streampark flink on k8s that flink task status is failed but k8s pod still alive
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/task/FlinkK8sChangeEventListener.java
Labels: BACKEND

#3630 [ISSUES-3623] Project management encrypts user warehouse passwords
  streampark-console/streampark-console-service/src/main/assembly/script/data/mysql-data.sql
  streampark-console/streampark-console-service/src/main/assembly/script/data/pgsql-data.sql
  streampark-console/streampark-console-service/src/main/assembly/script/schema/mysql-schema.sql
  streampark-console/streampark-console-service/src/main/assembly/script/schema/pgsql-schema.sql
  streampark-console/streampark-console-service/src/main/assembly/script/upgrade/mysql/2.2.2.sql
  streampark-console/streampark-console-service/src/main/assembly/script/upgrade/pgsql/2.2.2.sql
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/base/util/GitUtils.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/controller/ProjectController.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/entity/Project.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/ProjectService.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ProjectServiceImpl.java
  streampark-console/streampark-console-webapp/src/views/resource/project/useProject.tsx
Labels: BUILD, WEB UI, BACKEND

#3639 [ISSUE -3638][Fix] Flink native k8s application task with INITIALIZING…
  streampark-flink/streampark-flink-kubernetes/src/main/scala/org/apache/streampark/flink/kubernetes/KubernetesRetriever.scala
  streampark-flink/streampark-flink-kubernetes/src/main/scala/org/apache/streampark/flink/kubernetes/ingress/IngressController.scala
  streampark-flink/streampark-flink-kubernetes/src/main/scala/org/apache/streampark/flink/kubernetes/ingress/IngressStrategy.scala
  streampark-flink/streampark-flink-kubernetes/src/main/scala/org/apache/streampark/flink/kubernetes/ingress/IngressStrategyV1.scala
  streampark-flink/streampark-flink-kubernetes/src/main/scala/org/apache/streampark/flink/kubernetes/ingress/IngressStrategyV1beta1.scala
Labels: FLINK, KUBERNETES

#3640 [Imporve][Flink-Kubernetes-V2] Update crd to the 1.8.0 version
  streampark-flink/streampark-flink-kubernetes-v2/streampark-flink-kubernetes-crd/src/main/resources/crd/flinkdeployments.flink.apache.org-v1.yml
  streampark-flink/streampark-flink-kubernetes-v2/streampark-flink-kubernetes-crd/src/main/resources/crd/flinksessionjobs.flink.apache.org-v1.yml
Labels: FLINK

#3642 [Imporve] Imporve CommandUtilsTest
  streampark-common/src/test/scala/org/apache/streampark/common/util/CommandUtilsTest.scala
  streampark-common/src/test/scala/org/apache/streampark/common/util/FileUtilsTest.scala
Labels: BACKEND

#3643 [Imporve][Flink-Kubernetes-V2] Improve UsingOperator test
  streampark-flink/streampark-flink-kubernetes-v2/streampark-flink-kubernetes-core/src/test/scala/org/apache/streampark/flink/kubernetes/v2/example/UsingOperator.scala
Labels: FLINK

#3644 [Improve] maven build args check improvement
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/entity/Project.java
Labels: BACKEND
