Repository apache/streampark, pull requests merged in 2024-02, with the labels that each got.

#3528 [Improve] Optimize equals method conflicts
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/bean/Dependency.java
Labels: first time contributor, BACKEND

#3533 [Improve] lombok improvement
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/base/domain/RestRequest.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/base/domain/router/RouterMeta.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/base/domain/router/RouterTree.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/base/domain/router/VueRouter.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/base/properties/ShiroProperties.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/bean/AlertConfigWithParams.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/bean/AlertDingTalkParams.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/bean/AlertEmailParams.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/bean/AlertHttpCallbackParams.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/bean/AlertLarkParams.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/bean/AlertLarkRobotResponse.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/bean/AlertTemplate.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/bean/AlertWeComParams.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/bean/AppBuildDockerResolvedDetail.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/bean/AppControl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/bean/MavenDependency.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/bean/MavenExclusion.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/bean/MavenPom.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/bean/ResponseResult.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/bean/RobotResponse.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/bean/SenderEmail.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/entity/AlertConfig.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/entity/AppBuildPipeline.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/entity/Application.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/entity/ApplicationBackUp.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/entity/ApplicationConfig.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/entity/ApplicationLog.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/entity/Effective.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/entity/ExternalLink.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/entity/FlinkCluster.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/entity/FlinkEnv.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/entity/FlinkSql.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/entity/Message.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/entity/Project.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/entity/SavePoint.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/entity/Setting.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/entity/Variable.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/entity/YarnQueue.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/metrics/flink/CheckPoints.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/metrics/flink/JobsOverview.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/metrics/flink/Overview.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/metrics/yarn/YarnAppInfo.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/task/CheckpointProcessor.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/authentication/JWTToken.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/entity/AccessToken.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/entity/Member.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/entity/Menu.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/entity/Role.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/entity/RoleMenu.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/entity/SysLog.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/entity/Team.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/entity/User.java
Labels: BACKEND

#3535 [Improve] executors improvement
  streampark-common/src/main/scala/org/apache/streampark/common/util/YarnUtils.scala
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/annotation/AppUpdated.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/aspect/StreamParkAspect.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/alert/impl/AlertServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/AppBuildPipeServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ApplicationServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/FlinkClusterServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ProjectServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/SavePointServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/task/CheckpointProcessor.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/task/FlinkAppHttpWatcher.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/task/FlinkK8sChangeEventListener.java
Labels: BACKEND, YARN

#3536 [Bug] job running duration bug fixed.
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/bean/AlertTemplate.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/controller/AlertController.java
  streampark-console/streampark-console-service/src/test/java/org/apache/streampark/console/core/service/alert/AlertServiceTest.java
Labels: BACKEND

#3539 [Improve] job state lost improvement
  streampark-common/src/main/scala/org/apache/streampark/common/util/DateUtils.scala
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/bean/AlertTemplate.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/entity/Application.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ApplicationServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/task/FlinkAppHttpWatcher.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/task/FlinkK8sChangeEventListener.java
  streampark-console/streampark-console-service/src/test/java/org/apache/streampark/console/core/service/alert/AlertServiceTest.java
Labels: BACKEND

#3541 [Fix] k8sClusterId is none
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ApplicationServiceImpl.java
Labels: BACKEND

#3529 [WIP][Fix] The initialization of the configuration comes before the bean is loaded
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/StreamParkConsoleBootstrap.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/runner/EnvApplicationContextInitializer.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/runner/EnvInitializer.java
Labels: BACKEND

#3542 [Bug] fixed the CI failed
  streampark-common/src/main/scala/org/apache/streampark/common/conf/InternalConfigHolder.scala
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/StreamParkConsoleBootstrap.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/runner/EnvApplicationContextInitializer.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/runner/EnvInitializer.java
  streampark-console/streampark-console-service/src/main/resources/db/data-h2.sql
Labels: BACKEND

#3543 [Improve] update job run state improvement
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/controller/ApplicationController.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/entity/Application.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ApplicationServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/task/FlinkAppHttpWatcher.java
Labels: BACKEND

#3545 Run state
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ApplicationServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ProjectServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/task/FlinkAppHttpWatcher.java
Labels: BACKEND

#3546 [Improve] Flink job status monitoring improvement
  streampark-console/streampark-console-service/src/main/assembly/script/upgrade/mysql/2.1.3.sql
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/controller/ApplicationBuildPipelineController.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ApplicationServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/task/FlinkAppHttpWatcher.java
  streampark-console/streampark-console-service/src/main/resources/db/data-h2.sql
  streampark-console/streampark-console-webapp/src/locales/lang/zh-CN/flink/app.ts
  streampark-console/streampark-console-webapp/src/locales/lang/zh-CN/menu.ts
  streampark-console/streampark-console-webapp/src/views/flink/app/View.vue
  streampark-console/streampark-console-webapp/src/views/flink/app/hooks/useAppTableAction.ts
Labels: BUILD, WEB UI, BACKEND

#3547 [Improve][Docs] Add how to join the mailing lists
  README.md
Labels: DOCS

#3550 [Improve] Add dependency support to unit tests on streampark-common_2.12
  streampark-common/pom.xml
Labels: BUILD, BACKEND

#3555 [ISSUES-3063][Improve] Improve ImplicitsUtilsTest test code coverage
  streampark-common/src/test/scala/org/apache/streampark/common/util/ImplicitsUtilsTest.scala
Labels: BACKEND

#3557 [Imprpve] JDBC "like" syntax is compatible with mysql and pgsql
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/base/config/MybatisConfig.java
  streampark-console/streampark-console-service/src/main/resources/mapper/core/ApplicationMapper.xml
  streampark-console/streampark-console-service/src/main/resources/mapper/core/ProjectMapper.xml
  streampark-console/streampark-console-service/src/main/resources/mapper/core/VariableMapper.xml
  streampark-console/streampark-console-service/src/main/resources/mapper/core/YarnQueueMapper.xml
  streampark-console/streampark-console-service/src/main/resources/mapper/system/MemberMapper.xml
  streampark-console/streampark-console-service/src/main/resources/mapper/system/RoleMapper.xml
  streampark-console/streampark-console-service/src/main/resources/mapper/system/TeamMapper.xml
  streampark-console/streampark-console-service/src/main/resources/mapper/system/UserMapper.xml
  streampark-console/streampark-console-webapp/src/locales/lang/en/flink/app.ts
  streampark-console/streampark-console-webapp/src/locales/lang/zh-CN/flink/app.ts
  streampark-console/streampark-console-webapp/src/views/flink/app/hooks/useAppTableAction.ts
Labels: WEB UI, BACKEND

#3553 [ISSUES-3063][Improve] Improve CommandUtil test code coverage
  streampark-common/src/test/scala/org/apache/streampark/common/util/CommandUtilsTest.scala
Labels: BACKEND

#3560 [ISSUES-3063][Improve] Improve ThreadUtils test code coverage
  streampark-common/src/test/scala/org/apache/streampark/common/util/ThreadUtilsTest.scala
Labels: BACKEND

#3556 [ISSUES-3063][Improve] Improve ReflectUtils test code coverage
  streampark-common/src/test/scala/org/apache/streampark/common/util/ReflectUtilsTest.scala
Labels: BACKEND

#3562 [Improve]: header bar add Qrcode image & add language header
  streampark-console/streampark-console-webapp/src/assets/images/join_wechat.png
  streampark-console/streampark-console-webapp/src/layouts/default/header/index.vue
  streampark-console/streampark-console-webapp/src/utils/http/axios/index.ts
Labels: WEB UI

#3561 [Improve] Make the create time equal to update time when create a application
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/application/impl/ApplicationManageServiceImpl.java
Labels: BACKEND

#3559 [ISSUES-3063][Impprove] Improve Utils test code coverage
  streampark-common/src/test/scala/org/apache/streampark/common/util/UtilsTest.scala
Labels: BACKEND

#3552 [ISSUES-3063][Improve] Improve DateUtils unit test code coverage
  streampark-common/src/test/scala/org/apache/streampark/common/util/DateUtilsTest.scala
Labels: BACKEND

#3558 [ISSUES-3063][Improve] Improve ImplicitsUtilsTest test code coverage
  streampark-common/src/test/scala/org/apache/streampark/common/util/ImplicitsUtilsTest.scala
Labels: BACKEND

#3554 [ISSUES-3063][Improve] Improve FileUtils test code coverage
  pom.xml
  streampark-common/pom.xml
  streampark-common/src/test/scala/org/apache/streampark/common/util/FileUtilsTest.scala
Labels: BUILD, BACKEND

#3568 [BUG][FLINK-DEPEND]Fix flink lib to exclude dependencies that do not end in.jar
  streampark-flink/streampark-flink-proxy/src/main/scala/org/apache/streampark/flink/proxy/FlinkShimsProxy.scala
Labels: FLINK

#3571 [ISSUE-3085][Improve] Improve streampark-flink module based on [3.4 Collection Rule]
  streampark-flink/streampark-flink-connector/streampark-flink-connector-doris/src/main/java/org/apache/streampark/flink/connector/doris/bean/DorisSinkBufferEntry.java
Labels: FLINK

#3573 [Improve] mysql ddl current_timestamp syntax compatibility improvement
  streampark-console/streampark-console-service/src/main/assembly/script/schema/mysql-schema.sql
  streampark-console/streampark-console-service/src/main/assembly/script/schema/pgsql-schema.sql
  streampark-console/streampark-console-service/src/main/assembly/script/upgrade/mysql/2.0.0.sql
  streampark-console/streampark-console-service/src/main/assembly/script/upgrade/mysql/2.1.0.sql
  streampark-console/streampark-console-service/src/main/assembly/script/upgrade/mysql/2.1.3.sql
  streampark-console/streampark-console-service/src/main/assembly/script/upgrade/pgsql/2.1.0.sql
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/controller/SettingController.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/entity/FlinkCluster.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/entity/FlinkSql.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/entity/Variable.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ApplicationServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ExternalLinkServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/FlinkEnvServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ProjectServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/SavePointServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/SqlCompleteServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/VariableServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/YarnQueueServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/controller/AccessTokenController.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/entity/SysLog.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/service/AccessTokenService.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/service/impl/AccessTokenServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/service/impl/MemberServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/service/impl/MenuServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/service/impl/RoleServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/service/impl/TeamServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/service/impl/UserServiceImpl.java
  streampark-console/streampark-console-service/src/main/resources/db/schema-h2.sql
  streampark-console/streampark-console-service/src/test/java/org/apache/streampark/console/SpringTestBase.java
  streampark-console/streampark-console-service/src/test/java/org/apache/streampark/console/core/service/AccessTokenServiceTest.java
  streampark-console/streampark-console-webapp/src/api/flink/setting/index.ts
Labels: BUILD, WEB UI, BACKEND

#3580 [Improve] JAVA_OPTS improvement
  streampark-console/streampark-console-service/src/main/assembly/bin/jvm_opts.sh
  streampark-console/streampark-console-service/src/main/assembly/bin/streampark.sh
Labels: BUILD, BACKEND

#3582 [Improve] docker|email settings improvement
  streampark-console/streampark-console-service/src/main/assembly/script/data/mysql-data.sql
  streampark-console/streampark-console-service/src/main/assembly/script/data/pgsql-data.sql
  streampark-console/streampark-console-service/src/main/assembly/script/upgrade/mysql/2.0.0.sql
  streampark-console/streampark-console-service/src/main/resources/db/data-h2.sql
  streampark-console/streampark-console-webapp/src/assets/icons/edit.svg
  streampark-console/streampark-console-webapp/src/assets/icons/nginx.svg
  streampark-console/streampark-console-webapp/src/assets/icons/save.svg
  streampark-console/streampark-console-webapp/src/assets/icons/settings.svg
  streampark-console/streampark-console-webapp/src/assets/icons/settings2.svg
  streampark-console/streampark-console-webapp/src/views/setting/System/SettingList.vue
Labels: BUILD, WEB UI, BACKEND

#3585 [Improve] Refactor update setting interface
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/bean/DockerConfig.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/bean/MavenConfig.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/bean/SettingAlertEmailConfigParams.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/bean/SettingDockerConfigParams.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/controller/SettingController.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/SettingService.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/SettingServiceImpl.java
  streampark-console/streampark-console-service/src/test/java/org/apache/streampark/console/core/bean/SettingAlertEmailConfigParamsTest.java
  streampark-console/streampark-console-service/src/test/java/org/apache/streampark/console/core/bean/SettingDockerConfigParamsTest.java
  streampark-console/streampark-console-service/src/test/java/org/apache/streampark/console/core/service/SettingServiceTest.java
Labels: BACKEND

#3586 [Improve] docker|email settings improvements
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/bean/DockerConfig.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/bean/MavenConfig.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/bean/SenderEmail.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/bean/SettingAlertEmailConfigParams.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/bean/SettingDockerConfigParams.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/controller/SettingController.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/runner/EnvInitializer.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/SettingService.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/alert/impl/EmailAlertNotifyServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/AppBuildPipeServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/SettingServiceImpl.java
  streampark-console/streampark-console-service/src/test/java/org/apache/streampark/console/core/bean/SettingAlertEmailConfigParamsTest.java
  streampark-console/streampark-console-service/src/test/java/org/apache/streampark/console/core/bean/SettingDockerConfigParamsTest.java
  streampark-console/streampark-console-service/src/test/java/org/apache/streampark/console/core/service/SettingServiceTest.java
  streampark-console/streampark-console-service/src/test/java/org/apache/streampark/console/core/service/alert/AlertServiceTest.java
  streampark-console/streampark-console-webapp/src/api/flink/setting/index.ts
  streampark-console/streampark-console-webapp/src/views/setting/System/SettingForm.vue
  streampark-console/streampark-console-webapp/src/views/setting/System/SettingList.vue
Labels: WEB UI, BACKEND

#3587 [ISSUE-3490][BUG] Fixed copy error when new jobName is too long
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ApplicationServiceImpl.java
Labels: BACKEND

#3588 [Improve]: Optimize Docker and Email Settings Page Popup Content
  streampark-console/streampark-console-webapp/src/api/flink/setting/index.ts
  streampark-console/streampark-console-webapp/src/locales/lang/en/setting/system.ts
  streampark-console/streampark-console-webapp/src/locales/lang/zh-CN/setting/system.ts
  streampark-console/streampark-console-webapp/src/views/setting/System/SettingForm.vue
  streampark-console/streampark-console-webapp/src/views/setting/System/config.ts
Labels: WEB UI

#3572 [Improve] mysql and postgre ddl current_timestamp syntax compatibility improvement.
  streampark-console/streampark-console-service/src/main/assembly/script/schema/mysql-schema.sql
  streampark-console/streampark-console-service/src/main/assembly/script/schema/pgsql-schema.sql
  streampark-console/streampark-console-service/src/main/assembly/script/upgrade/mysql/2.0.0.sql
  streampark-console/streampark-console-service/src/main/assembly/script/upgrade/mysql/2.1.0.sql
  streampark-console/streampark-console-service/src/main/assembly/script/upgrade/mysql/2.2.0.sql
  streampark-console/streampark-console-service/src/main/assembly/script/upgrade/pgsql/2.1.0.sql
  streampark-console/streampark-console-service/src/main/assembly/script/upgrade/pgsql/2.2.0.sql
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/controller/SettingController.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/entity/FlinkCluster.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/entity/Resource.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/entity/Variable.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/application/impl/ApplicationManageServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ExternalLinkServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ProjectServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/security/impl/AuthenticatorImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/service/impl/AccessTokenServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/service/impl/MemberServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/service/impl/RoleServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/service/impl/TeamServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/service/impl/UserServiceImpl.java
  streampark-console/streampark-console-service/src/main/resources/db/schema-h2.sql
Labels: BUILD, BACKEND

#3590 [Improve] Check email Setting before update
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/SettingServiceImpl.java
  streampark-console/streampark-console-service/src/test/java/org/apache/streampark/console/core/service/SettingServiceTest.java
Labels: BACKEND
