Repository apache/streampark, pull requests merged in 2024-01, with the labels that each got.

#3441 [Improve] sql check improvement
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/base/domain/RestRequest.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/base/mybatis/pager/MybatisPager.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/entity/Resource.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/entity/Variable.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/entity/YarnQueue.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/alert/impl/AlertConfigServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/application/impl/ApplicationManageServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ApplicationBackUpServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ApplicationConfigServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ApplicationLogServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/FlinkSqlServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/MessageServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ProjectServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ResourceServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/SavePointServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/VariableServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/YarnQueueServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/entity/Member.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/entity/Role.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/entity/Team.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/entity/User.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/service/impl/AccessTokenServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/service/impl/MemberServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/service/impl/RoleServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/service/impl/TeamServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/service/impl/UserServiceImpl.java
  streampark-console/streampark-console-service/src/main/resources/mapper/core/YarnQueueMapper.xml
  streampark-console/streampark-console-service/src/main/resources/mapper/system/MemberMapper.xml
  streampark-console/streampark-console-service/src/main/resources/mapper/system/RoleMapper.xml
  streampark-console/streampark-console-service/src/main/resources/mapper/system/TeamMapper.xml
  streampark-console/streampark-console-service/src/main/resources/mapper/system/UserMapper.xml
  streampark-console/streampark-console-service/src/test/java/org/apache/streampark/console/core/service/YarnQueueServiceTest.java
Labels: BACKEND

#3440 [Improve] maven build args check improvement
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/entity/Project.java
Labels: BACKEND

#3444 [Doc] Update license
  README.md
Labels: DOCS

#3443 [Feature] apache-rat-plugin support
  .asf.yaml
  .editorconfig
  .git-blame-ignore-revs
  .gitattributes
  .github/workflows/maven.yml
  .github/workflows/pull-request-robot.yml
  .gitignore
  .licenserc.yaml
  .mvn/wrapper/maven-wrapper.properties
  .scalafmt-fp.conf
  .scalafmt.conf
  deploy/docker/Dockerfile
  deploy/helm/streampark/conf/streampark-console-config/ValidationMessages.properties
  deploy/helm/streampark/conf/streampark-console-config/application-h2.yml
  deploy/helm/streampark/conf/streampark-console-config/application-mysql.yml
  deploy/helm/streampark/conf/streampark-console-config/application-pgsql.yml
  deploy/helm/streampark/conf/streampark-console-config/application-sso.yml
  deploy/helm/streampark/conf/streampark-console-config/application.yml
  deploy/helm/streampark/conf/streampark-console-config/kerberos.yml
  deploy/helm/streampark/conf/streampark-console-config/spy.properties
  mvnw
  pom.xml
  streampark-console/streampark-console-service/src/main/assembly/bin/mvnw
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/aspect/ConsoleAspect.java
  streampark-console/streampark-console-service/src/main/resources/ValidationMessages.properties
  streampark-console/streampark-console-service/src/main/resources/application-h2.yml
  streampark-console/streampark-console-service/src/main/resources/application-mysql.yml
  streampark-console/streampark-console-service/src/main/resources/application-pgsql.yml
  streampark-console/streampark-console-service/src/main/resources/application-sso.yml
  streampark-console/streampark-console-service/src/main/resources/application.yml
  streampark-console/streampark-console-service/src/main/resources/flink-application.conf
  streampark-console/streampark-console-service/src/main/resources/kerberos.yml
  streampark-console/streampark-console-service/src/main/resources/spy.properties
  streampark-console/streampark-console-service/src/test/resources/application-integration-test.yml
  streampark-console/streampark-console-service/src/test/resources/application-test.yml
  streampark-console/streampark-console-webapp/.editorconfig
  streampark-console/streampark-console-webapp/.env
  streampark-console/streampark-console-webapp/.env.development
  streampark-console/streampark-console-webapp/.env.production
  streampark-console/streampark-console-webapp/.eslintignore
  streampark-console/streampark-console-webapp/.prettierignore
  streampark-console/streampark-console-webapp/.stylelintignore
  streampark-flink/streampark-flink-client/streampark-flink-client-core/src/main/resources/META-INF/services/org.apache.flink.client.deployment.StandaloneClientFactory
  streampark-flink/streampark-flink-client/streampark-flink-client-core/src/main/resources/META-INF/services/org.apache.flink.kubernetes.KubernetesClusterClientFactory
  streampark-flink/streampark-flink-client/streampark-flink-client-core/src/main/resources/META-INF/services/org.apache.flink.yarn.YarnClusterClientFactory
  streampark-spark/streampark-spark-cli/create_app.sh
  streampark-spark/streampark-spark-cli/create_conf.sh
  streampark-spark/streampark-spark-cli/default.properties
Labels: BUILD, INFRA, DOCKER, BACKEND, FLINK, SPARK

#3448 [Fix] replace old judgement method
  streampark-flink/streampark-flink-connector/streampark-flink-connector-hbase/src/main/java/org/apache/streampark/flink/connector/hbase/source/HBaseJavaSource.java
  streampark-flink/streampark-flink-connector/streampark-flink-connector-jdbc/src/main/java/org/apache/streampark/flink/connector/jdbc/sink/JdbcJavaSink.java
  streampark-flink/streampark-flink-connector/streampark-flink-connector-jdbc/src/main/java/org/apache/streampark/flink/connector/jdbc/source/JdbcJavaSource.java
  streampark-flink/streampark-flink-connector/streampark-flink-connector-mongo/src/main/java/org/apache/streampark/flink/connector/mongo/source/MongoJavaSource.java
Labels: FLINK

#3449 [Improve] clone project connect type improvement
  streampark-console/streampark-console-service/src/main/assembly/script/data/mysql-data.sql
  streampark-console/streampark-console-service/src/main/assembly/script/data/pgsql-data.sql
  streampark-console/streampark-console-service/src/main/assembly/script/schema/mysql-schema.sql
  streampark-console/streampark-console-service/src/main/assembly/script/schema/pgsql-schema.sql
  streampark-console/streampark-console-service/src/main/assembly/script/upgrade/mysql/2.1.3.sql
  streampark-console/streampark-console-service/src/main/assembly/script/upgrade/pgsql/2.1.3.sql
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/base/util/GitUtils.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/entity/Project.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/enums/GitCredential.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ProjectServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/task/ProjectBuildTask.java
  streampark-console/streampark-console-service/src/main/resources/db/data-h2.sql
  streampark-console/streampark-console-service/src/main/resources/db/schema-h2.sql
  streampark-console/streampark-console-service/src/main/resources/mapper/core/ProjectMapper.xml
  streampark-console/streampark-console-service/src/test/java/org/apache/streampark/console/core/entity/ProjectTest.java
  streampark-console/streampark-console-webapp/src/components/Application/src/AppDarkModeToggle.vue
  streampark-console/streampark-console-webapp/src/components/ContextMenu/src/ContextMenu.vue
  streampark-console/streampark-console-webapp/src/components/Form/src/BasicForm.vue
  streampark-console/streampark-console-webapp/src/components/Page/src/PageFooter.vue
  streampark-console/streampark-console-webapp/src/components/Table/src/components/HeaderCell.vue
  streampark-console/streampark-console-webapp/src/enums/projectEnum.ts
  streampark-console/streampark-console-webapp/src/hooks/web/useLockPage.ts
  streampark-console/streampark-console-webapp/src/locales/lang/en/flink/project.ts
  streampark-console/streampark-console-webapp/src/locales/lang/zh-CN/flink/project.ts
  streampark-console/streampark-console-webapp/src/utils/props.ts
  streampark-console/streampark-console-webapp/src/views/flink/project/Add.vue
  streampark-console/streampark-console-webapp/src/views/flink/project/Edit.vue
  streampark-console/streampark-console-webapp/src/views/flink/project/components/RepositoryGroup.tsx
  streampark-console/streampark-console-webapp/src/views/flink/project/useProject.tsx
Labels: BUILD, WEB UI, BACKEND

#3453 fix config streampark.flink-k8s.ingress.class default value
  streampark-common/src/main/scala/org/apache/streampark/common/conf/K8sFlinkConfig.scala
Labels: BACKEND

#3455 fix Application entity not set setModifyTime on create on update
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/application/impl/ApplicationManageServiceImpl.java
Labels: BACKEND

#3450 [Improve] git clone connect type improvement
  streampark-console/streampark-console-service/src/main/assembly/script/data/mysql-data.sql
  streampark-console/streampark-console-service/src/main/assembly/script/data/pgsql-data.sql
  streampark-console/streampark-console-service/src/main/assembly/script/schema/mysql-schema.sql
  streampark-console/streampark-console-service/src/main/assembly/script/schema/pgsql-schema.sql
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/base/util/GitUtils.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/entity/Project.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ProjectServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/task/ProjectBuildTask.java
  streampark-console/streampark-console-service/src/main/resources/db/data-h2.sql
  streampark-console/streampark-console-service/src/main/resources/db/schema-h2.sql
  streampark-console/streampark-console-service/src/main/resources/mapper/core/ProjectMapper.xml
  streampark-console/streampark-console-service/src/test/java/org/apache/streampark/console/core/entity/ProjectTest.java
  streampark-console/streampark-console-webapp/src/components/Application/src/AppDarkModeToggle.vue
  streampark-console/streampark-console-webapp/src/components/ContextMenu/src/ContextMenu.vue
  streampark-console/streampark-console-webapp/src/components/Form/src/BasicForm.vue
  streampark-console/streampark-console-webapp/src/components/Form/src/components/FormItem.vue
  streampark-console/streampark-console-webapp/src/components/Modal/src/components/ModalWrapper.vue
  streampark-console/streampark-console-webapp/src/components/Page/src/PageFooter.vue
  streampark-console/streampark-console-webapp/src/components/Table/src/components/HeaderCell.vue
  streampark-console/streampark-console-webapp/src/enums/projectEnum.ts
  streampark-console/streampark-console-webapp/src/hooks/setting/useMenuSetting.ts
  streampark-console/streampark-console-webapp/src/hooks/web/useLockPage.ts
  streampark-console/streampark-console-webapp/src/locales/lang/en/flink/project.ts
  streampark-console/streampark-console-webapp/src/locales/lang/zh-CN/flink/project.ts
  streampark-console/streampark-console-webapp/src/utils/props.ts
  streampark-console/streampark-console-webapp/src/views/base/error-log/data.tsx
  streampark-console/streampark-console-webapp/src/views/flink/app/hooks/useCreateAndEditSchema.ts
  streampark-console/streampark-console-webapp/src/views/resource/project/Add.vue
  streampark-console/streampark-console-webapp/src/views/resource/project/Edit.vue
  streampark-console/streampark-console-webapp/src/views/resource/project/components/RepositoryGroup.tsx
  streampark-console/streampark-console-webapp/src/views/resource/project/useProject.tsx
Labels: BUILD, WEB UI, BACKEND

#3458 [Bug] k8s job state monitor bug fixed
  streampark-common/src/main/scala/org/apache/streampark/common/util/Utils.scala
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/ApplicationService.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ApplicationServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/task/FlinkK8sWatcherWrapper.java
  streampark-flink/streampark-flink-kubernetes/src/main/scala/org/apache/streampark/flink/kubernetes/KubernetesRetriever.scala
  streampark-flink/streampark-flink-kubernetes/src/main/scala/org/apache/streampark/flink/kubernetes/helper/KubernetesDeploymentHelper.scala
  streampark-flink/streampark-flink-kubernetes/src/main/scala/org/apache/streampark/flink/kubernetes/model/TrackId.scala
  streampark-flink/streampark-flink-kubernetes/src/main/scala/org/apache/streampark/flink/kubernetes/watcher/FlinkJobStatusWatcher.scala
Labels: BACKEND, FLINK, KUBERNETES

#3457 [fix] update sql in xml for cross-compatibility with mysql, h2, and pgsql in like concat expressions
  streampark-console/streampark-console-service/src/main/resources/mapper/core/ApplicationMapper.xml
  streampark-console/streampark-console-service/src/main/resources/mapper/core/ProjectMapper.xml
  streampark-console/streampark-console-service/src/main/resources/mapper/core/ResourceMapper.xml
  streampark-console/streampark-console-service/src/main/resources/mapper/core/VariableMapper.xml
  streampark-console/streampark-console-service/src/main/resources/mapper/core/YarnQueueMapper.xml
  streampark-console/streampark-console-service/src/main/resources/mapper/system/MemberMapper.xml
  streampark-console/streampark-console-service/src/main/resources/mapper/system/RoleMapper.xml
  streampark-console/streampark-console-service/src/main/resources/mapper/system/TeamMapper.xml
  streampark-console/streampark-console-service/src/main/resources/mapper/system/UserMapper.xml
Labels: BACKEND

#3462 [Bug] jdbc like bug fixed
  streampark-console/streampark-console-service/src/main/resources/mapper/core/ApplicationMapper.xml
  streampark-console/streampark-console-service/src/main/resources/mapper/core/ProjectMapper.xml
  streampark-console/streampark-console-service/src/main/resources/mapper/core/VariableMapper.xml
  streampark-console/streampark-console-service/src/main/resources/mapper/core/YarnQueueMapper.xml
  streampark-console/streampark-console-service/src/main/resources/mapper/system/MemberMapper.xml
  streampark-console/streampark-console-service/src/main/resources/mapper/system/RoleMapper.xml
  streampark-console/streampark-console-service/src/main/resources/mapper/system/TeamMapper.xml
  streampark-console/streampark-console-service/src/main/resources/mapper/system/UserMapper.xml
Labels: BACKEND

#3461 [Improve]Improve flink env check method
  streampark-common/src/main/java/org/apache/streampark/common/enums/FlinkEnvStatus.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/controller/FlinkEnvController.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/FlinkEnvService.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/FlinkEnvServiceImpl.java
  streampark-console/streampark-console-webapp/src/enums/flinkEnum.ts
  streampark-console/streampark-console-webapp/src/locales/lang/en/setting/flinkHome.ts
  streampark-console/streampark-console-webapp/src/locales/lang/zh-CN/setting/flinkHome.ts
  streampark-console/streampark-console-webapp/src/views/flink/home/components/Modal.vue
Labels: WEB UI, BACKEND

#3469 [Improve] flink env check improvement
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/controller/FlinkEnvController.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/enums/FlinkEnvCheckEnum.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/FlinkEnvService.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/FlinkEnvServiceImpl.java
  streampark-console/streampark-console-webapp/src/components/Application/src/AppDarkModeToggle.vue
  streampark-console/streampark-console-webapp/src/components/ContextMenu/src/ContextMenu.vue
  streampark-console/streampark-console-webapp/src/components/Form/src/BasicForm.vue
  streampark-console/streampark-console-webapp/src/components/Form/src/components/FormItem.vue
  streampark-console/streampark-console-webapp/src/components/Modal/src/components/ModalWrapper.vue
  streampark-console/streampark-console-webapp/src/components/Page/src/PageFooter.vue
  streampark-console/streampark-console-webapp/src/components/Table/src/components/HeaderCell.vue
  streampark-console/streampark-console-webapp/src/enums/flinkEnum.ts
  streampark-console/streampark-console-webapp/src/hooks/setting/useMenuSetting.ts
  streampark-console/streampark-console-webapp/src/hooks/web/useLockPage.ts
  streampark-console/streampark-console-webapp/src/locales/lang/en/setting/flinkHome.ts
  streampark-console/streampark-console-webapp/src/locales/lang/zh-CN/setting/flinkHome.ts
  streampark-console/streampark-console-webapp/src/utils/props.ts
  streampark-console/streampark-console-webapp/src/views/base/error-log/data.tsx
  streampark-console/streampark-console-webapp/src/views/flink/home/components/Modal.vue
Labels: WEB UI, BACKEND

#3473 [Bug] When calling Application using an interface, it is not possible to recover from the latest CheckPoint or SavePoint
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/application/impl/ApplicationActionServiceImpl.java
Labels: BACKEND

#3474 [Improve] issus-3471 bug fixed
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ApplicationServiceImpl.java
Labels: BACKEND

#3475 [Improve][Doc] Add Code Submission Guide link
  README.md
Labels: DOCS

#3476 [Improve] flink k8s session cluster shutdown bug fixed
  .dlc.json
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/controller/FlinkClusterController.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/FlinkClusterService.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ApplicationServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/FlinkClusterServiceImpl.java
  streampark-flink/streampark-flink-client/streampark-flink-client-api/src/main/scala/org/apache/streampark/flink/client/FlinkClient.scala
  streampark-flink/streampark-flink-client/streampark-flink-client-api/src/main/scala/org/apache/streampark/flink/client/bean/DeployRequest.scala
  streampark-flink/streampark-flink-client/streampark-flink-client-api/src/main/scala/org/apache/streampark/flink/client/bean/ShutDownRequest.scala
  streampark-flink/streampark-flink-client/streampark-flink-client-core/src/main/scala/org/apache/streampark/flink/client/FlinkClientHandler.scala
  streampark-flink/streampark-flink-client/streampark-flink-client-core/src/main/scala/org/apache/streampark/flink/client/impl/KubernetesNativeApplicationClient.scala
  streampark-flink/streampark-flink-client/streampark-flink-client-core/src/main/scala/org/apache/streampark/flink/client/impl/KubernetesNativeSessionClient.scala
  streampark-flink/streampark-flink-client/streampark-flink-client-core/src/main/scala/org/apache/streampark/flink/client/impl/YarnSessionClient.scala
Labels: BACKEND, FLINK

#3479 [Hotfix] fix bug： can`t upload a jar package to hdfs on streampark application type
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/entity/Application.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/AppBuildPipeServiceImpl.java
Labels: BACKEND

#3484 [Improve] custom_code build pipeline bug fixed.
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/AppBuildPipeServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ApplicationServiceImpl.java
  streampark-console/streampark-console-webapp/package.json
  streampark-console/streampark-console-webapp/src/views/base/login/Login.vue
  streampark-flink/streampark-flink-kubernetes/src/main/scala/org/apache/streampark/flink/kubernetes/DefaultFlinkK8sWatcher.scala
  streampark-flink/streampark-flink-kubernetes/src/main/scala/org/apache/streampark/flink/kubernetes/watcher/FlinkJobStatusWatcher.scala
Labels: WEB UI, BACKEND, FLINK, KUBERNETES

#3482 [Fix] fix_t_flink_app Missing "hadoop_user" field
  streampark-console/streampark-console-service/src/main/assembly/script/data/mysql-data.sql
  streampark-console/streampark-console-service/src/main/assembly/script/data/pgsql-data.sql
  streampark-console/streampark-console-service/src/main/assembly/script/schema/mysql-schema.sql
  streampark-console/streampark-console-service/src/main/assembly/script/schema/pgsql-schema.sql
Labels: BUILD, BACKEND

#3485 [Improve] flink cluster on k8s session shutdown bug fixed
  streampark-flink/streampark-flink-client/streampark-flink-client-api/src/main/scala/org/apache/streampark/flink/client/bean/SubmitRequest.scala
  streampark-flink/streampark-flink-client/streampark-flink-client-core/src/main/scala/org/apache/streampark/flink/client/impl/KubernetesNativeApplicationClient.scala
  streampark-flink/streampark-flink-client/streampark-flink-client-core/src/main/scala/org/apache/streampark/flink/client/impl/KubernetesNativeSessionClient.scala
  streampark-flink/streampark-flink-client/streampark-flink-client-core/src/main/scala/org/apache/streampark/flink/client/impl/YarnApplicationClient.scala
  streampark-flink/streampark-flink-client/streampark-flink-client-core/src/main/scala/org/apache/streampark/flink/client/impl/YarnPerJobClient.scala
  streampark-flink/streampark-flink-client/streampark-flink-client-core/src/main/scala/org/apache/streampark/flink/client/impl/YarnSessionClient.scala
  streampark-flink/streampark-flink-client/streampark-flink-client-core/src/main/scala/org/apache/streampark/flink/client/tool/FlinkSessionClientHelper.scala
  streampark-flink/streampark-flink-client/streampark-flink-client-core/src/main/scala/org/apache/streampark/flink/client/trait/FlinkClientTrait.scala
  streampark-flink/streampark-flink-client/streampark-flink-client-core/src/main/scala/org/apache/streampark/flink/client/trait/KubernetesNativeClientTrait.scala
  streampark-flink/streampark-flink-client/streampark-flink-client-core/src/main/scala/org/apache/streampark/flink/client/trait/YarnClientTrait.scala
  streampark-flink/streampark-flink-kubernetes/src/main/scala/org/apache/streampark/flink/kubernetes/helper/KubernetesDeploymentHelper.scala
Labels: FLINK, KUBERNETES

#3486 [Improve] add quickstart-with-docker to README
  README.md
  deploy/docker/README.md
  docker/.env
  docker/Dockerfile
  docker/README.md
  docker/docker-compose.yaml
  helm/README.md
  helm/streampark/.helmignore
  helm/streampark/Chart.yaml
  helm/streampark/conf/streampark-console-config/ValidationMessages.properties
  helm/streampark/conf/streampark-console-config/application-h2.yml
  helm/streampark/conf/streampark-console-config/application-mysql.yml
  helm/streampark/conf/streampark-console-config/application-pgsql.yml
  helm/streampark/conf/streampark-console-config/application-sso.yml
  helm/streampark/conf/streampark-console-config/application.yml
  helm/streampark/conf/streampark-console-config/kerberos.yml
  helm/streampark/conf/streampark-console-config/logback-spring.xml
  helm/streampark/conf/streampark-console-config/spy.properties
  helm/streampark/templates/NOTES.txt
  helm/streampark/templates/_helpers.tpl
  helm/streampark/templates/configmap.yaml
  helm/streampark/templates/ingress.yaml
  helm/streampark/templates/rbac.yaml
  helm/streampark/templates/service.yaml
  helm/streampark/templates/serviceaccount.yaml
  helm/streampark/templates/streampark.yml
  helm/streampark/values.yaml
  pom.xml
  streampark-console/streampark-console-service/src/main/assembly/plugins/.gitkeep
  streampark-console/streampark-console-service/src/main/assembly/plugins/Dockerfile
Labels: BUILD, DOCKER, DOCS, BACKEND

#3459 [ISSUE-3433][Fix] Mapper/core/ApplicationMapper.xml ERROR: operator does not exist: boolean = integer
  streampark-console/streampark-console-service/src/main/resources/mapper/core/ApplicationMapper.xml
Labels: BACKEND

#3464 [Improve] Cluster Connection Check
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/FlinkClusterServiceImpl.java
Labels: BACKEND

#3489 [Bug] deploy job on k8s session mode get job state bug fixed
  streampark-common/src/main/scala/org/apache/streampark/common/conf/ConfigConst.scala
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/entity/Application.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/ApplicationService.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/AppBuildPipeServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ApplicationServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/FlinkClusterServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/YarnQueueServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/task/FlinkK8sWatcherWrapper.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/task/FlinkRESTAPIWatcher.java
  streampark-console/streampark-console-webapp/src/api/flink/app/app.type.ts
  streampark-console/streampark-console-webapp/src/components/Application/src/AppDarkModeToggle.vue
  streampark-console/streampark-console-webapp/src/components/ContextMenu/src/ContextMenu.vue
  streampark-console/streampark-console-webapp/src/components/Form/src/BasicForm.vue
  streampark-console/streampark-console-webapp/src/components/Page/src/PageFooter.vue
  streampark-console/streampark-console-webapp/src/components/Table/src/components/HeaderCell.vue
  streampark-console/streampark-console-webapp/src/hooks/web/useLockPage.ts
  streampark-console/streampark-console-webapp/src/locales/lang/en/flink/app.ts
  streampark-console/streampark-console-webapp/src/locales/lang/zh-CN/flink/app.ts
  streampark-console/streampark-console-webapp/src/locales/lang/zh-CN/setting/flinkCluster.ts
  streampark-console/streampark-console-webapp/src/utils/props.ts
  streampark-console/streampark-console-webapp/src/views/base/login/Login.vue
  streampark-console/streampark-console-webapp/src/views/flink/app/EditFlink.vue
  streampark-console/streampark-console-webapp/src/views/flink/app/EditStreamPark.vue
  streampark-console/streampark-console-webapp/src/views/flink/app/hooks/useCreateAndEditSchema.ts
  streampark-console/streampark-console-webapp/src/views/flink/app/hooks/useFlinkRender.tsx
  streampark-console/streampark-console-webapp/src/views/flink/app/utils/index.ts
  streampark-flink/streampark-flink-client/streampark-flink-client-api/src/main/scala/org/apache/streampark/flink/client/bean/CancelRequest.scala
  streampark-flink/streampark-flink-client/streampark-flink-client-api/src/main/scala/org/apache/streampark/flink/client/bean/DeployRequest.scala
  streampark-flink/streampark-flink-client/streampark-flink-client-api/src/main/scala/org/apache/streampark/flink/client/bean/DeployResponse.scala
  streampark-flink/streampark-flink-client/streampark-flink-client-api/src/main/scala/org/apache/streampark/flink/client/bean/ShutDownResponse.scala
  streampark-flink/streampark-flink-client/streampark-flink-client-api/src/main/scala/org/apache/streampark/flink/client/bean/TriggerSavepointRequest.scala
  streampark-flink/streampark-flink-client/streampark-flink-client-core/src/main/scala/org/apache/streampark/flink/client/impl/KubernetesNativeSessionClient.scala
  streampark-flink/streampark-flink-client/streampark-flink-client-core/src/main/scala/org/apache/streampark/flink/client/impl/YarnSessionClient.scala
  streampark-flink/streampark-flink-client/streampark-flink-client-core/src/main/scala/org/apache/streampark/flink/client/trait/FlinkClientTrait.scala
  streampark-flink/streampark-flink-kubernetes/src/main/scala/org/apache/streampark/flink/kubernetes/FlinkK8sWatchController.scala
  streampark-flink/streampark-flink-kubernetes/src/main/scala/org/apache/streampark/flink/kubernetes/model/ClusterKey.scala
  streampark-flink/streampark-flink-kubernetes/src/main/scala/org/apache/streampark/flink/kubernetes/model/JobStatusCV.scala
  streampark-flink/streampark-flink-kubernetes/src/main/scala/org/apache/streampark/flink/kubernetes/model/K8sEventKey.scala
  streampark-flink/streampark-flink-kubernetes/src/main/scala/org/apache/streampark/flink/kubernetes/model/TrackId.scala
  streampark-flink/streampark-flink-kubernetes/src/main/scala/org/apache/streampark/flink/kubernetes/watcher/FlinkJobStatusWatcher.scala
  streampark-flink/streampark-flink-packer/src/main/scala/org/apache/streampark/flink/packer/pipeline/impl/FlinkK8sApplicationBuildPipeline.scala
Labels: WEB UI, BACKEND, FLINK, KUBERNETES

#3498 [Improve]: App view table column add drag and drop, tag width adaptive
  streampark-console/streampark-console-webapp/src/design/ant/index.less
  streampark-console/streampark-console-webapp/src/views/flink/app/View.vue
  streampark-console/streampark-console-webapp/src/views/flink/app/components/State.tsx
  streampark-console/streampark-console-webapp/src/views/flink/app/data/index.ts
  streampark-console/streampark-console-webapp/src/views/flink/app/hooks/useAppTableColumns.ts
Labels: WEB UI

#3499 [Improve] Repo metadata
  .asf.yaml
  README.md
Labels: INFRA, DOCS

#3505 [ISSUE-3503] build Docker Image bug fixed
  .github/workflows/docker-push.yml
Labels: INFRA

#3506 [ISSUE-3451] pgsql "like" syntax bug fixed.
  streampark-console/streampark-console-service/src/main/resources/mapper/core/ApplicationMapper.xml
  streampark-console/streampark-console-service/src/main/resources/mapper/core/ProjectMapper.xml
  streampark-console/streampark-console-service/src/main/resources/mapper/core/ResourceMapper.xml
  streampark-console/streampark-console-service/src/main/resources/mapper/core/VariableMapper.xml
  streampark-console/streampark-console-service/src/main/resources/mapper/core/YarnQueueMapper.xml
  streampark-console/streampark-console-service/src/main/resources/mapper/system/MemberMapper.xml
  streampark-console/streampark-console-service/src/main/resources/mapper/system/RoleMapper.xml
  streampark-console/streampark-console-service/src/main/resources/mapper/system/TeamMapper.xml
  streampark-console/streampark-console-service/src/main/resources/mapper/system/UserMapper.xml
Labels: BACKEND

#3488 [ISSUE-3472][Improve] Improve streampark-console module Controller invoke service
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/controller/AlertController.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/controller/ApplicationController.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/controller/ConfigController.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/controller/FlinkClusterController.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/controller/FlinkSqlController.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/controller/ResourceController.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/mapper/ApplicationMapper.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/ApplicationConfigService.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/FlinkClusterService.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/FlinkSqlService.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/ResourceService.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/alert/AlertConfigService.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/alert/impl/AlertConfigServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/application/ApplicationActionService.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/application/ApplicationInfoService.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/application/ApplicationManageService.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/application/impl/ApplicationActionServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/application/impl/ApplicationInfoServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/application/impl/ApplicationManageServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ApplicationConfigServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/FlinkClusterServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/FlinkSqlServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ResourceServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/controller/MemberController.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/service/MemberService.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/service/impl/MemberServiceImpl.java
  streampark-console/streampark-console-service/src/main/resources/mapper/core/ApplicationMapper.xml
  streampark-console/streampark-console-service/src/test/java/org/apache/streampark/console/core/service/ApplicationManageServiceITest.java
Labels: BACKEND

#3511 add IngressClassName
  streampark-flink/streampark-flink-kubernetes/src/main/scala/org/apache/streampark/flink/kubernetes/ingress/IngressStrategyV1.scala
  streampark-flink/streampark-flink-kubernetes/src/main/scala/org/apache/streampark/flink/kubernetes/ingress/IngressStrategyV1beta1.scala
Labels: FLINK, KUBERNETES

#3493 [Feature] Trigger method add savepoint save
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/SavePointServiceImpl.java
Labels: BACKEND

#3509 [ISSUE-3070][Improve] Improve streampark-console module base on [3.7 Code Comments Rule]
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/base/config/AlertRestTemplateConfig.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/base/config/AsyncExecutorPoolConfig.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/base/config/OpenapiConfig.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/base/config/P6spySqlFormatConfig.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/base/config/WebMvcConfig.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/base/domain/ApiDocConstant.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/base/domain/Constant.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/base/exception/ApplicationException.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/base/exception/IllegalFileTypeException.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/base/handler/GlobalExceptionHandler.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/base/interceptor/UploadFileTypeInterceptor.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/base/util/GitUtils.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/base/util/JacksonUtils.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/annotation/PermissionAction.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/enums/AccessTokenStateEnum.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/enums/AppExistsStateEnum.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/enums/BuildStateEnum.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/enums/CheckPointStatusEnum.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/enums/CheckPointTypeEnum.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/enums/FailoverStrategyEnum.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/enums/FlinkAppStateEnum.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/enums/GatewayTypeEnum.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/enums/GitAuthorizedErrorEnum.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/enums/GitCredentialEnum.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/enums/NoticeTypeEnum.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/enums/OperationEnum.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/enums/OptionStateEnum.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/enums/ReleaseStateEnum.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/AppBuildPipeService.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/ApplicationLogService.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/CommonService.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/ExternalLinkService.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/FlinkClusterService.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/FlinkGateWayService.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/FlinkSqlService.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/MessageService.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/ProjectService.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/SettingService.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/YarnQueueService.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/alert/AlertConfigService.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/AppBuildPipeServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/authentication/JWTUtil.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/controller/RoleController.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/service/AccessTokenService.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/service/MemberService.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/service/MenuService.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/service/RoleMenuService.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/service/RoleService.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/service/TeamService.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/service/UserService.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/service/impl/MenuServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/service/impl/RoleMenuServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/service/impl/RoleServiceImpl.java
Labels: BACKEND

#3515 [improvement-3512][Flink-Doris-connector] replace `lable` to `label`
  streampark-flink/streampark-flink-connector/streampark-flink-connector-doris/src/main/java/org/apache/streampark/flink/connector/doris/internal/DorisSinkWriter.java
  streampark-flink/streampark-flink-connector/streampark-flink-connector-doris/src/main/scala/org/apache/streampark/connector/doris/conf/DorisConfig.scala
  streampark-flink/streampark-flink-connector/streampark-flink-connector-doris/src/main/scala/org/apache/streampark/connector/doris/conf/DorisSinkConfigOption.scala
Labels: FLINK

#3514 [Bug] Ingress class param bug fixed
  streampark-flink/streampark-flink-kubernetes/src/main/scala/org/apache/streampark/flink/kubernetes/ingress/IngressController.scala
  streampark-flink/streampark-flink-kubernetes/src/main/scala/org/apache/streampark/flink/kubernetes/ingress/IngressStrategy.scala
  streampark-flink/streampark-flink-kubernetes/src/main/scala/org/apache/streampark/flink/kubernetes/ingress/IngressStrategyV1.scala
  streampark-flink/streampark-flink-kubernetes/src/main/scala/org/apache/streampark/flink/kubernetes/ingress/IngressStrategyV1beta1.scala
Labels: FLINK, KUBERNETES

#3516 [Improve]doris-connector typo improvement
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ApplicationServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/task/FlinkK8sChangeEventListener.java
  streampark-console/streampark-console-webapp/src/locales/lang/en/flink/app.ts
  streampark-console/streampark-console-webapp/src/locales/lang/zh-CN/flink/app.ts
  streampark-console/streampark-console-webapp/src/views/flink/app/components/AppDetail/DetailTab.vue
  streampark-console/streampark-console-webapp/src/views/flink/app/components/AppView/StartApplicationModal.vue
  streampark-flink/streampark-flink-connector/streampark-flink-connector-doris/src/main/java/org/apache/streampark/flink/connector/doris/internal/DorisSinkWriter.java
  streampark-flink/streampark-flink-connector/streampark-flink-connector-doris/src/main/scala/org/apache/streampark/connector/doris/conf/DorisConfig.scala
  streampark-flink/streampark-flink-connector/streampark-flink-connector-doris/src/main/scala/org/apache/streampark/connector/doris/conf/DorisSinkConfigOption.scala
  streampark-flink/streampark-flink-kubernetes/src/main/scala/org/apache/streampark/flink/kubernetes/watcher/FlinkMetricsWatcher.scala
Labels: WEB UI, BACKEND, FLINK, KUBERNETES

#3518 [Improve] Menu icon improvement
  streampark-console/streampark-console-service/src/main/assembly/script/data/mysql-data.sql
  streampark-console/streampark-console-service/src/main/assembly/script/data/pgsql-data.sql
  streampark-console/streampark-console-service/src/main/assembly/script/upgrade/mysql/2.1.3.sql
  streampark-console/streampark-console-service/src/main/assembly/script/upgrade/pgsql/2.1.3.sql
  streampark-console/streampark-console-service/src/main/resources/db/data-h2.sql
  streampark-console/streampark-console-webapp/src/assets/icons/app.svg
  streampark-console/streampark-console-webapp/src/assets/icons/auth.svg
  streampark-console/streampark-console-webapp/src/assets/icons/code.svg
  streampark-console/streampark-console-webapp/src/assets/icons/connector.svg
  streampark-console/streampark-console-webapp/src/assets/icons/copy.svg
  streampark-console/streampark-console-webapp/src/assets/icons/deploy.svg
  streampark-console/streampark-console-webapp/src/assets/icons/docker.svg
  streampark-console/streampark-console-webapp/src/assets/icons/edit.svg
  streampark-console/streampark-console-webapp/src/assets/icons/flame.svg
  streampark-console/streampark-console-webapp/src/assets/icons/flink2.svg
  streampark-console/streampark-console-webapp/src/assets/icons/flink3.svg
  streampark-console/streampark-console-webapp/src/assets/icons/flinksql.svg
  streampark-console/streampark-console-webapp/src/assets/icons/format.svg
  streampark-console/streampark-console-webapp/src/assets/icons/fql.svg
  streampark-console/streampark-console-webapp/src/assets/icons/fx.svg
  streampark-console/streampark-console-webapp/src/assets/icons/github.svg
  streampark-console/streampark-console-webapp/src/assets/icons/group.svg
  streampark-console/streampark-console-webapp/src/assets/icons/host.svg
  streampark-console/streampark-console-webapp/src/assets/icons/jar.svg
  streampark-console/streampark-console-webapp/src/assets/icons/keys.svg
  streampark-console/streampark-console-webapp/src/assets/icons/mail.svg
  streampark-console/streampark-console-webapp/src/assets/icons/management.svg
  streampark-console/streampark-console-webapp/src/assets/icons/mapping.svg
  streampark-console/streampark-console-webapp/src/assets/icons/mvnpass.svg
  streampark-console/streampark-console-webapp/src/assets/icons/net.svg
  streampark-console/streampark-console-webapp/src/assets/icons/password.svg
  streampark-console/streampark-console-webapp/src/assets/icons/pause.svg
  streampark-console/streampark-console-webapp/src/assets/icons/play.svg
  streampark-console/streampark-console-webapp/src/assets/icons/plus.svg
  streampark-console/streampark-console-webapp/src/assets/icons/port.svg
  streampark-console/streampark-console-webapp/src/assets/icons/py.svg
  streampark-console/streampark-console-webapp/src/assets/icons/question.svg
  streampark-console/streampark-console-webapp/src/assets/icons/remove.svg
  streampark-console/streampark-console-webapp/src/assets/icons/resetpass.svg
  streampark-console/streampark-console-webapp/src/assets/icons/resource.svg
  streampark-console/streampark-console-webapp/src/assets/icons/rollback.svg
  streampark-console/streampark-console-webapp/src/assets/icons/see.svg
  streampark-console/streampark-console-webapp/src/assets/icons/settings.svg
  streampark-console/streampark-console-webapp/src/assets/icons/shutdown.svg
  streampark-console/streampark-console-webapp/src/assets/icons/sms.svg
  streampark-console/streampark-console-webapp/src/assets/icons/spark.svg
  streampark-console/streampark-console-webapp/src/assets/icons/ssl.svg
  streampark-console/streampark-console-webapp/src/assets/icons/stream.svg
  streampark-console/streampark-console-webapp/src/assets/icons/swap.svg
  streampark-console/streampark-console-webapp/src/assets/icons/theme.svg
  streampark-console/streampark-console-webapp/src/assets/icons/threshold.svg
  streampark-console/streampark-console-webapp/src/assets/icons/thunderbolt.svg
  streampark-console/streampark-console-webapp/src/assets/icons/user.svg
  streampark-console/streampark-console-webapp/src/assets/icons/variable.svg
  streampark-console/streampark-console-webapp/src/assets/icons/workspace.svg
  streampark-console/streampark-console-webapp/src/components/SimpleMenu/src/SimpleMenuTag.vue
  streampark-console/streampark-console-webapp/src/components/SimpleMenu/src/SimpleSubMenu.vue
  streampark-console/streampark-console-webapp/src/layouts/default/header/index.vue
Labels: BUILD, WEB UI, BACKEND

#3523 get cluster detail of flink session on k8s with ingress url bug fix
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/controller/FlinkClusterController.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/FlinkClusterService.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/FlinkClusterServiceImpl.java
Labels: BACKEND

#3525 [Improve] table resize icon
  streampark-console/streampark-console-webapp/src/components/Table/src/BasicTable.vue
  streampark-console/streampark-console-webapp/src/views/flink/app/View.vue
  streampark-console/streampark-console-webapp/src/views/flink/app/components/AppResize.vue
  streampark-console/streampark-console-webapp/src/views/flink/app/hooks/useAppTableColumns.ts
Labels: WEB UI

#3526 [Improve] App view table resize icon
  streampark-console/streampark-console-webapp/src/components/Table/src/BasicTable.vue
  streampark-console/streampark-console-webapp/src/views/flink/app/View.vue
  streampark-console/streampark-console-webapp/src/views/flink/app/components/AppResize.vue
  streampark-console/streampark-console-webapp/src/views/flink/app/hooks/useAppTableColumns.ts
Labels: WEB UI
