Repository apache/streampark, pull requests merged in 2024-07, with the labels that each got.

#3824 [ISSUE-3811][Feature] Introduce role management e2e test
  .github/workflows/e2e.yml
  streampark-e2e/streampark-e2e-case/src/test/java/org/apache/streampark/e2e/cases/RoleManagementTest.java
  streampark-e2e/streampark-e2e-case/src/test/java/org/apache/streampark/e2e/pages/system/RoleManagementPage.java
  streampark-e2e/streampark-e2e-case/src/test/java/org/apache/streampark/e2e/pages/system/SystemPage.java
Labels: INFRA

#3835 [ISSUE-3832][Feature] Introduce variable management e2e test
  .github/workflows/e2e.yml
  streampark-e2e/streampark-e2e-case/src/test/java/org/apache/streampark/e2e/cases/resource/VariableManagementTest.java
  streampark-e2e/streampark-e2e-case/src/test/java/org/apache/streampark/e2e/pages/common/NavBarPage.java
  streampark-e2e/streampark-e2e-case/src/test/java/org/apache/streampark/e2e/pages/resource/ResourcePage.java
  streampark-e2e/streampark-e2e-case/src/test/java/org/apache/streampark/e2e/pages/resource/VariableManagementPage.java
Labels: INFRA

#3838 [Improve] submit flink job default file.encoding parameter improvement
  streampark-common/src/main/java/org/apache/streampark/common/enums/FlinkDevelopmentMode.java
  streampark-flink/streampark-flink-client/streampark-flink-client-api/src/main/scala/org/apache/streampark/flink/client/bean/SubmitRequest.scala
  streampark-flink/streampark-flink-client/streampark-flink-client-core/src/main/scala/org/apache/streampark/flink/client/trait/FlinkClientTrait.scala
Labels: BACKEND, FLINK

#3829 [ISSUE-3813][Feature] Introduce member management e2e test
  .github/workflows/e2e.yml
  streampark-e2e/streampark-e2e-case/src/test/java/org/apache/streampark/e2e/cases/MemberManagementTest.java
  streampark-e2e/streampark-e2e-case/src/test/java/org/apache/streampark/e2e/pages/system/MemberManagementPage.java
  streampark-e2e/streampark-e2e-case/src/test/java/org/apache/streampark/e2e/pages/system/SystemPage.java
Labels: INFRA

#3841 [Improve] submit flink job error message improvement
  helm/streampark/conf/config.yaml
  helm/streampark/conf/logback-spring.xml
  helm/streampark/templates/configmap.yaml
  streampark-console/streampark-console-service/src/main/assembly/bin/streampark.sh
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/base/config/SpringProperties.java
  streampark-flink/streampark-flink-client/streampark-flink-client-api/src/main/scala/org/apache/streampark/flink/client/bean/SubmitRequest.scala
  streampark-flink/streampark-flink-client/streampark-flink-client-core/src/main/scala/org/apache/streampark/flink/client/impl/KubernetesNativeApplicationClient.scala
  streampark-flink/streampark-flink-client/streampark-flink-client-core/src/main/scala/org/apache/streampark/flink/client/impl/LocalClient.scala
  streampark-flink/streampark-flink-client/streampark-flink-client-core/src/main/scala/org/apache/streampark/flink/client/impl/YarnApplicationClient.scala
  streampark-flink/streampark-flink-client/streampark-flink-client-core/src/main/scala/org/apache/streampark/flink/client/impl/YarnPerJobClient.scala
  streampark-flink/streampark-flink-client/streampark-flink-client-core/src/main/scala/org/apache/streampark/flink/client/impl/YarnSessionClient.scala
  streampark-flink/streampark-flink-client/streampark-flink-client-core/src/main/scala/org/apache/streampark/flink/client/trait/FlinkClientTrait.scala
Labels: BUILD, BACKEND, FLINK

#3826 [ISSUE-3825][Improve] `/system/role` page miss description field value
  streampark-console/streampark-console-webapp/src/api/system/model/roleModel.ts
  streampark-console/streampark-console-webapp/src/views/system/role/components/RoleDrawer.vue
  streampark-console/streampark-console-webapp/src/views/system/role/components/RoleInfo.vue
  streampark-console/streampark-console-webapp/src/views/system/role/role.data.ts
  streampark-e2e/streampark-e2e-case/src/test/java/org/apache/streampark/e2e/cases/RoleManagementTest.java
  streampark-e2e/streampark-e2e-case/src/test/java/org/apache/streampark/e2e/pages/system/RoleManagementPage.java
Labels: WEB UI

#3847 [Fix-3681] DockerConfig setting error
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/bean/DockerConfig.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/controller/SettingController.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/mapper/SettingMapper.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/SettingServiceImpl.java
  streampark-console/streampark-console-service/src/main/resources/mapper/core/SettingMapper.xml
  streampark-console/streampark-console-service/src/test/java/org/apache/streampark/console/core/service/SettingServiceTest.java
Labels: BACKEND

#3850 [ISSUE-3849][Improve] Resource Type value should be consistency
  streampark-console/streampark-console-webapp/src/views/resource/upload/View.vue
Labels: WEB UI

#3845 [ISSUE-3830][Feature] Introduce upload management e2e test
  .github/workflows/e2e.yml
  streampark-e2e/streampark-e2e-case/src/test/java/org/apache/streampark/e2e/cases/UploadManagementTest.java
  streampark-e2e/streampark-e2e-case/src/test/java/org/apache/streampark/e2e/cases/VariableManagementTest.java
  streampark-e2e/streampark-e2e-case/src/test/java/org/apache/streampark/e2e/pages/resource/ResourcePage.java
  streampark-e2e/streampark-e2e-case/src/test/java/org/apache/streampark/e2e/pages/resource/UploadsPage.java
  streampark-e2e/streampark-e2e-case/src/test/java/org/apache/streampark/e2e/pages/resource/VariablesPage.java
Labels: INFRA

#3858 [Cherry-Pick-3847] DockerConfig setting error
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/bean/DockerConfig.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/controller/SettingController.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/mapper/SettingMapper.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/SettingService.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/SettingServiceImpl.java
  streampark-console/streampark-console-service/src/main/resources/mapper/core/SettingMapper.xml
  streampark-console/streampark-console-service/src/test/java/org/apache/streampark/console/core/service/SettingServiceTest.java
Labels: BACKEND

#3859 [Chore] Improve owasp dependency check
  .github/workflows/owasp-dependency-check.yaml
  pom.xml
Labels: BUILD, INFRA

#3860 [Improve] flink on yarn e2e testcase
  .github/workflows/e2e.yml
  streampark-e2e/streampark-e2e-case/src/test/java/org/apache/streampark/e2e/cases/FlinkSQL116OnYarnTest.java
  streampark-e2e/streampark-e2e-case/src/test/java/org/apache/streampark/e2e/cases/FlinkSQL117OnYarnTest.java
  streampark-e2e/streampark-e2e-case/src/test/java/org/apache/streampark/e2e/cases/FlinkSQL118OnYarnTest.java
  streampark-flink/streampark-flink-proxy/src/main/scala/org/apache/streampark/flink/proxy/ChildFirstClassLoader.scala
  streampark-flink/streampark-flink-proxy/src/main/scala/org/apache/streampark/flink/proxy/FlinkShimsProxy.scala
Labels: INFRA, FLINK

#3864 [Improve] docker setting improvements
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/AppBuildPipeServiceImpl.java
Labels: BACKEND

#3867 [Improve] parse flink version minor improvement
  streampark-common/src/main/scala/org/apache/streampark/common/conf/FlinkVersion.scala
Labels: BACKEND

#3823 [ISSUE-3812][Feature] Introduce token management e2e test
  .github/workflows/e2e.yml
  streampark-e2e/streampark-e2e-case/src/test/java/org/apache/streampark/e2e/cases/TokenManagementTest.java
  streampark-e2e/streampark-e2e-case/src/test/java/org/apache/streampark/e2e/pages/system/SystemPage.java
  streampark-e2e/streampark-e2e-case/src/test/java/org/apache/streampark/e2e/pages/system/TokenManagementPage.java
Labels: INFRA

#3869 [Chore] Improve ci build speed
  .github/workflows/backend.yml
  .github/workflows/unit-test.yml
Labels: INFRA

#3874 [Bug] Fix yarn queue page 404 not found
  streampark-console/streampark-console-service/src/main/assembly/script/data/mysql-data.sql
  streampark-console/streampark-console-service/src/main/assembly/script/data/pgsql-data.sql
  streampark-console/streampark-console-service/src/main/assembly/script/upgrade/mysql/2.2.2.sql
  streampark-console/streampark-console-service/src/main/resources/db/data-h2.sql
  streampark-console/streampark-console-webapp/src/views/setting/yarn-queue/View.vue
  streampark-console/streampark-console-webapp/src/views/setting/yarn-queue/YarnQueueDrawer.vue
  streampark-console/streampark-console-webapp/src/views/setting/yarn-queue/index.data.ts
  streampark-console/streampark-console-webapp/src/views/setting/yarn-queue/useYarnQueueRender.tsx
Labels: BUILD, WEB UI, BACKEND

#3875 [Hotfix] Fix document link address error.
  streampark-console/streampark-console-webapp/src/settings/siteSetting.ts
Labels: WEB UI

#3877 [Hotfix] The MySQL Connector/J is incompatible with the Apache 2.0 license.
  pom.xml
Labels: BUILD

#3876 [Improve] parse flink version improvement
  streampark-common/src/main/scala/org/apache/streampark/common/conf/FlinkVersion.scala
Labels: BACKEND

#3878 [Chore] Add dependency license check
  .github/workflows/backend.yml
  .gitignore
  .licenserc.yaml
  tools/dependencies/check-LICENSE.sh
  tools/dependencies/known-dependencies.txt
Labels: INFRA

#3881 [Improvement] Improvement in releasing system-provided demo job null pointer exception when using streampark for the first time
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/application/impl/ApplicationInfoServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/AppBuildPipeServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/FlinkEnvServiceImpl.java
Labels: BACKEND

#3888 [Feature] Introduce external link e2e test
  .github/workflows/e2e.yml
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ExternalLinkServiceImpl.java
  streampark-e2e/streampark-e2e-case/src/test/java/org/apache/streampark/e2e/cases/ExternalLinkPageTest.java
  streampark-e2e/streampark-e2e-case/src/test/java/org/apache/streampark/e2e/pages/setting/ExternalLinkPage.java
  streampark-e2e/streampark-e2e-case/src/test/java/org/apache/streampark/e2e/pages/setting/SettingPage.java
Labels: INFRA, BACKEND

#3890 [Feature-3861] Add Flink on Yarn yarn session with FlinkSQL e2e test
  streampark-console/streampark-console-webapp/src/views/flink/app/hooks/useFlinkRender.tsx
  streampark-e2e/streampark-e2e-case/src/test/java/org/apache/streampark/e2e/cases/FlinkSQL116OnYarnTest.java
  streampark-e2e/streampark-e2e-case/src/test/java/org/apache/streampark/e2e/cases/FlinkSQL117OnYarnTest.java
  streampark-e2e/streampark-e2e-case/src/test/java/org/apache/streampark/e2e/cases/FlinkSQL118OnYarnTest.java
  streampark-e2e/streampark-e2e-case/src/test/java/org/apache/streampark/e2e/pages/common/Constants.java
  streampark-e2e/streampark-e2e-case/src/test/java/org/apache/streampark/e2e/pages/flink/applications/ApplicationForm.java
  streampark-e2e/streampark-e2e-case/src/test/java/org/apache/streampark/e2e/pages/flink/applications/FlinkSQLEditor.java
  streampark-e2e/streampark-e2e-case/src/test/java/org/apache/streampark/e2e/pages/flink/applications/FlinkSQLYarnApplicationForm.java
  streampark-e2e/streampark-e2e-case/src/test/java/org/apache/streampark/e2e/pages/flink/applications/entity/ApplicationsDynamicParams.java
  streampark-e2e/streampark-e2e-case/src/test/java/org/apache/streampark/e2e/pages/flink/clusters/FlinkClustersPage.java
  streampark-e2e/streampark-e2e-case/src/test/resources/docker/flink-1.16-on-yarn/docker-compose.config
  streampark-e2e/streampark-e2e-case/src/test/resources/docker/flink-1.17-on-yarn/docker-compose.config
  streampark-e2e/streampark-e2e-case/src/test/resources/docker/flink-1.18-on-yarn/docker-compose.config
  streampark-e2e/streampark-e2e-core/src/main/java/org/apache/streampark/e2e/core/Constants.java
Labels: WEB UI

#3892 [Cherry-pick] Fix document link address error. (#3875)
  streampark-console/streampark-console-webapp/src/settings/siteSetting.ts
Labels: WEB UI

#3893 [Improve] Remove swagger dependencies.
  streampark-console/streampark-console-service/pom.xml
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/base/config/OpenapiConfig.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/base/domain/ApiDocConstant.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/base/domain/RestRequest.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/bean/AlertConfigWithParams.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/bean/AlertDingTalkParams.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/bean/AlertEmailParams.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/bean/AlertHttpCallbackParams.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/bean/AlertLarkParams.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/bean/AlertWeComParams.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/controller/ApplicationController.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/controller/IndexController.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/controller/AccessTokenController.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/controller/PassportController.java
Labels: BUILD, BACKEND

#3900 [Improve] spark-submit improvements
  streampark-common/src/main/scala/org/apache/streampark/common/util/ChildFirstClassLoader.scala
  streampark-common/src/main/scala/org/apache/streampark/common/util/ClassLoaderObjectInputStream.scala
  streampark-flink/streampark-flink-client/streampark-flink-client-core/src/main/scala/org/apache/streampark/flink/client/trait/FlinkClientTrait.scala
  streampark-flink/streampark-flink-proxy/src/main/scala/org/apache/streampark/flink/proxy/ChildFirstClassLoader.scala
  streampark-flink/streampark-flink-proxy/src/main/scala/org/apache/streampark/flink/proxy/ClassLoaderObjectInputStream.scala
  streampark-flink/streampark-flink-proxy/src/main/scala/org/apache/streampark/flink/proxy/FlinkShimsProxy.scala
  streampark-spark/streampark-spark-client/streampark-spark-client-api/src/main/scala/org/apache/streampark/spark/client/bean/SubmitRequest.scala
  streampark-spark/streampark-spark-client/streampark-spark-client-api/src/main/scala/org/apache/streampark/spark/client/conf/SparkConfiguration.scala
  streampark-spark/streampark-spark-client/streampark-spark-client-api/src/main/scala/org/apache/streampark/spark/client/proxy/SparkShimsProxy.scala
  streampark-spark/streampark-spark-client/streampark-spark-client-core/src/main/scala/org/apache/streampark/spark/client/impl/YarnApplicationClient.scala
  streampark-spark/streampark-spark-client/streampark-spark-client-core/src/main/scala/org/apache/streampark/spark/client/trait/SparkClientTrait.scala
Labels: BACKEND, FLINK, SPARK

#3901 [Improve] spark-submit some improvements
  streampark-common/src/main/java/org/apache/streampark/common/enums/SparkDevelopmentMode.java
  streampark-common/src/main/java/org/apache/streampark/common/enums/SparkExecutionMode.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/entity/SparkApplication.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/application/impl/SparkApplicationActionServiceImpl.java
  streampark-flink/streampark-flink-client/streampark-flink-client-api/src/main/scala/org/apache/streampark/flink/client/bean/SubmitRequest.scala
  streampark-spark/streampark-spark-client/streampark-spark-client-api/src/main/scala/org/apache/streampark/spark/client/bean/StopRequest.scala
  streampark-spark/streampark-spark-client/streampark-spark-client-api/src/main/scala/org/apache/streampark/spark/client/bean/StopResponse.scala
  streampark-spark/streampark-spark-client/streampark-spark-client-api/src/main/scala/org/apache/streampark/spark/client/bean/SubmitRequest.scala
  streampark-spark/streampark-spark-client/streampark-spark-client-api/src/main/scala/org/apache/streampark/spark/client/bean/SubmitResponse.scala
  streampark-spark/streampark-spark-client/streampark-spark-client-core/src/main/scala/org/apache/streampark/spark/client/SparkClientEndpoint.scala
  streampark-spark/streampark-spark-client/streampark-spark-client-core/src/main/scala/org/apache/streampark/spark/client/impl/YarnClient.scala
  streampark-spark/streampark-spark-client/streampark-spark-client-core/src/main/scala/org/apache/streampark/spark/client/trait/SparkClientTrait.scala
Labels: BACKEND, FLINK, SPARK

#3891 [Bug] fix resource variable dependent apps page 404 not found
  streampark-console/streampark-console-service/src/main/assembly/script/data/mysql-data.sql
  streampark-console/streampark-console-service/src/main/assembly/script/data/pgsql-data.sql
  streampark-console/streampark-console-service/src/main/assembly/script/upgrade/mysql/2.2.2.sql
  streampark-console/streampark-console-service/src/main/resources/db/data-h2.sql
  streampark-console/streampark-console-webapp/src/views/resource/variable/View.vue
Labels: BUILD, WEB UI, BACKEND

#3908 [Bug] Correct spark app submitting process
  streampark-common/src/main/scala/org/apache/streampark/common/conf/SparkVersion.scala
  streampark-spark/streampark-spark-client/streampark-spark-client-core/src/main/scala/org/apache/streampark/spark/client/impl/YarnClient.scala
Labels: BACKEND, SPARK

#3909 [Improvement] Some code optimization
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/bean/AlertTemplate.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/component/FlinkCheckpointProcessor.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/entity/Application.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/entity/FlinkStateChangeEvent.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/enums/FlinkAppStateEnum.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/enums/OptionStateEnum.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/utils/AlertTemplateUtils.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/watcher/FlinkAppHttpWatcher.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/watcher/FlinkClusterWatcher.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/watcher/FlinkK8sChangeEventListener.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/watcher/SparkAppHttpWatcher.java
Labels: BACKEND

#3899 [Feature] Introduce alarm e2e test
  .github/workflows/e2e.yml
  streampark-e2e/streampark-e2e-case/src/test/java/org/apache/streampark/e2e/cases/AlarmTest.java
  streampark-e2e/streampark-e2e-case/src/test/java/org/apache/streampark/e2e/cases/ExternalLinkTest.java
  streampark-e2e/streampark-e2e-case/src/test/java/org/apache/streampark/e2e/pages/setting/SettingPage.java
  streampark-e2e/streampark-e2e-case/src/test/java/org/apache/streampark/e2e/pages/setting/alarm/AlarmPage.java
  streampark-e2e/streampark-e2e-case/src/test/java/org/apache/streampark/e2e/pages/setting/alarm/AlertTypeDetailForm.java
  streampark-e2e/streampark-e2e-case/src/test/java/org/apache/streampark/e2e/pages/setting/alarm/CommonForm.java
  streampark-e2e/streampark-e2e-case/src/test/java/org/apache/streampark/e2e/pages/setting/alarm/DingTalkAlertForm.java
  streampark-e2e/streampark-e2e-case/src/test/java/org/apache/streampark/e2e/pages/setting/alarm/EmailAlertForm.java
  streampark-e2e/streampark-e2e-case/src/test/java/org/apache/streampark/e2e/pages/setting/alarm/LarkAlertForm.java
  streampark-e2e/streampark-e2e-case/src/test/java/org/apache/streampark/e2e/pages/setting/alarm/SMSAlertForm.java
  streampark-e2e/streampark-e2e-case/src/test/java/org/apache/streampark/e2e/pages/setting/alarm/WeChatAlertForm.java
Labels: INFRA

#3906 [Chore] Add spip issue template
  .github/ISSUE_TEMPLATE/spip-request.yml
Labels: INFRA

#3916 [Improve] openapi request parameter schema improvement
  streampark-console/streampark-console-service/src/main/assembly/conf/config.yaml
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/aspect/StreamParkAspect.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/bean/OpenAPISchema.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/component/OpenAPIComponent.java
Labels: BUILD, BACKEND

#3915 [Improve]: add openapi schema modal
  streampark-console/streampark-console-webapp/.npmrc
  streampark-console/streampark-console-webapp/src/api/flink/savepoint.ts
  streampark-console/streampark-console-webapp/src/api/system/openapi.ts
  streampark-console/streampark-console-webapp/src/assets/icons/api.svg
  streampark-console/streampark-console-webapp/src/components/OpenApi/index.ts
  streampark-console/streampark-console-webapp/src/components/OpenApi/src/index.tsx
  streampark-console/streampark-console-webapp/src/design/ant/index.less
  streampark-console/streampark-console-webapp/src/locales/lang/en/component.ts
  streampark-console/streampark-console-webapp/src/locales/lang/en/flink/app.ts
  streampark-console/streampark-console-webapp/src/locales/lang/zh-CN/component.ts
  streampark-console/streampark-console-webapp/src/locales/lang/zh-CN/flink/app.ts
  streampark-console/streampark-console-webapp/src/views/flink/app/Detail.vue
  streampark-console/streampark-console-webapp/src/views/flink/app/components/AppDetail/DetailTab.vue
  streampark-console/streampark-console-webapp/src/views/flink/app/components/RequestModal/index.tsx
  streampark-console/streampark-console-webapp/src/views/flink/app/hooks/useApp.tsx
Labels: WEB UI

#3917 [Fix]: Improve style issue in dark mode
  streampark-console/streampark-console-webapp/src/components/OpenApi/src/index.tsx
  streampark-console/streampark-console-webapp/src/design/ant/index.less
Labels: WEB UI

#3919 [Fix]: Add the missing License header
  streampark-console/streampark-console-webapp/src/components/OpenApi/index.ts
Labels: WEB UI

#3921 [Improve] token status improvement
  streampark-console/streampark-console-service/src/main/assembly/conf/config.yaml
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/aspect/StreamParkAspect.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/controller/AlertController.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/controller/OpenAPIController.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/enums/AccessTokenStateEnum.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/ServiceHelper.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/authentication/ShiroRealm.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/controller/AccessTokenController.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/controller/MemberController.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/service/AccessTokenService.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/service/impl/AccessTokenServiceImpl.java
  streampark-console/streampark-console-service/src/main/resources/mapper/system/AccessTokenMapper.xml
  streampark-console/streampark-console-webapp/src/api/index.ts
  streampark-console/streampark-console-webapp/src/locales/lang/en/flink/app.ts
  streampark-console/streampark-console-webapp/src/locales/lang/zh-CN/flink/app.ts
  streampark-console/streampark-console-webapp/src/views/flink/app/components/RequestModal/index.tsx
  streampark-console/streampark-console-webapp/src/views/system/token/token.data.ts
Labels: BUILD, WEB UI, BACKEND

#3922 [Improve] default team improvement
  streampark-console/streampark-console-service/src/main/assembly/script/data/pgsql-data.sql
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/base/domain/Constant.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/authentication/JWTToken.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/controller/PassportController.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/controller/SsoController.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/controller/UserController.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/service/TeamService.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/service/UserService.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/service/impl/AccessTokenServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/service/impl/TeamServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/service/impl/UserServiceImpl.java
  streampark-console/streampark-console-service/src/main/resources/db/data-h2.sql
  streampark-console/streampark-console-webapp/src/api/system/user.ts
  streampark-console/streampark-console-webapp/src/store/modules/user.ts
  streampark-console/streampark-console-webapp/src/views/base/login/LoginForm.vue
Labels: BUILD, WEB UI, BACKEND

#3928 [Improvement] Docker improvement
  docker/Dockerfile
  docker/README.md
  docker/config.yaml
  docker/docker-compose.yaml
Labels: DOCS

#3931 feature: add flink webui proxy
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/controller/ProxyController.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/entity/Application.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/ApplicationService.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ApplicationServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/authentication/ShiroConfig.java
Labels: BACKEND
