Repository apache/streampark, pull requests merged in 2024-08, with the labels that each got.

#3932 [Improve] flink webUI proxy support.
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/controller/ProxyController.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/entity/Application.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/ApplicationService.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/ProxyService.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/ServiceHelper.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ApplicationServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ProxyServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/authentication/ShiroConfig.java
  streampark-console/streampark-console-webapp/src/views/flink/app/Detail.vue
  streampark-console/streampark-console-webapp/src/views/flink/app/View.vue
  streampark-console/streampark-console-webapp/src/views/flink/app/components/AppDetail/DetailTab.vue
  streampark-console/streampark-console-webapp/src/views/flink/app/utils/index.ts
Labels: WEB UI, BACKEND

#3938 [Improve] openapi access bug fixed.
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/base/util/WebUtils.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/controller/OpenAPIController.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/controller/ProxyController.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/ProxyService.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ProxyServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/authentication/JWTFilter.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/authentication/JWTToken.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/authentication/JWTUtil.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/authentication/ShiroRealm.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/controller/AccessTokenController.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/controller/PassportController.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/controller/UserController.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/entity/AccessToken.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/runner/StartedUpRunner.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/service/AccessTokenService.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/service/UserService.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/service/impl/AccessTokenServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/service/impl/UserServiceImpl.java
  streampark-console/streampark-console-service/src/test/java/org/apache/streampark/console/core/service/AccessTokenServiceTest.java
  streampark-console/streampark-console-service/src/test/java/org/apache/streampark/console/system/authentication/JWTTest.java
Labels: BACKEND

#3939 [Improve] Shiro session cannot expire bug fixed
  streampark-common/src/main/scala/org/apache/streampark/common/util/CURLBuilder.scala
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/base/util/WebUtils.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/annotation/AppChangeEvent.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/annotation/OpenAPI.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/aspect/AppChangeEventAspect.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/aspect/OpenAPIAspect.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/aspect/PermissionAspect.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/component/FlinkCheckpointProcessor.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/component/OpenAPIComponent.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/controller/ApplicationController.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/controller/OpenAPIController.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/controller/ProjectController.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/controller/SavepointController.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/controller/SparkApplicationController.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/entity/Application.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/entity/Savepoint.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/entity/SparkApplication.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/mapper/SavepointMapper.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/SavepointService.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/application/impl/ApplicationActionServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/application/impl/ApplicationInfoServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/application/impl/ApplicationManageServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/application/impl/SparkApplicationInfoServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/application/impl/SparkApplicationManageServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/SavepointServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/watcher/FlinkAppHttpWatcher.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/authentication/JWTFilter.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/authentication/JWTToken.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/authentication/JWTUtil.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/authentication/ShiroConfig.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/authentication/ShiroRealm.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/controller/AccessTokenController.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/controller/PassportController.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/controller/SsoController.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/controller/UserController.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/entity/AccessToken.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/runner/StartedUpRunner.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/security/Authenticator.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/security/impl/AuthenticatorImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/service/AccessTokenService.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/service/UserService.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/service/impl/AccessTokenServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/service/impl/UserServiceImpl.java
  streampark-console/streampark-console-service/src/main/resources/mapper/core/SavepointMapper.xml
  streampark-console/streampark-console-service/src/test/java/org/apache/streampark/console/core/service/AccessTokenServiceTest.java
  streampark-console/streampark-console-service/src/test/java/org/apache/streampark/console/core/service/ApplicationManageServiceTest.java
  streampark-console/streampark-console-service/src/test/java/org/apache/streampark/console/core/service/SavepointServiceTest.java
  streampark-console/streampark-console-service/src/test/java/org/apache/streampark/console/system/authentication/JWTTest.java
  streampark-console/streampark-console-webapp/src/api/flink/app.ts
  streampark-console/streampark-console-webapp/src/api/flink/app.type.ts
  streampark-console/streampark-console-webapp/src/locales/lang/en/flink/app.ts
  streampark-console/streampark-console-webapp/src/locales/lang/zh-CN/flink/app.ts
  streampark-console/streampark-console-webapp/src/views/flink/app/components/AppView/StartApplicationModal.vue
  streampark-console/streampark-console-webapp/src/views/flink/app/components/AppView/StopApplicationModal.vue
  streampark-console/streampark-console-webapp/src/views/flink/app/hooks/useSavepoint.tsx
  streampark-e2e/streampark-e2e-case/src/test/java/org/apache/streampark/e2e/pages/flink/applications/ApplicationsPage.java
  streampark-flink/streampark-flink-client/streampark-flink-client-api/src/main/scala/org/apache/streampark/flink/client/bean/CancelResponse.scala
  streampark-flink/streampark-flink-client/streampark-flink-client-api/src/main/scala/org/apache/streampark/flink/client/bean/SavepointResponse.scala
Labels: WEB UI, BACKEND, FLINK

#3944 [Improve] notify message improvement
  streampark-console/streampark-console-service/pom.xml
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/base/config/WebSocketConfig.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/controller/MessageController.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/MessageService.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/AppBuildPipeServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/MessageServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/websocket/WebSocketEndpoint.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/authentication/ShiroConfig.java
  streampark-console/streampark-console-webapp/src/api/system/notify.ts
  streampark-console/streampark-console-webapp/src/layouts/default/header/components/notify/index.vue
Labels: BUILD, WEB UI, BACKEND

#3936 [catalog] Introduce catalog managed
  streampark-common/src/main/java/org/apache/streampark/common/enums/CatalogType.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/base/util/JacksonUtils.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/bean/FlinkCatalogParams.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/controller/CatalogController.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/entity/FlinkCatalog.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/mapper/CatalogMapper.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/CatalogService.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/CatalogServiceImpl.java
  streampark-console/streampark-console-service/src/main/resources/db/schema-h2.sql
  streampark-console/streampark-console-service/src/main/resources/mapper/core/CatalogMapper.xml
  streampark-console/streampark-console-service/src/test/java/org/apache/streampark/console/core/service/CatalogServiceTest.java
Labels: BACKEND

#3911 [Feature] Introduce environment e2e test
  .github/workflows/e2e.yml
  streampark-e2e/streampark-e2e-case/src/test/java/org/apache/streampark/e2e/cases/EnvironmentTest.java
  streampark-e2e/streampark-e2e-case/src/test/java/org/apache/streampark/e2e/pages/common/CommonFactory.java
  streampark-e2e/streampark-e2e-case/src/test/java/org/apache/streampark/e2e/pages/setting/SettingPage.java
  streampark-e2e/streampark-e2e-case/src/test/java/org/apache/streampark/e2e/pages/setting/env/CommonForm.java
  streampark-e2e/streampark-e2e-case/src/test/java/org/apache/streampark/e2e/pages/setting/env/DockerSettingForm.java
  streampark-e2e/streampark-e2e-case/src/test/java/org/apache/streampark/e2e/pages/setting/env/EmailSettingForm.java
  streampark-e2e/streampark-e2e-case/src/test/java/org/apache/streampark/e2e/pages/setting/env/EnvironmentDetailForm.java
  streampark-e2e/streampark-e2e-case/src/test/java/org/apache/streampark/e2e/pages/setting/env/EnvironmentPage.java
  streampark-e2e/streampark-e2e-case/src/test/java/org/apache/streampark/e2e/pages/setting/env/IngressSettingForm.java
  streampark-e2e/streampark-e2e-case/src/test/java/org/apache/streampark/e2e/pages/setting/env/MavenSettingForm.java
  streampark-e2e/streampark-e2e-case/src/test/resources/docker/environment/Dockerfile
  streampark-e2e/streampark-e2e-case/src/test/resources/docker/environment/docker-compose.yaml
Labels: INFRA

#3951 [Bug] Fix: Kerberos authentication issues may occur in Flink on YARN
  streampark-common/src/main/scala/org/apache/streampark/common/util/HadoopUtils.scala
  streampark-flink/streampark-flink-client/streampark-flink-client-core/src/main/scala/org/apache/streampark/flink/client/impl/YarnApplicationClient.scala
  streampark-flink/streampark-flink-client/streampark-flink-client-core/src/main/scala/org/apache/streampark/flink/client/impl/YarnPerJobClient.scala
  streampark-flink/streampark-flink-client/streampark-flink-client-core/src/main/scala/org/apache/streampark/flink/client/impl/YarnSessionClient.scala
  streampark-flink/streampark-flink-client/streampark-flink-client-core/src/main/scala/org/apache/streampark/flink/client/trait/YarnClientTrait.scala
Labels: first time contributor, BACKEND, FLINK

#3953 [Improve] default team member improvement
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/base/domain/Constant.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/service/RoleService.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/service/impl/RoleServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/service/impl/UserServiceImpl.java
Labels: BACKEND

#3955 [Bug] Fix: Set a default password for Ldap user
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/entity/User.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/security/impl/AuthenticatorImpl.java
Labels: BACKEND

#3956 [Cherry-pick] default team member improvement 3953
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/base/domain/Constant.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/service/RoleService.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/service/impl/RoleServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/service/impl/UserServiceImpl.java
Labels: BACKEND

#3967 [Improve] add streampark task id in external link
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/enums/PlaceholderTypeEnum.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ExternalLinkServiceImpl.java
  streampark-console/streampark-console-webapp/src/views/setting/extlink/components/Modal.vue
Labels: WEB UI, BACKEND

#3965 Fix the issue where failure to start in k8s mode cannot be stopped.
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/enums/FlinkAppState.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ApplicationServiceImpl.java
  streampark-flink/streampark-flink-kubernetes/src/main/scala/org/apache/streampark/flink/kubernetes/enums/FlinkJobState.scala
  streampark-flink/streampark-flink-kubernetes/src/main/scala/org/apache/streampark/flink/kubernetes/watcher/FlinkJobStatusWatcher.scala
Labels: BACKEND, FLINK, KUBERNETES

#3969 [Improve] add spark menu
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/SettingService.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/SettingServiceImpl.java
  streampark-console/streampark-console-service/src/main/resources/db/data-h2.sql
  streampark-console/streampark-console-webapp/src/components/SimpleMenu/src/SimpleSubMenu.vue
  streampark-console/streampark-console-webapp/src/locales/lang/en/menu.ts
  streampark-console/streampark-console-webapp/src/locales/lang/zh-CN/menu.ts
Labels: WEB UI, BACKEND

#3973 [Improve] job on yarn state bug fixed.
  streampark-common/src/main/scala/org/apache/streampark/common/util/YarnUtils.scala
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/mapper/ApplicationMapper.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/ApplicationService.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ApplicationServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/task/FlinkAppHttpWatcher.java
  streampark-console/streampark-console-service/src/main/resources/mapper/core/ApplicationMapper.xml
Labels: BACKEND, YARN

#3979 fix(streampark-console): Proxy and Session Issues with YARN HTTP Kerb…
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/entity/FlinkCluster.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/FlinkClusterServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ProxyServiceImpl.java
Labels: BACKEND

#3977 [Improve]: add spark home page
  streampark-console/streampark-console-webapp/src/api/spark/home.ts
  streampark-console/streampark-console-webapp/src/api/spark/home.type.ts
  streampark-console/streampark-console-webapp/src/enums/sparkEnum.ts
  streampark-console/streampark-console-webapp/src/locales/lang/en/spark/home.ts
  streampark-console/streampark-console-webapp/src/locales/lang/zh-CN/spark/home.ts
  streampark-console/streampark-console-webapp/src/views/spark/app.vue
  streampark-console/streampark-console-webapp/src/views/spark/components/Modal.vue
  streampark-console/streampark-console-webapp/src/views/spark/components/index.ts
  streampark-console/streampark-console-webapp/src/views/spark/home.vue
Labels: WEB UI

#3982 [Improve] proxy bug fixed.
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/controller/ProxyController.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/ProxyService.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ProxyServiceImpl.java
  streampark-console/streampark-console-webapp/src/views/flink/app/components/AppDetail/DetailTab.vue
  streampark-console/streampark-console-webapp/src/views/flink/app/utils/index.ts
Labels: WEB UI, BACKEND

#3986 [Improve] Improved proxy permission checks and fixed URL bug for YARN…
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/controller/ProxyController.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ProxyServiceImpl.java
Labels: BACKEND

#3990 [ISSUES-3983] Job dependencies limit the default number of uploaded jars
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/application/impl/ApplicationInfoServiceImpl.java
Labels: BACKEND

#3989 [improve] job on yarn state patch.
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/mapper/ApplicationLogMapper.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/ApplicationLogService.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ApplicationLogServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/task/FlinkAppHttpWatcher.java
  streampark-console/streampark-console-service/src/main/resources/mapper/core/ApplicationLogMapper.xml
Labels: BACKEND

#3993 [Improve] configHolder get value bug fixed.
  streampark-common/src/main/scala/org/apache/streampark/common/conf/InternalConfigHolder.scala
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/runner/EnvInitializer.java
Labels: BACKEND

#3992 [Improve]: add spark application create page
  streampark-console/streampark-console-webapp/src/api/spark/app.ts
  streampark-console/streampark-console-webapp/src/api/spark/app.type.ts
  streampark-console/streampark-console-webapp/src/api/spark/conf.ts
  streampark-console/streampark-console-webapp/src/api/spark/sql.ts
  streampark-console/streampark-console-webapp/src/components/SimpleMenu/src/SimpleSubMenu.vue
  streampark-console/streampark-console-webapp/src/enums/sparkEnum.ts
  streampark-console/streampark-console-webapp/src/views/flink/app/hooks/useCreateAndEditSchema.ts
  streampark-console/streampark-console-webapp/src/views/spark/app/components/AppDashboard.vue
  streampark-console/streampark-console-webapp/src/views/spark/app/components/AppStartModal.vue
  streampark-console/streampark-console-webapp/src/views/spark/app/components/Mergely.vue
  streampark-console/streampark-console-webapp/src/views/spark/app/components/ProgramArgs.vue
  streampark-console/streampark-console-webapp/src/views/spark/app/components/SparkSql.vue
  streampark-console/streampark-console-webapp/src/views/spark/app/components/StatisticCard.vue
  streampark-console/streampark-console-webapp/src/views/spark/app/components/VariableReview.vue
  streampark-console/streampark-console-webapp/src/views/spark/app/create.vue
  streampark-console/streampark-console-webapp/src/views/spark/app/data/index.ts
  streampark-console/streampark-console-webapp/src/views/spark/app/hooks/useAppFormSchema.tsx
  streampark-console/streampark-console-webapp/src/views/spark/app/hooks/useFlinkRender.tsx
  streampark-console/streampark-console-webapp/src/views/spark/app/hooks/useSparkAction.tsx
  streampark-console/streampark-console-webapp/src/views/spark/app/hooks/useSparkColumns.ts
  streampark-console/streampark-console-webapp/src/views/spark/app/hooks/useSparkTableAction.ts
  streampark-console/streampark-console-webapp/src/views/spark/app/index.vue
  streampark-console/streampark-console-webapp/src/views/spark/app/sqlFormatter.js
  streampark-console/streampark-console-webapp/src/views/spark/app/styles/View.less
Labels: WEB UI

#3994 [Improve] apahce flink 1.20 support
  streampark-common/src/main/scala/org/apache/streampark/common/conf/FlinkVersion.scala
  streampark-console/streampark-console-service/pom.xml
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/runner/EnvInitializer.java
  streampark-flink/streampark-flink-shims/pom.xml
  streampark-flink/streampark-flink-shims/streampark-flink-shims_flink-1.20/pom.xml
  streampark-flink/streampark-flink-shims/streampark-flink-shims_flink-1.20/src/main/scala/org/apache/streampark/flink/core/FlinkClusterClient.scala
  streampark-flink/streampark-flink-shims/streampark-flink-shims_flink-1.20/src/main/scala/org/apache/streampark/flink/core/FlinkKubernetesClient.scala
  streampark-flink/streampark-flink-shims/streampark-flink-shims_flink-1.20/src/main/scala/org/apache/streampark/flink/core/StreamTableContext.scala
  streampark-flink/streampark-flink-shims/streampark-flink-shims_flink-1.20/src/main/scala/org/apache/streampark/flink/core/TableContext.scala
  streampark-flink/streampark-flink-shims/streampark-flink-shims_flink-1.20/src/main/scala/org/apache/streampark/flink/core/TableExt.scala
Labels: BUILD, BACKEND, FLINK

#3995 [Improve] k8s application mode trigger savepoint bug fixed.
  logback-spring.xml
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/controller/ProxyController.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/entity/Application.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/SavepointServiceImpl.java
  streampark-console/streampark-console-webapp/src/api/flink/app/app.ts
  streampark-flink/streampark-flink-client/streampark-flink-client-core/src/main/scala/org/apache/streampark/flink/client/impl/RemoteClient.scala
Labels: WEB UI, BACKEND, FLINK

#3999 Change link_url to text type.
  streampark-console/streampark-console-service/src/main/assembly/script/schema/mysql-schema.sql
  streampark-console/streampark-console-service/src/main/assembly/script/schema/pgsql-schema.sql
  streampark-console/streampark-console-service/src/main/assembly/script/upgrade/mysql/2.1.5.sql
  streampark-console/streampark-console-service/src/main/assembly/script/upgrade/pgsql/2.1.5.sql
Labels: BUILD, BACKEND

#3998 Fix the "java.nio.file.NoSuchFileException: /root/.kube/config" exception by not providing the Kube Conf File parameter when starting the k8s session cluster.
  streampark-flink/streampark-flink-client/streampark-flink-client-api/src/main/scala/org/apache/streampark/flink/client/bean/DeployRequest.scala
  streampark-flink/streampark-flink-client/streampark-flink-client-core/src/main/scala/org/apache/streampark/flink/client/trait/KubernetesNativeClientTrait.scala
Labels: FLINK

#4000 [Improve] proxy minor improvement
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ProxyServiceImpl.java
Labels: BACKEND

#4002 [Bug] save checkpoint bug fixed.
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ApplicationServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/task/CheckpointProcessor.java
Labels: BACKEND

#4004 [Improve] flink checkpointing conf key minor improvement
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/SavepointServiceImpl.java
Labels: BACKEND

#3981 [Feature] Introduce flink on remote cluster e2e test
  .github/workflows/e2e.yml
  streampark-e2e/streampark-e2e-case/src/test/java/org/apache/streampark/e2e/cases/Flink116OnRemoteClusterDeployTest.java
  streampark-e2e/streampark-e2e-case/src/test/java/org/apache/streampark/e2e/cases/Flink117OnRemoteClusterDeployTest.java
  streampark-e2e/streampark-e2e-case/src/test/java/org/apache/streampark/e2e/cases/Flink118OnRemoteClusterDeployTest.java
  streampark-e2e/streampark-e2e-case/src/test/java/org/apache/streampark/e2e/pages/flink/clusters/ClusterDetailForm.java
  streampark-e2e/streampark-e2e-case/src/test/java/org/apache/streampark/e2e/pages/flink/clusters/RemoteForm.java
  streampark-e2e/streampark-e2e-case/src/test/resources/docker/flink-1.16-on-remote/Dockerfile
  streampark-e2e/streampark-e2e-case/src/test/resources/docker/flink-1.16-on-remote/docker-compose.yaml
  streampark-e2e/streampark-e2e-case/src/test/resources/docker/flink-1.17-on-remote/Dockerfile
  streampark-e2e/streampark-e2e-case/src/test/resources/docker/flink-1.17-on-remote/docker-compose.yaml
  streampark-e2e/streampark-e2e-case/src/test/resources/docker/flink-1.18-on-remote/Dockerfile
  streampark-e2e/streampark-e2e-case/src/test/resources/docker/flink-1.18-on-remote/docker-compose.yaml
Labels: INFRA

#4006 [Improve] checkpoint save bug fixed.
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/mapper/SavepointMapper.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/SavepointServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/task/CheckpointProcessor.java
  streampark-console/streampark-console-service/src/main/resources/mapper/core/SavepointMapper.xml
Labels: BACKEND

#4007 [Improve] Flink-Yarn multi-version adaptation
  streampark-flink/streampark-flink-client/streampark-flink-client-core/src/main/scala/org/apache/streampark/flink/client/impl/YarnPerJobClient.scala
  streampark-flink/streampark-flink-shims/streampark-flink-shims-base/pom.xml
  streampark-flink/streampark-flink-shims/streampark-flink-shims-base/src/main/scala/org/apache/streampark/flink/core/YarnClusterDescriptorTrait.scala
  streampark-flink/streampark-flink-shims/streampark-flink-shims_flink-1.12/src/main/scala/org/apache/streampark/flink/core/YarnClusterDescriptorWrapper.scala
  streampark-flink/streampark-flink-shims/streampark-flink-shims_flink-1.13/src/main/scala/org/apache/streampark/flink/core/YarnClusterDescriptorWrapper.scala
  streampark-flink/streampark-flink-shims/streampark-flink-shims_flink-1.14/src/main/scala/org/apache/streampark/flink/core/YarnClusterDescriptorWrapper.scala
  streampark-flink/streampark-flink-shims/streampark-flink-shims_flink-1.15/src/main/scala/org/apache/streampark/flink/core/YarnClusterDescriptorWrapper.scala
  streampark-flink/streampark-flink-shims/streampark-flink-shims_flink-1.16/src/main/scala/org/apache/streampark/flink/core/YarnClusterDescriptorWrapper.scala
  streampark-flink/streampark-flink-shims/streampark-flink-shims_flink-1.17/src/main/scala/org/apache/streampark/flink/core/YarnClusterDescriptorWrapper.scala
  streampark-flink/streampark-flink-shims/streampark-flink-shims_flink-1.18/src/main/scala/org/apache/streampark/flink/core/YarnClusterDescriptorWrapper.scala
  streampark-flink/streampark-flink-shims/streampark-flink-shims_flink-1.19/src/main/scala/org/apache/streampark/flink/core/YarnClusterDescriptorWrapper.scala
  streampark-flink/streampark-flink-shims/streampark-flink-shims_flink-1.20/src/main/scala/org/apache/streampark/flink/core/YarnClusterDescriptorWrapper.scala
Labels: BUILD, FLINK

#4008 [Feat] git clone by tag support.
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/base/util/GitUtils.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/ProjectService.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ProjectServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/task/ProjectBuildTask.java
  streampark-console/streampark-console-service/src/test/java/org/apache/streampark/console/core/service/ProjectServiceTest.java
  streampark-console/streampark-console-service/src/test/java/org/apache/streampark/console/core/utils/GitUtilsTest.java
Labels: BACKEND

#4009 [Feat] git clone by tag support.
  streampark-console/streampark-console-service/src/main/assembly/script/schema/mysql-schema.sql
  streampark-console/streampark-console-service/src/main/assembly/script/schema/pgsql-schema.sql
  streampark-console/streampark-console-service/src/main/assembly/script/upgrade/mysql/2.1.5.sql
  streampark-console/streampark-console-service/src/main/assembly/script/upgrade/pgsql/2.1.5.sql
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/base/util/GitUtils.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/controller/ProjectController.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/entity/Project.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ProjectServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/task/ProjectBuildTask.java
  streampark-console/streampark-console-service/src/main/resources/db/schema-h2.sql
  streampark-console/streampark-console-service/src/main/resources/mapper/core/ProjectMapper.xml
  streampark-console/streampark-console-webapp/src/api/flink/project/index.ts
  streampark-console/streampark-console-webapp/src/api/flink/project/model/projectModel.ts
  streampark-console/streampark-console-webapp/src/assets/icons/branch.svg
  streampark-console/streampark-console-webapp/src/assets/icons/tag.svg
  streampark-console/streampark-console-webapp/src/locales/lang/en/flink/app.ts
  streampark-console/streampark-console-webapp/src/locales/lang/en/flink/project.ts
  streampark-console/streampark-console-webapp/src/locales/lang/zh-CN/flink/project.ts
  streampark-console/streampark-console-webapp/src/views/flink/app/Detail.vue
  streampark-console/streampark-console-webapp/src/views/flink/app/View.vue
  streampark-console/streampark-console-webapp/src/views/flink/project/Add.vue
  streampark-console/streampark-console-webapp/src/views/flink/project/Edit.vue
  streampark-console/streampark-console-webapp/src/views/flink/project/components/ListItem.vue
  streampark-console/streampark-console-webapp/src/views/flink/project/useProject.tsx
Labels: BUILD, WEB UI, BACKEND

#4010 [Improve] jvm opt improvement
  streampark-console/streampark-console-service/src/main/assembly/bin/jvm_opts.sh
  streampark-console/streampark-console-service/src/main/assembly/bin/streampark.sh
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/runner/StartedUpRunner.java
Labels: BUILD, BACKEND

#4013 [Improve] flink app cancel bug fixed.
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/entity/Application.java
  streampark-console/streampark-console-webapp/src/views/flink/app/components/State.tsx
Labels: WEB UI, BACKEND

#4012 Optimize the user experience of the Flink web page proxy.
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/bean/AppControl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/controller/ProxyController.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ApplicationServiceImpl.java
  streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ProxyServiceImpl.java
  streampark-console/streampark-console-webapp/src/views/flink/app/Detail.vue
  streampark-console/streampark-console-webapp/src/views/flink/app/View.vue
Labels: WEB UI, BACKEND
